.gitignore
demo/index.scss
demo/pages/app/App.js
demo/pages/pages.js
demo/pages/tabs/TabsDemo.js
demo/pages/tabs/TabsDemo.scss
demo/pages/tabs/templates/ButtonTabDemo.html
demo/pages/tabs/templates/ColorDemo.html
demo/pages/tabs/templates/RouterDemo.html
demo/pages/tabs/templates/VerticalDemo.html
demo/pages/tabs/templates/WhiteDemo.html
src/elements/tabs.js
src/elements/tabs/README.md
src/elements/tabs/Tabs.e2e.js
src/elements/tabs/Tabs.js
src/elements/tabs/Tabs.scss
src/elements/tabs/Tabs.spec.js
src/novo-elements.js
src/novo-elements.scss

Adds Tabs element to demo, closes #19 
* Added "Tabs" element to demo
* Updated Tabs element README
* @jgodi

added tabs

---

demo/assets/styles/_sidenav.scss
demo/pages/app/App.html
src/assets/styles/global/_reset.scss

* Adds css to make elements with `[href]` have `cursor: pointer;`
* Moved `[routerLink]` on logo elements of sidenav
* @jgodi

fix(style): fixes href cursor styling

---

demo/assets/styles/_sidenav.scss
demo/index.scss
demo/pages/app/App.html
demo/pages/app/App.js
demo/pages/list/ListDemo.js
demo/pages/list/ListDemo.scss
demo/pages/list/templates/ListDemo.html
demo/pages/pages.js
src/assets/styles/global/_reset.scss
src/elements/list.js
src/elements/list/List.e2e.js
src/elements/list/List.js
src/elements/list/List.spec.js
src/elements/list/README.md
src/elements/list/_List.scss
src/novo-elements.js
src/novo-elements.scss

* Adds list component
* Adds list documentation & demo
* Closes #11 
* @jgodi

feat(list): Adds list component and documentation, closes #11

---

src/elements/header/_Header.scss

* Fixes SCSS on header to give `section.primary` the appropriate background color
* closes #41 
* @jgodi 
…nd color

fix(headers): Fixes SCSS, closes #41

---

src/elements/loading/Loading.js
src/elements/loading/README.md
src/elements/loading/_NovoSpinner.scss

* changed url path for svg filter
* @jgodi

Hotfix for loading animation svg filter

---

demo/pages/toast/ToastDemo.js
demo/pages/toast/templates/ToastServiceDemo.html
src/elements/toast/_Toast.scss

* fixes z index bug in toast
* adds all toast types to demo
* closes #51 
* @jgodi

bug(toast): Fixes z-index on inline toast

---

demo/index.scss
demo/pages/app/App.js
demo/pages/dragula/DragulaDemo.js
demo/pages/dragula/DragulaDemo.scss
demo/pages/dragula/templates/DragulaDemo.html
demo/pages/dragula/templates/DragulaModelDemo.html
src/elements/dragula.js
src/elements/dragula/Dragula.js
src/elements/dragula/DragulaService.js
src/elements/dragula/README.md
src/elements/dragula/_Dragula.scss
src/novo-elements.js
src/novo-elements.scss

* Adds dragula element
* Adds dragula service
* Adds documentation
* Closes #5 
* @jgodi

feat(dragula): Adds Dragula element and docs, closes #5

---

demo/pages/picker/PickerDemo.js
demo/pages/picker/templates/CustomPickerResultsDemo.html
src/elements/picker/_Picker.scss

Added a custom template picker demo

chore(picker): Adding a custom picker template demo, closes #58

---

demo/pages/iconography/Iconography.html

chore(icons): Adding link to the icon font, closes #60

---

demo/pages/table/TableDemo.js
demo/pages/table/templates/SelectAllTableDemo.html
src/elements/table/Table.js

Adding table selection.
Closes #50

feature(table): Adding table selection via checkboxes, closes #50

---

src/elements/form/extras/date-input/DateInput.js
src/elements/form/extras/date-time-input/DateTimeInput.js
src/elements/form/extras/time-input/TimeInput.js

Added click to the calendar icon so the date picker opens when the icon is clicked

BH-40768: add click to calendar icon to open date picker

---

demo/demo.scss
demo/pages/app/App.js
demo/pages/radio/RadioDemo.js
demo/pages/radio/_RadioDemo.scss
demo/pages/radio/templates/BasicRadio.html
demo/pages/radio/templates/VerticalRadio.html
src/elements/radio.js
src/elements/radio/README.md
src/elements/radio/Radio.js
src/elements/radio/Radio.spec.js
src/elements/radio/_Radio.scss
src/novo-elements.js
src/novo-elements.scss

feat(radio): Adding a radio group element

---

demo/pages/app/App.js
demo/pages/tiles/TilesDemo.js
demo/pages/tiles/templates/TilesDemo.html
src/elements/tiles.js
src/elements/tiles/README.md
src/elements/tiles/Tiles.js
src/elements/tiles/Tiles.spec.js
src/elements/tiles/_Tiles.scss
src/novo-elements.js
src/novo-elements.scss

Adding a new component called tiles that behaves like a radio button component.
Added a new component called tiles.
* @jgodi

feat(tiles): Adding a tile component

---

src/elements/button/Button.js

Updates Button to add correct disabled attribute
* @jgodi

Hotfixed button disabled attribute

---

src/elements/form/_Form.scss
src/elements/select/_Select.scss

Minor form related styling updates
- chip pickers required state matches others
- select dropdown top border is more visible
* @jgodi

Minor styling updates

---

src/elements/form/_Form.scss

Updates to form label styles
Updates to font weight and size based on UX input
* @jgodi

style(form): updates to form label style

---

src/elements/table/Table.js

Toggling the visibility of the clear button when filtering in the table

[Table] - Clear button toggling

---

src/elements/table/_Table.scss

* Removes `overflow: hidden;`
* Adds `display: block;`
* @jgodi

fix(tables): Updates novo-tables to fix overflow clipping issues

---

src/assets/styles/global/_variables.scss

Updated colors for taks & note entities
* @jgodi

style: Updated task & note colors

---

demo/pages/table/TableDemo.js
src/elements/table/README.md
src/elements/table/Table.js
src/elements/table/Table.spec.js

allows date filters to be toggled between multiple and single selection. with multiple=true property on meta data.
Table.js and spec file.
Changed includes to indexOf check due to PhantomJS not supporting includes, no shim in polyfills

feat(Table): changed Date filtering to allow multiple or single selection

---

src/services/novo-label-service.js

UX asked for 'Filters' to be changed to 'Filter'
Changed 'Filters' to 'Filter'
* @jgodi @amrutha-rajiv

refactor(Table): Language tweak from UX

---

demo/pages/dropdown/DropdownDemo.js
demo/pages/dropdown/templates/DropdownDemo.html
demo/pages/table/templates/SelectAllTableDemo.html
src/elements/dropdown/Dropdown.js
src/elements/dropdown/Dropdown.spec.js
src/elements/dropdown/README.md
src/elements/dropdown/_Dropdown.scss
src/elements/table/README.md

Making it so dropdown items have a custom action and can be disabled.

feat(dropdown): Adding ability to disable an item inside a dropdown

---

.eslintrc
config/webpack.common.js
config/webpack.dev.js
config/webpack.prod.js
demo/demo.scss
demo/index.html
demo/pages/app/App.js
demo/pages/editor/EditorDemo.js
demo/pages/editor/_EditorDemo.scss
demo/pages/editor/templates/BasicEditorDemo.html
src/elements/ckeditor.js
src/elements/ckeditor/CKEditor.js
src/elements/ckeditor/CKEditor.spec.js
src/elements/ckeditor/README.md
src/elements/ckeditor/_CKEditor.scss
src/novo-elements.js
src/novo-elements.scss

Adding in a basic HTML editor. Included is the first pass in theming this to Novo.

HTML Editor (CKEditor)

---

demo/pages/calendar/CalendarDemo.js
demo/pages/calendar/templates/RangeDemo.html
demo/pages/table/TableDemo.js
src/elements/date-picker/DatePicker.js
src/elements/date-picker/DatePicker.spec.js
src/elements/date-picker/README.md
src/elements/date-picker/_DatePicker.scss
src/elements/dropdown/Dropdown.js
src/elements/dropdown/README.md
src/elements/form/extras/date-input/DateInput.js
src/elements/table/README.md
src/elements/table/Table.js
src/elements/table/Table.spec.js
src/elements/table/_Table.scss

Adding ability to select a range of dates either fro the calendar picker or the table filters
modified:   demo/pages/calendar/CalendarDemo.js
new file:     demo/pages/calendar/templates/RangeDemo.html
modified:   demo/pages/table/TableDemo.js
modified:   src/elements/date-picker/DatePicker.js
modified:   src/elements/date-picker/DatePicker.spec.js
modified:   src/elements/date-picker/_DatePicker.scss
modified:   src/elements/date-picker/README.md
modified:   src/elements/dropdown/Dropdown.js
modified:   src/elements/dropdown/README.md
modified:   src/elements/table/Table.js
modified:   src/elements/table/Table.spec.js
modified:   src/elements/table/_Table.scss
modified:   src/elements/table/README.md

feat(calendar): Adding ability to select a range of dates

---

src/elements/form/FormUtils.js

readOnly fields will be hidden
* @jgodi @bvkimball

bug(form): hiding readOnly fields

---

demo/pages/elements/form/templates/DynamicForm.html
demo/pages/elements/form/templates/VerticalDynamicForm.html
src/elements/form/Control.js
src/elements/form/DynamicForm.js
src/elements/form/controls/BaseControl.js

fix(forms): Fixing initial values for the updated values and validation

---

demo/pages/elements/chips/_ChipsDemo.scss
demo/pages/elements/chips/templates/AsyncChipsDemo.html
demo/pages/elements/chips/templates/BasicChipsDemo.html
demo/pages/elements/chips/templates/FormattedChipsDemo.html
demo/pages/elements/picker/_PickerDemo.scss
demo/pages/elements/picker/templates/AsyncPickerDemo.html
demo/pages/elements/picker/templates/BasicPickerDemo.html
demo/pages/elements/picker/templates/CustomPickerResultsDemo.html
demo/pages/elements/picker/templates/FormattedPickerDemo.html
demo/pages/elements/table/TableDemo.js
package.json
src/elements/button/_Button.scss
src/elements/chips/Chips.js
src/elements/chips/_Chips.scss
src/elements/form/Control.html
src/elements/form/Control.js
src/elements/form/_Form.scss
src/elements/picker/Picker.js
src/elements/picker/_Picker.scss

* Closes #112 
* Closes #158 
* Closes #121 
* Closes #120
* Closes #171 
* Cloes #170

[WIP] Closing out some issues

---

src/elements/date-picker/DatePicker.js
src/elements/table/Table.js
src/elements/table/_Table.scss

Fixes for issues
[Date Picker] - Custom date range #169
[Date Picker] Date filter dropdown closes out #162
Also fixes issue where range end date does not respect time.
src/elements/date-picker/DatePicker.js
src/elements/table/Table.js
src/elements/table/_Table.scss
* @bvkimball @jgodi @krsween 
…er sizing

fix(DatePicker): Fix for Date filter dropdown closes out and DatePicker sizing

---

demo/demo.scss
src/elements/table/_Table.scss
src/elements/table/extras/pagination/Pagination.js
src/elements/table/extras/pagination/_Pagination.scss

* Issue #180  and issue #190  were both solved by fixing pagination styles. This branch solves both issues.
* Removes `[hidden]` property on pagination next / prev buttons
* Replaces `[hidden]` with class `.disabled`
* Adds `.disabled` styles
* Adds styles for `dark` attribute on `novo-table`
* @jgodi

fix(pagination): Fixes table headers + pagination, closes #180 + #190

---

src/elements/tabs/_Tabs.scss

* Closes #126 
* Removed border styles, flipped order of indicator on vertical tabs
* @jgodi

fix(tabs): Updates vertical tab styles, closes #126

---

demo/novo-elements-demo.module.js
demo/pages/elements/modal/ModalDemo.js
demo/pages/elements/modal/templates/ModalAddDemo.html
demo/pages/elements/modal/templates/ModalEditDemo.html
demo/pages/elements/table/TableDemo.js
src/elements/form/FormValidators.spec.js
src/elements/modal/Modal.js
src/elements/modal/Modal.module.js
src/elements/modal/ModalService.js
src/elements/picker/Picker.js
src/elements/picker/Picker.module.js
src/elements/quick-note/QuickNote.js
src/elements/quick-note/QuickNote.module.js
src/elements/table/extras/TableExtras.module.js
src/elements/table/extras/row-details/RowDetails.js
src/elements/table/extras/table-cell/TableCell.js
src/elements/tabs/Tabs.js
src/elements/toast/Toast.module.js
src/elements/toast/ToastService.js
src/novo-elements.js
src/novo-elements.module.js
src/testing/test-providers.js
src/utils/component-utils/ComponentUtils.js

ComponentUtils

---

demo/pages/elements/form/FormDemo.js
src/elements/chips/Chips.js
src/elements/form/Control.html
src/elements/form/Control.js
src/elements/form/DynamicForm.js
src/elements/form/Form.js
src/elements/picker/Picker.js

Adds vertical label animations, closes #187 
* Updated various form controls
* Added ngAnimate2 animations to controls
* @jgodi

feat(form): Animations

---

src/elements/form/Control.html
src/elements/form/Control.js

Label sizes were wrong, chips / pickers weren't closing appropriately.
* Updated ng animations for `scale`
* Replaced `toggleState()` with `checkState()` where necessary
* @jgodi

fix(forms): Small tweaks to vertical forms

---

demo/pages/elements/editor/EditorDemo.js
demo/pages/elements/editor/templates/BasicEditorDemo.html
src/elements/ckeditor/CKEditor.js
src/elements/form/Control.html
src/elements/picker/extras/entity-picker-results/EntityPickerResults.js
src/elements/picker/extras/entity-picker-results/EntityPickerResults.spec.js

feat(CKEDITOR) - Added a function and demo for using CKEDITOR's insertText functionality.
* @user

feat(CKEDITOR)

---

src/elements/form/Control.html
src/elements/form/Control.js

issue #212 
emitting change event on input
* @jgodi

feat(form): TextBoxControl emits change events on input

---

src/elements/form/Control.html

feat(Form) - change events on textarea input

---

demo/pages/elements/form/FormDemo.js
demo/pages/elements/form/MockMeta.js
src/elements/form/Control.js
src/elements/form/DynamicForm.html
src/elements/form/FormUtils.js
src/elements/form/_Form.scss
src/elements/form/controls/BaseControl.js
src/elements/form/controls/BaseControl.spec.js

Add disabled attribute and styling for form fields.
Add disabled attribute and styling for form fields.
* @user

feat(forms) Add disabled element and styling to form fields

---

src/elements/chips/Chips.js

fix for clearAll
clearAll was using the wrong items object
* @jgodi

bug(chips) - fix for clearAll

---

src/elements/picker/extras/entity-picker-results/EntityPickerResults.js

Placement results should display with all pertinent information.
Added the ability to see all relevant placement fields on the placement picker.
* @jgodi

refactor(form): Add fields to placement results

---

src/elements/form/extras/address/_Address.scss

* increased padding in address form field block
* @jgodi

fix(form): Updates address block styles

---

src/elements/chips/Chips.js
src/elements/form/extras/address/_Address.scss

Fix saving of Add Note with a placement
* @user

Fix saving of Add Note with a placement

---

src/assets/styles/global/_variables.scss

Added a css variable for commonly used hex code
Added a css variable for #CCCDCC
* @jgodi

style(css): add css variable for #CCCDCC

---

src/elements/category-dropdown/CategoryDropdown.scss

Small styling updates for Category Dropdown
Updated some styling for Category Dropdown
* @user

feat(category-dropdown) Styling update

---

demo/pages/elements/card/CardDemo.js
demo/pages/elements/card/templates/FullConfigCardDemo.html
src/elements/card/Card.js
src/elements/card/Card.module.js
src/elements/card/README.md
src/elements/card/_Card.scss
src/services/novo-label-service.js

- ability to add custom action buttons to the header
- tooltips for refresh & close
* @jgodi

feat(card) - custom-actions in header & tooltips for refresh/close

---

demo/pages/elements/list/ListDemo.js
demo/pages/elements/list/templates/ListDemo.html
demo/pages/elements/list/templates/ThemedListDemo.html
src/assets/styles/content/_typography.scss
src/elements/card/Card.js
src/elements/list/List.js
src/elements/list/List.module.js
src/elements/list/_List.scss
src/elements/picker/extras/entity-picker-results/EntityPickerResults.js
src/services/novo-label-service.js

Updates to novo-list-item
- `item-header` & `item-date`
* @asibilia @jgodi

feat(list) - updated list to use header, date, updates to styles

---

src/elements/chips/_Chips.scss
src/elements/form/_Form.scss
src/elements/picker/_Picker.scss
src/elements/table/_Table.scss

* makes x and search icons smaller
* @jgodi

fix(pickers): Updates picker icons to have correct sizing

---

src/elements/form/FormUtils.js
src/elements/form/controls/BaseControl.js
src/elements/form/controls/BaseControl.spec.js

Adding async validator support for Controls
modified:   src/elements/form/FormUtils.js
modified:   src/elements/form/controls/BaseControl.js
modified:   src/elements/form/controls/BaseControl.spec.js
* @jgodi @bvkimball @krsween

feat(Forms): Adding async validator support for Controls

---

src/elements/list/List.js

fix for avatar flag update to list
* @jgodi

fix(list) - class attr to ngClass

---

src/elements/modal/Modal.js
src/services/novo-label-service.js

Novo Notification Improvements
Add getProperty method to label service to have custom properties
Add the ability not to have an icon on a novo-notification
* @user

Novo Notification Improvements

---

src/elements/form/DynamicForm.ts

Added disabled class to dynamic form fields
* @jgodi

fix(form fields): Add disabled class to dynamic form fields

---

src/elements/date-picker/DatePicker.scss
src/elements/date-picker/DatePicker.ts
src/elements/date-time-picker/DateTimePicker.ts

* Adds markup to allow clicking between start and end date
* Adds typing for `date-picker` and `date-time-picker`
* New date range picker now functions similar to `date-time-picker`
* Adds new styles
* @jgodi

feat(calendar): Fixes date-range pickers to allow tabbing

---

src/elements/button/Button.scss
src/elements/date-time-picker/DateTimePicker.ts
src/elements/table/Table.scss
src/elements/table/Table.ts

* Updates button styles to not use `focus` but use `active` for click coloring (was causing filter issue)
* Adds background color to filtered column headers
* Flips sort arrows
* @jgodi

fix(tables): Fix sort order, fix button focus styles, add sorted column header color

---

src/styles/global/variables.scss

Updating color for submission and adding sendout
varibles.scss

feat(colors): adding sendout entity color

---

src/elements/form/Form.scss

fix(form) padding

---

src/elements/form/DynamicForm.ts

not showing fieldset unless controls exist
* @jgodi

fix(form) - fieldset header spacing

---

src/elements/form/FormUtils.ts

Explicit check to make address fields show
FormUtils
* @jgodi

fix: make address fields show

---

src/elements/form/FormUtils.ts
src/elements/form/FormValidators.ts
src/elements/form/extras/address/Address.ts

- not defaulting country value
- formutils ensures sortOrder is the max int number to surface fields without sortOrder
* @jgodi

fix(address) - address validator & address defaults

---

src/elements/form/extras/address/Address.ts

fix(address) - populate states list

---

src/elements/picker/Picker.ts

Picker clearing had unnecessary logic.
Refactored picker clearing around new Forms logic.
* @jgodi

refactor(Picker): added new picker clearing logic for forms

---

src/elements/chips/Chips.ts
src/elements/picker/Picker.scss
src/elements/picker/Picker.ts
src/elements/picker/extras/entity-picker-results/EntityPickerResults.ts
src/elements/picker/extras/picker-results/PickerResults.ts

- any selected option on a chips is disabled
- chips passes through selected items to PickerResult element
* @jgodi

(chips) - selected option is disabled

---

demo/pages/elements/form/MockMeta.ts
src/elements/form/Control.ts

Radio value fix (should honor default value and correctly set value)
Radio.tx
* @jgodi

bug (radio): Radio value fix (should honor default value and correctly set value)

---

src/elements/chips/Chips.scss

fix(chips): reduce max-width to prevent elipsis from pushing to the edge

---

src/elements/chips/Chips.scss
src/styles/global/variables.scss

fix(css): add distributionList as an entity color

---

src/elements/picker/Picker.scss

Pickers.scss
* @jgodi @bvkimball @krsween @asibilia

fix(Picker): Updating Entity Results styling to be more reponsive

---

src/elements/form/Form.scss

Form.scss
* @jgodi @bvkimball @krsween @asibilia

fix(Picker): Updating Entity Results styling to be more responsive

---

src/elements/picker/extras/picker-results/PickerResults.ts

valueFormat in pickers
* @user

feat(picker) - allow for valueFormat in pickers

---

src/elements/form/FormValidators.ts

Removed validation check for state field
* @user

BH-46505 - making state no longer a required field

---

src/elements/popover/PopOver.scss

Styling changes to PopOver element
* reduced padding on .popover-content, .popover, .popover-title
* @jgodi 
* [x ] Changes are limited to a single goal (no scope creep)
* [x ] Code can be automatically merged (no conflicts)
* [x ] Code follows the standards laid out in the [contributing guide](https://github.com/bullhorn/novo-elements/blob/master/CONTRIBUTING.md)
* [x ] New functions are documented (with a description, list of inputs, and expected output)
* [x ] Visually tested in supported browsers and devices

feat(PopOver) UX styling changes

---

src/elements/chips/Chips.ts

Chips.ts
* @jgodi  @bvkimball @krsween

feat(Chips): Adding check to make sure options is an array before using getLabelFromOptions() in Chips labels

---

demo/pages/elements/form/FormDemo.ts
demo/pages/elements/form/MockMeta.ts
demo/pages/elements/form/templates/FieldInteraction.html
demo/pages/elements/form/templates/UpdatingFormDemo.html
src/elements/form/Control.ts
src/elements/form/DynamicForm.ts
src/elements/form/Form.scss
src/elements/form/FormUtils.ts
src/elements/form/controls/BaseControl.ts

[WIP] Form Updates

---

src/elements/table/Table.ts
src/services/data-provider/PagedArrayCollection.ts
src/utils/Helpers.ts

Past 1 Day should be yesterday midnight to today midnight, not past 24 hours

fix(Table): Date Ranges should clear times accordingly.

---

demo/pages/elements/form/FormDemo.ts
src/elements/form/Control.ts
src/elements/form/FormUtils.ts

The hidden property wasn't being read correctly.
Updated hidden property.
* @user

refactor(Form): added new logic around hiding fields and updated demo

---

demo/pages/elements/form/FormDemo.ts
src/elements/form/FormUtils.ts

fix for issue https://github.com/bullhorn/novo-elements/issues/354

fix(Form): Form interactions required field does not validate correctly

---

src/elements/form/Form.scss

fix for issue https://github.com/bullhorn/novo-elements/issues/354

bug(feat): fix for Update disabled state #343

---

src/elements/form/FormUtils.ts

fix(form) - sectionHeader sort order conflicts are resolved

---

src/elements/form/FormUtils.ts

bug(Form): setValue does not mark form as dirty

---

src/elements/dropdown/Dropdown.scss
src/elements/header/Header.scss

fix for #316 Reduce margin on tops of headers
* @user

bug(Header): fix for #316 Reduce margin on tops of headers

---

demo/index.html
src/elements/ckeditor/CKEditor.scss

Updated CKEDITOR to version 4.6.2 and fixed styling
* @jgodi
* @more

feat(Editor): Updated to version 4.6.2 and fixed styling

---

src/elements/form/Control.ts

Reworking field interactions to have events and invokeOnInit
* @jgodi
* @more

feat(FieldInteractions): Reworking field interactions to have events and invokeOnInit

---

demo/pages/elements/picker/PickerDemo.ts
src/elements/picker/Picker.scss
src/elements/picker/extras/entity-picker-results/EntityPickerResults.ts
src/elements/picker/extras/picker-results/PickerResults.ts
src/elements/select/Select.ts

- added onScrollDown callback in BasePickerResults - triggered while scrolling
* @jgodi
* @more

Infinite scroll on pickers

---

demo/pages/elements/form/FormDemo.ts
src/elements/form/controls/BaseControl.ts

Updating the TypeScript definitions and form demo to work with new field interactions
* @jgodi
* @more

bug(Control): Updating the TypeScript definitions and form demo to work with new field interactions

---

src/elements/picker/Picker.scss

fix(picker) centering loading dots

---

src/elements/tip-well/TipWell.ts

Hide tip fires event.
Added event fired when the tip is hidden by clicking the button.
* @jgodi
* @more

feat(tip-well) emit event on hide tip

---

src/elements/table/Table.ts

Table filtering should be disabled for all columns if set in config
config = { filtering: false }
* @jgodi
* @more

feat(Table): Table filtering should be disabled for all columns if set in config

---

package.json
src/elements/quick-note/QuickNote.scss
src/elements/quick-note/QuickNote.ts

Quick Note Dropdown

---

demo/assets/styles/main.scss
src/elements/date-time-picker/_DateTimePicker.scss
src/elements/time-picker/TimePicker.scss
src/styles/global/variables.scss

Reduced base font size from `14px` to `13px`
* Updated base font size
* Updated time picker sizes to match new font size
* @jgodi
* @more

feat(fonts): Updated font size from 14px to 13px

---

src/elements/card/Card.scss

Changed overflow styling on cards
Moved overflow to the main list and froze the header
* @jgodi
* @more

BH-45576 Card overflow cleanup

---

demo/pages/elements/form/FormDemo.ts
demo/pages/elements/picker/templates/BasicPickerDemo.html
demo/pages/elements/table/TableDemo.scss
demo/pages/elements/table/TableDemo.ts
demo/pages/elements/table/templates/EditableTableDemo.html
demo/pages/elements/table/templates/TableDemo.html
demo/pages/elements/table/templates/TotalFooterTableDemo.html
index.ts
src/elements/form/Control.ts
src/elements/form/Form.scss
src/elements/form/Form.ts
src/elements/form/FormControls.ts
src/elements/form/FormUtils.ts
src/elements/form/controls/BaseControl.ts
src/elements/form/controls/picker/PickerControl.ts
src/elements/form/controls/read-only/ReadOnlyControl.ts
src/elements/picker/Picker.module.ts
src/elements/picker/Picker.scss
src/elements/picker/Picker.ts
src/elements/table/Table.module.ts
src/elements/table/Table.scss
src/elements/table/Table.ts
src/elements/table/extras/table-cell/TableCell.ts
src/utils/Helpers.ts

* Making tables have an edit mode
* Setting up a config to quickly have a total footer to sum up columns
* Tables
* @bvkimball

WIP: Editable Table / Total Footer

---

novo-elements.module.ts

Required FormUtils dependency was missing.
Added FormUtils to providers.
* @jgodi

chore(Providers): added FormUtils to providers.

---

src/elements/picker/extras/picker-results/PickerResults.ts

fix(picker) - fixed paging issues with scrolling in picker results

---

src/elements/table/Table.ts

fix for issue #393
* @jgodi
* @more

fix(Table): #393 Table filtering should be disabled for all columns if set in config

---

src/elements/picker/extras/picker-results/PickerResults.ts

fix(picker) paging correctly

---

src/elements/ckeditor/CKEditor.ts

Add paste and loaded outputs to CKEditor.
Add paste and loaded outputs to CKEditor.
* @jgodi

feat(ckeditor): Add paste and loaded events

---

src/elements/ckeditor/CKEditor.ts
src/elements/toast/Toast.ts

Add ng-content to toast, fix paste event in editor
Add ng-content to toast, fix paste event in editor
* @jgodi

feat:Toast & fix:CKEditor - Add ng-content to toast, fix paste event in editor

---

demo/pages/elements/modal/templates/ModalCustomDemo.html
demo/pages/elements/modal/templates/ModalErrorDemo.html
demo/pages/elements/modal/templates/ModalSuccessDemo.html
demo/pages/elements/modal/templates/ModalWarningDemo.html
src/elements/modal/Modal.scss
src/elements/modal/Modal.ts

Updates modal styles
* Updated CSS
* Changed `h4` to `h2`
* @jgodi

feat(modals): Updated modal styles and structure

---

src/styles/global/variables.scss

Add Credential to entities
* @jgodi
* @more

Add Credential to entities

---

src/elements/toast/Toast.scss
src/elements/toast/Toast.ts

In toast, wrap ng-content section in dialogue div, and add styling for toast dialogue.
Toast.ts
Toast.scss
* @jgodi
* @more

feat(toast): add dialogue styling to toast

---

src/elements/form/FormUtils.ts

Add the ability to pass in overrides when creating field sets.
* @jgodi
* @more

feat(form): Add ability to set overrides when creating field sets

---

demo/pages/elements/form/FormDemo.ts
demo/pages/elements/form/templates/PickerControls.html
index.ts
src/elements/chips/Chips.scss
src/elements/chips/Chips.ts
src/elements/form/FormUtils.ts
src/elements/picker/Picker.module.ts
src/elements/picker/Picker.scss
src/elements/picker/extras/entity-picker-results/EntityPickerResults.ts

Added a preview of the entity chip, which is exactly what was picked from the entity picker results.
* Pulled entity-picker-result out of entity-picker-results
* Added mouse over logic for the chip
* Added selection logic in the chips
* @jgodi
* @more

feat(chips): Added a preview on hover of the entity chip

---

demo/main.module.ts
demo/pages/elements/form/FormDemo.ts
demo/pages/elements/form/MockMeta.ts
src/elements/form/Control.ts
src/elements/form/DynamicForm.ts
src/elements/form/Form.module.ts
src/elements/form/Form.scss
src/elements/form/FormUtils.ts
src/elements/form/controls/BaseControl.ts

Allow the ability to use custom components in dynamic forms. 
* @jgodi
* @more

feat(Form): Add ability to have custom components used with the dynamic form

---

src/elements/form/Control.ts

bug(Control): Errors is an unknown property on NovoCustomControlContainerElement

---

src/elements/picker/extras/entity-picker-results/EntityPickerResults.ts

Fixed the bug
* @jgodi
* @more

fix(chips): Fixed the preview on hover of the entity chip when data is not present

---

src/elements/table/Table.ts

Allow css on footer for even and odd

---

src/elements/tiles/Tiles.scss
src/elements/tiles/Tiles.ts

updated novo tiles to have a disable option

---

src/elements/form/Control.ts
src/elements/form/extras/checkbox/CheckList.ts

Added events that get emitted when making changes to date-time, checklist, and select Controls
Added modelChange to Control.ts for date-time, checklist, and select
Implemented onSelect event emitter for novo-checklist
* @jgodi
* @more

BH-45391 added onChange events to date-time, checklist, and select

---

src/elements/form/Control.ts

Added for the Date Picker just like the Date Time Picker
* @jgodi
* @more

 fix(control): Moving Model change events to be fired after model is updated

---

src/elements/table/Table.ts

also Toasts should be removed on cancel
* @jgodi
* @more

feat(Table): Column headers should show in edit mode even if no data

---

src/elements/form/Form.scss
src/elements/table/Table.scss

feat(Table): Adding margin for table header buttons and increasing min-width for entity-picker

---

index.ts
src/elements/form/extras/file/FileInput.ts
src/elements/form/extras/file/extras/file/File.ts
src/pipes/Pipes.module.ts
src/pipes/decode-uri/DecodeURI.spec.ts
src/pipes/decode-uri/DecodeURI.ts
src/pipes/decode-uri/README.md
src/pipes/plural/README.md

Added a pipe for displaying strings as a URL decoded string and added URL encoding to NovoFile class.
* @jgodi

feature(pipe): Added new pipe for displaying encoded string

---

src/elements/table/Table.scss

Following a request from Ethan.
* @jgodi
* @asibilia

feat(Table): remove forced uppercase for empty state text

---

src/utils/form-utils/FormUtils.ts

Don't set a default value for keepClean
* @jgodi

fix(FormUtils): Don't set a default value for keepClean

---

src/elements/form/NovoFormControl.ts

Overrides for setValue calls are now outside of config
* @jgodi

fix(FormUtils): Overrides for setValue calls are now outside of config

---

src/elements/form/extras/checkbox/CheckList.ts

Set up initial values for checklist based on options array.
* @jgodi
* @more

feat(checklist): set initial model up based on options

---

src/elements/header/Header.scss
src/elements/tabs/Tabs.scss

Increasing font size and weight in header and tabs to improve contrast and legibility.
Header & Tabs styles
* @jgodi
* @more

BH-50651: Style changes to header and tabs

---

demo/pages/elements/tabs/templates/ButtonTabDemo.html
demo/pages/elements/tabs/templates/ColorDemo.html
demo/pages/elements/tabs/templates/RouterDemo.html
demo/pages/elements/tabs/templates/VerticalDemo.html
demo/pages/elements/tabs/templates/WhiteDemo.html
src/elements/tabs/Tabs.scss
src/elements/tabs/Tabs.ts

Tabs can be disabled
This is how it looks now: http://recordit.co/wY9apbVE1n
New input `disabled`
* @jgodi
* @more

issue #466 feat(tabs) - disabled input

---

src/elements/form/Form.module.ts
src/elements/form/controls/BaseControl.ts
src/elements/form/extras/FormExtras.module.ts
src/elements/form/extras/file/FileInput.scss
src/elements/form/extras/file/FileInput.spec.ts
src/elements/form/extras/file/FileInput.ts

made file chips draggable. Draggability can be configured through layout options.
FileInput.ts
* @jgodi
* @more

feat(fileInput): make file chips draggable

---

src/elements/form/extras/file/FileInput.scss
src/elements/form/extras/file/FileInput.ts

Fix default layout options to make draggable false
* @jgodi
* @more

fix(fileInput): draggable should default to false

---

src/elements/form/Control.ts
src/elements/form/controls/BaseControl.ts
src/elements/form/extras/checkbox/Checkbox.scss
src/elements/form/extras/checkbox/Checkbox.ts

Add options to checkbox's styling - can either be circle or box
Checkbox
* @jgodi
* @more

feat(checkbox): make icon optional - style can be box or circle

---

src/elements/table/Table.ts

Added Expand all details feature
When your table is using rowDetails, the table header will have a expand/collapse all icon.

feat(Table): Added Expand all details feature

---

src/elements/picker/Picker.scss
src/elements/picker/extras/checklist-picker-results/ChecklistPickerResults.ts
src/elements/picker/extras/entity-picker-results/EntityPickerResults.ts
src/elements/picker/extras/picker-results/PickerResults.ts

fix(pickers): Fixing empty results not displaying

---

src/elements/picker/Picker.ts

checking clearValueOnSelect flag to display icons

---

src/elements/form/Control.ts

This fixes an issue with the novo forms where clicking into a text input causes the click to bubble into the date-picker
* @jgodi
* @more

(fix) - date/time pickers will not be added to the dom until needed

---

demo/main.module.ts
demo/pages/elements/form/FormDemo.ts
demo/pages/elements/quick-note/QuickNoteDemo.scss
demo/pages/elements/quick-note/QuickNoteDemo.ts
demo/pages/elements/quick-note/templates/BasicQuickNote.html
demo/pages/elements/quick-note/templates/CustomQuickNoteResults.html
src/elements/picker/extras/base-picker-results/BasePickerResults.ts
src/elements/quick-note/extras/quick-note-results/QuickNoteResults.spec.ts
src/elements/quick-note/extras/quick-note-results/QuickNoteResults.ts

* Got the demo working in preparation for changing the quick note editor to use CKEditor (https://github.com/bullhorn/novo-elements/pull/486)
* Fixed issue where the custom results template demo wouldn't work
* Fixed issue where results dropdown caused console errors
* Simple fixing of typos and better naming convention for demo
* @jgodi

Fixes and cleanup for QuickNote Demo

---

src/elements/quick-note/QuickNote.spec.ts
src/elements/quick-note/QuickNote.ts

Quicknote component now replaces all instances of &amp; with &
* @jgodi
* @more

BH-51800 Global replace of &

---

demo/pages/elements/radio/RadioDemo.ts
demo/pages/elements/radio/templates/IconRadio.html
src/elements/radio/Radio.scss
src/elements/radio/Radio.spec.ts
src/elements/radio/Radio.ts

feat(Radio): Adding ability to have icon only button radio groups

---

src/elements/quick-note/QuickNote.spec.ts
src/elements/quick-note/QuickNote.ts

BH-51802 call hideResults when we remove the search symbol

---

src/utils/app-bridge/AppBridge.ts

Adding in AppBridge functionality.  Can open either a fast-add or add page now, and can pass in a passthrough parameter to any open call.
Changed enum and interface around AppBridge open calls.
* @jgodi
* @more

AppBridge Functionality

---

demo/pages/elements/calendar/CalendarDemo.ts
demo/pages/elements/calendar/templates/CalendarDemo.html
src/elements/calendar/day/CalendarDayEvent.ts
src/elements/calendar/day/CalendarDayView.ts
src/elements/calendar/week/CalendarWeekEvent.ts
src/elements/calendar/week/CalendarWeekView.ts
src/utils/app-bridge/AppBridge.ts

Added in mechanism for onClick events for calendar events for week and day view.
Changed week/day views of calendar to properly perform onClick for events.  Fixed demo for click events on days.
* @jgodi
* @more

Added in onClick for events in week and day views in calendar

---

src/elements/form/Control.ts

if a control does not have a default value the event subscription is never added
* @jgodi
* @more

bug(Control): fix empty percentage field interactions

---

src/elements/picker/Picker.ts

This fix allows users to right click and paste values into pickers.
I added an observer on paste events for pickers so that pickers can handle right click pasted values.
* @jgodi
* @more

fix(picker): Fixing picker to accept right click paste values

---

demo/pages/elements/form/MockMeta.ts
novo-elements.providers.ts
package.json
src/elements/date-picker/DatePicker.ts
src/elements/form/Control.ts
src/elements/form/Form.module.ts
src/elements/form/Stepwise.ts
src/elements/table/Table.module.ts
src/elements/table/Table.spec.ts
src/services/date-format/DateFormat.spec.ts
src/services/date-format/DateFormat.ts
src/services/novo-label-service.ts

(Work In Progress) (form) - Allowing Date, Time & Date-Time inputs

---

demo/demo.scss
demo/pages/elements/index.ts

Fix file path casing for Linux

---

src/elements/quick-note/QuickNote.spec.ts

Improving the readability of the quick note component tests
Refactoring only
* @jgodi

Improved the readability of the tests

---

src/elements/tiles/Tiles.spec.ts
src/elements/tiles/Tiles.ts

changed tiles component to add ngOnChanges so that the options array can be changed after initialization
Tiles component
* @jgodi
* @more

feat(tiles) Add ability to change options array

---

src/elements/tiles/Tiles.spec.ts
src/elements/tiles/Tiles.ts

Adding a check to Tiles ngOnChanges to catch case when previousValue is undefined
Tiles.ts
* @jgodi
* @more

fix(Tiles): Fix check for undefined array 

---

demo/pages/elements/tooltip/TooltipDemo.ts
demo/pages/elements/tooltip/templates/TooltipSizesDemo.html
src/elements/button/Button.scss
src/elements/tooltip/Tooltip.ts

feat(tooltip) - ability to add tooltipSize

---

src/elements/form/NovoFormControl.spec.ts
src/elements/form/NovoFormControl.ts

Reverse enable/disable calls inside setReadOnly
* @jgodi
* @more

fix(form): fixes#526

---

demo/pages/elements/form/MockMeta.ts
src/elements/form/Control.ts
src/elements/radio/Radio.scss
src/elements/radio/Radio.ts

Default (nothing selected)
On Hover
Selected
* @jgodi
* @more

feat(Radio): adding support for buttons with icons as radio buttons.

---

src/utils/app-bridge/AppBridge.ts

(appbridge) - updates to request data

---

src/utils/countries/Countries.ts

Re-Generated the Country/States array based on the current production database values.

Updated the country/states data to match the current prod database

---

src/elements/form/extras/address/Address.spec.ts
src/elements/select/Select.module.ts
src/elements/select/Select.scss
src/elements/select/Select.spec.ts
src/elements/select/Select.ts
src/elements/table/Table.spec.ts
src/elements/table/extras/keep-filter-focus/KeepFilterFocus.spec.ts
src/elements/table/extras/pagination/Pagination.spec.ts

We are trying to make all overlays append to the body element to avoid an clipping, overflow, or scrolling issues.
http://g.recordit.co/n8rRdMWbaM.gif

feat(Select): Select now Appends to Body

---

package.json
src/elements/form/DynamicForm.ts
src/elements/form/Form.module.ts
src/elements/form/Form.scss
src/elements/form/FormInterfaces.ts
src/elements/form/extras/FormExtras.module.ts
src/utils/form-utils/FormUtils.ts

Magic aardvark iweek/scroll you

---

src/elements/form/Form.scss

BH-47266 adding a vertical scrollbar to autosized textarea on focus

---

demo/main.module.ts
demo/pages/utils/app-bridge/AppBridgeDemo.ts
index.ts
src/utils/app-bridge/AppBridge.ts

Now you can use you cookies and make direct http requests to Bullhorn when developing with AppBridge
```let bridge: AppBridge;
export function appBridgeFactory(http: Http): AppBridge {
if (!bridge) {
if ( environment.production ) {
bridge = new AppBridge('ComplexToDoCard');
} else {
bridge = new DevAppBridge('ComplexToDoCard', http);
}
bridge.register();
bridge.tracing = true;
}
return bridge;
}
```

feat(AppBridge): Added a Developer mode for AppBridge

---

src/elements/form/Form.scss

BH-47266 added important tag to add scrollbar on focus

---

demo/pages/elements/table/TableDemo.ts

(fix)TableDemo

---

src/elements/form/ControlGroup.scss
src/elements/form/ControlGroup.ts
src/elements/tiles/Tiles.ts

BBO-2152 work

---

demo/app/App.routes.ts
demo/main.module.ts
demo/pages/elements/index.ts
demo/pages/elements/value/ValueDemo.ts
demo/pages/elements/value/templates/AddressValueDemo.html
demo/pages/elements/value/templates/AssociatedValueDemo.html
demo/pages/elements/value/templates/CategoryValueDemo.html
demo/pages/elements/value/templates/CorporateUserValueDemo.html
demo/pages/elements/value/templates/DateTimeValueDemo.html
demo/pages/elements/value/templates/EmailValueDemo.html
demo/pages/elements/value/templates/ExternalLinkValueDemo.html
demo/pages/elements/value/templates/FormatterValueDemo.html
demo/pages/elements/value/templates/IconRightValueDemo.html
demo/pages/elements/value/templates/PhoneValueDemo.html
demo/pages/elements/value/templates/SimpleValueDemo.html
demo/pages/elements/value/templates/ValueDemo.html
index.ts
novo-elements.module.ts
novo-elements.scss
src/elements/value/Render.spec.ts
src/elements/value/Render.ts
src/elements/value/SimpleValueDemo.html
src/elements/value/Value.module.ts
src/elements/value/Value.spec.ts
src/elements/value/Value.ts
src/elements/value/ValueTodo
src/elements/value/Values.scss
src/services/novo-label-service.ts
src/utils/entity-utils/EntityUtils.ts

- New novo-value element 
- novo-value-phone and novo-value-email are the sub-elements
- Specs, demos and minor changes to novo-value are pending

WIP - value renderer

---

src/utils/form-utils/FormUtils.ts

fix(form) converting toString for integer values

---

index.ts
novo-elements.module.ts
novo-elements.providers.ts

feat(Places): exporting the GoogleServiceService

---

index.ts
novo-elements.module.ts
novo-elements.providers.ts

feat(Places): exporting the GoogleServiceService missing dependencies

---

src/utils/countries/Countries.ts

I just added some missing countries and states that should have been there.

Added missing countries and states

---

.travis.yml
snapshot-publish
src/platform/elements/button/Button.ts

chore(snapshot): Trying for branches

---

src/platform/elements/value/Render.ts

WIP: BH-54897 fixed placement name renderer to pull from correct fields

---

cypress/integration/radio.js
src/app/pages/components/components.component.html
src/app/pages/components/components.module.ts
src/app/pages/components/components.routes.ts
src/app/pages/components/radio/demos/basic/basic.html
src/app/pages/components/radio/demos/basic/basic.ts
src/app/pages/components/radio/demos/button/button.html
src/app/pages/components/radio/demos/button/button.ts
src/app/pages/components/radio/demos/icon/icon.html
src/app/pages/components/radio/demos/icon/icon.ts
src/app/pages/components/radio/demos/index.ts
src/app/pages/components/radio/demos/vertical/vertical.html
src/app/pages/components/radio/demos/vertical/vertical.ts
src/app/pages/components/radio/docs/usage.md
src/app/pages/components/radio/radio.component.html
src/app/pages/components/radio/radio.component.ts
src/platform/core/components/button/button.component.ts
src/platform/core/components/index.ts
src/platform/core/components/radio/index.ts
src/platform/core/components/radio/radio.component.scss
src/platform/core/components/radio/radio.component.spec.ts
src/platform/core/components/radio/radio.component.ts
src/platform/core/components/radio/radio.module.ts
src/platform/core/novo-elements.module.ts
src/platform/index.ts
src/platform/novo-elements.scss

port(radio): move, unit tests, add cypress specs, update demos closes #607

---

src/platform/utils/entity-utils/EntityUtils.ts

BH-54839 adding tearsheet to ENTITY_LONG_NAMES in EntityUtils

---

src/platform/elements/picker/extras/entity-picker-results/EntityPickerResults.ts

Added owner to EntityPickerResults for Candidate

Add owner to EntityPickerResults for Candidate

---

src/platform/elements/table/Table.ts

Change to allow table changed event to emit

---

src/platform/elements/form/Form.scss

style(form) fix styling for field-message

---

src/platform/index.ts

Export NovoCheckListElement for extending

chore(export): export NovoCheckListElement

---

src/platform/elements/picker/extras/base-picker-results/BasePickerResults.ts

Fixing pickers

---

package-lock.json
package.json
src/app/pages/elements/dragula/DragulaDemo.ts
src/app/pages/elements/dragula/templates/DragulaThresholdDemo.html
src/platform/elements/dragula/Dragula.ts
src/platform/elements/dragula/DragulaService.ts

Using custom build with support for drag thresholds
New demo showing threshold support
Now using @bullhorn/dragula

feat(dragula): Using custom build with support for drag thresholds

---

src/platform/utils/form-utils/FormUtils.ts

fix(address) - updating label checking

---

package.json
src/app/pages/elements/form/FormDemo.ts
src/app/pages/elements/form/templates/CalendarInputControls.html
src/platform/elements/date-picker/DatePicker.module.ts
src/platform/elements/date-picker/DatePickerInput.ts
src/platform/elements/form/Control.ts
src/platform/elements/form/NovoFormControl.ts
src/platform/elements/form/controls/BaseControl.ts
src/platform/utils/form-utils/FormUtils.ts

Reverts bullhorn/novo-elements#698

Revert "Add support into datepicker for looser date formats and different locale options"

---

src/platform/elements/card/Card.scss

Increased font-weight on card headers

style(card): Increase font-weight on card headers

---

src/app/pages/elements/form/FormDemo.ts
src/platform/elements/form/extras/address/Address.ts

fix(address) looking at countryID and not country

---

src/platform/elements/value/EntityList.ts
src/platform/elements/value/Render.ts
src/platform/elements/value/Values.scss

BH-56266 adding gray dot to non-linkable internal entities for mobile

---

src/platform/elements/value/Value.ts

checking if you can actually replace the value

fix(value) - data.replace will not work if data is not a string value

---

src/platform/elements/form/ControlTemplates.ts

undefined function error when interacting with the datePicker.

fix: blur/focus-console-error

---

src/platform/elements/form/Control.ts
src/platform/elements/form/ControlTemplates.ts
src/platform/elements/form/DynamicForm.ts
src/platform/elements/form/Form.spec.ts
src/platform/elements/form/Form.ts

Loading control templates within the scope of the form instead of the scope of the control

Form rendering fix

---

src/platform/elements/form/Control.ts

fix(control) fixing a typo

---

src/TODO
src/platform/elements/form/ControlTemplates.ts
src/platform/elements/form/Form.scss

added back the change that got lost due to moving code around

WIP fix(textarea) tooltips

---

src/platform/elements/picker/extras/base-picker-results/BasePickerResults.spec.ts
src/platform/elements/picker/extras/base-picker-results/BasePickerResults.ts
src/platform/elements/picker/extras/entity-picker-results/EntityPickerResults.spec.ts
src/platform/elements/picker/extras/entity-picker-results/EntityPickerResults.ts

Began trimming text to match against for highlighting.

Change to trim highlight text

---

projects/novo-elements/src/elements/data-table/cell-headers/data-table-header-cell.component.ts
projects/novo-elements/src/elements/data-table/data-table.component.scss

Update resize icon for data tables

---

src/app/pages/elements/value/ValueDemo.ts
src/platform/elements/value/Value.ts
src/platform/elements/value/Values.scss

Allow to add an icon which represent the person type of novo-value:

Added person icon to value

---

projects/novo-elements/src/elements/form/Control.ts
projects/novo-elements/src/elements/form/Form.scss
projects/novo-elements/src/elements/form/NovoFormControl.ts
projects/novo-elements/src/elements/form/controls/BaseControl.ts
projects/novo-elements/src/utils/form-utils/FormUtils.ts
src/app/pages/elements/form/FormDemo.ts

Warning Text 

---

src/platform/elements/form/Control.ts
src/platform/elements/form/Form.scss
src/platform/elements/form/NovoFormControl.ts
src/platform/elements/form/controls/BaseControl.ts
src/platform/utils/form-utils/FormUtils.ts

(feat) Warning Text

---

projects/novo-elements/src/styles/global/variables.scss
projects/novo-examples/src/design/colors/entity-colors/entity-colors-example.ts

Added colors to variables for invoice statement and billable charge

style(variables): Added invoice statement and billable item colors

---

projects/novo-elements/src/elements/data-table/data-table-expand.directive.ts
projects/novo-elements/src/elements/data-table/data-table.component.ts
projects/novo-elements/src/elements/data-table/state/data-table-state.service.ts

Adjustments to data table expansion logic

---

projects/novo-elements/src/elements/toast/ToastService.ts

toast service to accept an optional custom toast element

---

projects/novo-elements/src/elements/picker/Picker.spec.ts
projects/novo-elements/src/elements/picker/Picker.ts
projects/novo-examples/src/form-controls/form/picker-controls/picker-controls-example.html
projects/novo-examples/src/form-controls/form/picker-controls/picker-controls-example.ts

add flag to force using getLabels

---

projects/novo-elements/src/elements/form/FieldInteractionApi.ts

Adjusted field interactions api to allow config.format to be optional

feat(fieldInteractions): modified to make format optional

---

projects/novo-elements/src/utils/form-utils/FormUtils.ts

Add placement to the entity picker list

---

projects/novo-elements/src/elements/form/ControlGroup.ts

fix(controlGroup): Decrement currentIndex so it stays up to date

---

projects/novo-elements/src/utils/Helpers.spec.ts
projects/novo-elements/src/utils/Helpers.ts

bug(helpers): Fixed issue where isNumber was validating incorrectly

---

projects/novo-elements/src/elements/modal/Modal.scss

Center the icon in the circle. Tested on chrome, firefox, safari.

style(Modal): Center the icon in the circle

---

src/platform/elements/value/Value.ts

Making associated leads internal links

---

projects/novo-elements/src/elements/value/Value.ts

Making associated Leads type of INTERNAL_LINK

---

projects/novo-elements/src/elements/picker/Picker.ts
projects/novo-elements/src/elements/picker/extras/base-picker-results/BasePickerResults.spec.ts
projects/novo-elements/src/elements/picker/extras/base-picker-results/BasePickerResults.ts

[ n/a] New demos work in `Safari`, `Chrome` and `Firefox`

update selected list on popup

---

projects/novo-elements/src/elements/picker/extras/base-picker-results/BasePickerResults.spec.ts
projects/novo-elements/src/elements/picker/extras/base-picker-results/BasePickerResults.ts

check value for Object and value property

---

projects/novo-elements/src/elements/data-table/data-table.component.scss
projects/novo-elements/src/elements/data-table/data-table.component.ts
projects/novo-examples/src/components/data-table/data-table-rows/data-table-rows-example.css
projects/novo-examples/src/components/data-table/data-table-rows/data-table-rows-example.html

data table scrolling

---

src/app/pages/elements/value/ValueDemo.ts
src/platform/elements/value/Render.ts

If an inputType of 'SELECT' does not have an array of options, catch the error and pass a helpful error message.
If If an inputType of 'SELECT' is configured with and optionsType, don't throw the error & return the value
ex. customText5 is a Picker:People
- [ x] Any related demos were added and `npm start` and `npm run build` still works
- [x ] New demos work in `Safari`, `Chrome` and `Firefox`
- [ x] `npm run lint` passes
- [ x] `npm test` passes and code coverage is increased
- [x ] `npm run build` still works

Support/ Catching improper config

---

projects/novo-elements/src/elements/value/Render.ts

If an inputType of 'SELECT' does not have an array of options, catch the error and pass a helpful error message.
If If an inputType of 'SELECT' is configured with and optionsType, don't throw the error & return the value
ex. customText5 is a Picker:People
- [x ] Any related demos were added and `npm start` and `npm run build` still works
- [ x] New demos work in `Safari`, `Chrome` and `Firefox`
- [ x] `npm run lint` passes
- [x ] `npm test` passes and code coverage is increased
- [x ] `npm run build` still works

Catching improper config 

---

projects/novo-examples/src/design/colors/primary-colors/primary-colors-example.ts

fix(demo): Fix variable name for color on demo page

---

projects/novo-elements/src/elements/data-table/sort-filter/sort-filter.directive.spec.ts

lol whoops meant to commit straight to @MichaelDill's branch and instead pushed a new one because case sensitivity

add a unit test

---

projects/novo-elements/src/elements/form/ControlTemplates.ts

Update to allow passing of config into EditorControl object in order to update the underlying CKEditor options.

Allow passing of config object to Editor Control in order to update underlying CKEditor options

---

projects/novo-elements/src/elements/list/List.scss

Small css change to up opacity on picker items

changing opacity on picker lists

---

tsconfig.json

show how to use novo-examples and demo with novo-elements source files.

debug novo examples

---

projects/chomsky/src/utils/formats.ts

fix dayPeriod Issue for Time Picker

---

projects/novo-elements/src/elements/data-table/data-table.component.ts

add a dropdown with just a icon (no text)

BH-60879 add icon dropdown

---

projects/novo-elements/src/elements/data-table/data-table.source.ts

Reverts bullhorn/novo-elements#991
This code causes a regression for certain BBO lists

Revert "Fix issue where novo data tables weren't showing results if they start filtered"

---

projects/novo-elements/package.json
projects/novo-elements/src/elements/form/FieldInteractionApi.ts

Hotfix/rel 9468.1

---

projects/novo-elements/src/elements/stepper/step-header.component.ts
projects/novo-elements/src/elements/stepper/stepper.component.ts
projects/novo-elements/src/index.ts
projects/novo-examples/src/layouts/stepper/stepper-horizontal/stepper-horizontal-example.ts
projects/novo-examples/src/layouts/stepper/stepper-vertical/stepper-vertical-example.html
projects/novo-examples/src/layouts/stepper/stepper-vertical/stepper-vertical-example.ts
tsconfig.json

Fix novo-elements stepper example
https://github.com/bullhorn/novo-elements/issues/1020

Fix novo-elements stepper example

---

projects/novo-examples/src/form-controls/chips/basic-chips/basic-chips-example.ts

fix(examples) basic chips example

fix(examples): basic chips example

---

projects/novo-elements/src/elements/picker/extras/entity-picker-results/EntityPickerResults.spec.ts
projects/novo-elements/src/elements/picker/extras/entity-picker-results/EntityPickerResults.ts
projects/novo-elements/src/utils/form-utils/FormUtils.ts

BH-63816: Making corporation department an entity picker

---

projects/novo-elements/src/elements/picker/extras/grouped-multi-picker-results/GroupedMultiPickerResults.scss

adding ability to scroll thru list items for grouped picker

---

projects/novo-elements/src/elements/data-table/data-table.pipes.spec.ts
projects/novo-elements/src/elements/data-table/data-table.pipes.ts

fix(pipe) Correct issue with date and time pipes

---

projects/novo-elements/src/elements/form/FieldInteractionApi.ts
projects/novo-elements/src/elements/form/FieldInteractionApiTypes.ts
projects/novo-elements/src/elements/form/FormInterfaces.ts
projects/novo-examples/src/examples.routes.ts
projects/novo-examples/src/utils/field-interactions/fi-modify-added-picker/fi-modify-added-picker-example.css
projects/novo-examples/src/utils/field-interactions/fi-modify-added-picker/fi-modify-added-picker-example.html
projects/novo-examples/src/utils/field-interactions/fi-modify-added-picker/fi-modify-added-picker-example.ts
projects/novo-examples/src/utils/field-interactions/field-interactions.md

Adding ability to pass optional argument to modifyPickerConfig on FieldInteractionApi to mark any dynamically added controls to be rendered using EntityPickerResults

New optional picker templates

---

projects/novo-elements/src/elements/form/Form.scss

Fix for horizontal layout in Firefox

setting css for firefox for checkbox

---

projects/novo-elements/src/index.ts

feat(visibility): expose NovoDropdownElement

---

projects/novo-elements/src/elements/form/ControlGroup.ts

Added null check to prevent error in console

(controlgroup): added null check to checkCanRemove method

---

projects/novo-elements/src/elements/tiles/Tiles.scss
projects/novo-elements/src/elements/tiles/Tiles.ts

Updating tile component to use new CSS

new styles for tiles

---

projects/novo-elements/src/elements/calendar/day/CalendarDayView.ts
projects/novo-elements/src/elements/data-table/cell-headers/data-table-checkbox-header-cell.component.ts
projects/novo-elements/src/elements/data-table/cell-headers/data-table-expand-header-cell.component.ts
projects/novo-elements/src/elements/data-table/cell-headers/data-table-header-cell.component.ts
projects/novo-elements/src/elements/data-table/cells/data-table-expand-cell.component.ts
projects/novo-elements/src/elements/date-time-picker/DateTimePickerInput.ts
projects/novo-elements/src/elements/expansion/expansion-panel-header.ts
projects/novo-elements/src/elements/form/FieldInteractionApi.ts
projects/novo-elements/src/elements/form/extras/address/Address.ts
projects/novo-elements/src/elements/form/extras/checkbox/Checkbox.ts
projects/novo-elements/src/elements/multi-picker/MultiPicker.ts
projects/novo-elements/src/elements/places/places.component.ts
projects/novo-elements/src/elements/places/places.module.ts
projects/novo-elements/src/elements/popover/PopOverContent.ts
projects/novo-elements/src/elements/radio/Radio.ts
projects/novo-elements/src/elements/select/Select.ts
projects/novo-elements/src/elements/simple-table/cell.ts
projects/novo-elements/src/elements/value/EntityList.ts
projects/novo-elements/src/elements/value/Render.ts
projects/novo-elements/src/elements/value/Value.module.ts
projects/novo-elements/src/services/data-provider/PagedArrayCollection.ts
projects/novo-elements/src/services/options/OptionsService.ts
projects/novo-elements/src/utils/component-utils/ComponentUtils.ts

remove unused import

---

.travis.yml
projects/chomsky/src/utils/currency-overrides.ts
projects/novo-elements/src/elements/form/Control.spec.ts

add Russian currency RUB

---

projects/novo-elements/README.md

add doc for https://www.npmjs.com/package/novo-elements

chore(doc) add readme for npmjs

---

projects/novo-elements/src/elements/picker/extras/entity-picker-results/EntityPickerResults.ts

BH-68811 not converting startTime in jobshift pickers

---

projects/novo-elements/src/elements/date-picker/DatePickerInput.ts
projects/novo-elements/src/elements/date-time-picker/DateTimePickerInput.ts
projects/novo-elements/src/elements/form/Control.ts
projects/novo-elements/src/elements/form/ControlTemplates.ts

BH-69061 emitting change on blur in Date/DateTime components

---

projects/novo-examples/src/form-controls/date-picker/date-picker/date-picker-example.ts

Added a comment to clarify how NovoLabelService should be leveraged for DatePicker Component

add commment to DatePickerExample component

---

.github/workflows/pr.yaml

This action forces pull request titles to be in the proper "commit message format" for squash merges

chore(actions): enforce pull requests to be in a certain format

---

projects/novo-elements/src/elements/common/option/optgroup.component.scss
projects/novo-elements/src/elements/data-table/cell-headers/data-table-header-cell.component.ts
projects/novo-elements/src/elements/data-table/data-table.module.ts

fix filter

---

projects/novo-elements/src/elements/data-table/cell-headers/data-table-header-cell.component.ts

f/BH-72034 Added double click resize

---

projects/novo-elements/src/elements/field/formats/time-format.ts
projects/novo-elements/src/elements/time-picker/TimePickerInput.ts

Make it easier to create times for hour 1.

BH-74428 time picker hour 1 enhancement

---

package-lock.json
projects/novo-elements/src/elements/form/ControlGroup.ts
projects/novo-elements/src/elements/form/DynamicForm.ts
projects/novo-elements/src/elements/form/Form.ts
projects/novo-elements/src/elements/form/NovoFormGroup.ts
projects/novo-elements/src/elements/picker/extras/base-picker-results/BasePickerResults.ts
projects/novo-elements/src/elements/stepper/stepper.component.ts
projects/novo-elements/src/elements/table/extras/base-renderer/BaseRenderer.ts
projects/novo-elements/src/elements/table/extras/date-cell/DateCell.ts
projects/novo-elements/src/elements/table/extras/dropdown-cell/DropdownCell.ts
projects/novo-elements/src/utils/form-utils/FormUtils.ts

Reverts bullhorn/novo-elements#1266
Reverting this from master due to issues with versioning. Going to keep this on next branch for now.

refactor(): REVERT: some refactor work in preparation for typescript 4.0.8 upgrade

---

projects/novo-elements/src/elements/data-table/cell-headers/data-table-header-cell.component.ts

fix(imports): fix utils import

---

projects/novo-elements/src/elements/chips/ChipInput.ts
projects/novo-elements/src/elements/data-table/data-table.component.ts
projects/novo-elements/src/elements/data-table/interfaces.ts
projects/novo-elements/src/elements/data-table/state/data-table-state.service.spec.ts
projects/novo-elements/src/elements/data-table/state/data-table-state.service.ts
projects/novo-elements/src/elements/field/formats/date-format.ts
projects/novo-elements/src/elements/field/formats/date-range-format.ts
projects/novo-elements/src/elements/field/formats/time-format.ts
projects/novo-elements/src/elements/picker/Picker.scss
projects/novo-elements/src/elements/picker/extras/workers-comp-codes-picker-results/WorkersCompCodesPickerResults.ts
projects/novo-elements/src/elements/query-builder/condition-builder/condition-builder.component.scss
projects/novo-elements/src/elements/query-builder/condition-builder/condition-builder.component.ts
projects/novo-elements/src/elements/query-builder/condition-definitions/string-condition.definition.ts
projects/novo-elements/src/elements/query-builder/condition-group/condition-group.component.html
projects/novo-elements/src/elements/query-builder/condition-group/condition-group.component.ts
projects/novo-elements/src/elements/query-builder/criteria-builder/criteria-builder.component.ts
projects/novo-examples/src/examples.routes.ts
projects/novo-examples/src/updates/june-2022.md

fix(): fixing some typos and removing some commented out code [52896f](https://github.com/bullhorn/novo-elements/pull/1338/commits/52896f9b65036e22b5241f547e7b764a8088ea13)
fix(WorkersCompCodesPickerResults): - fix buggy picker behaviour for workers comp code pickers #1343 fix(NovoDefaultStringConditionDef): fixing bug with the model when loading multiple string defs #1342

feat(): next

---

projects/novo-elements/src/elements/date-time-picker/DateTimePicker.ts
projects/novo-elements/src/elements/field/field.module.ts
projects/novo-elements/src/elements/field/formats/date-time-format.ts
projects/novo-elements/src/elements/field/index.ts
projects/novo-elements/src/elements/form/Form.module.ts
projects/novo-examples/src/components/field/form-usage/form-usage-example.html
projects/novo-examples/src/components/field/form-usage/form-usage-example.ts

Added a formatter for the dateTime Picker to work with fields. Also fixed a bug where the dateTimePicker was changing the date upon selection of the time.
- [ x] Any related demos were added and `npm start` and `npm run build` still works
- [ x] New demos work in `Safari`, `Chrome` and `Firefox`
- [ x] `npm run lint` passes
- [x ] `npm test` passes and code coverage is increased
- [ x] `npm run build` still works
- [ x] Run `Novo Automation`

feat(dateTimePicker): Added formatter for dateTimePicker

---

projects/novo-elements/src/elements/chips/Chips.spec.ts
projects/novo-elements/src/elements/chips/Chips.ts

Ensure proper flow of async processes for Chips element.

feat(Chips): make setItems() async

---

projects/novo-elements/src/elements/chips/Chips.spec.ts
projects/novo-elements/src/elements/chips/Chips.ts

Reverts bullhorn/novo-elements#1395

fix(): Revert "feat(Chips): make setItems() async"

---

projects/novo-elements/src/elements/checkbox/Checkbox.ts
projects/novo-examples/src/examples.routes.ts
projects/novo-examples/src/form-controls/checkbox/basic-checkbox/basic-checkbox-example.css
projects/novo-examples/src/form-controls/checkbox/basic-checkbox/basic-checkbox-example.html
projects/novo-examples/src/form-controls/checkbox/basic-checkbox/basic-checkbox-example.ts
projects/novo-examples/src/form-controls/checkbox/basic-checkbox/index.ts
projects/novo-examples/src/form-controls/checkbox/checkbox-list/checkbox-list-example.css
projects/novo-examples/src/form-controls/checkbox/checkbox-list/checkbox-list-example.html
projects/novo-examples/src/form-controls/checkbox/checkbox-list/checkbox-list-example.ts
projects/novo-examples/src/form-controls/checkbox/checkbox-list/index.ts
projects/novo-examples/src/form-controls/checkbox/checkbox.md
projects/novo-examples/src/form-controls/checkbox/index.ts
projects/novo-examples/src/form-controls/index.ts

#1425 introduced a display bug with checked checkboxes not appearing checked. this was caused by the template property changes, so those were rolled back to be looked at later. 
i also added a new checkbox demo under the form controls section so this can be more easily tested in the future.

fix(Checkbox): fixing checkbox display bug and adding demo

---

projects/novo-examples/src/examples.routes.ts
projects/novo-examples/src/utils/code-editor/code-editor.md
projects/novo-examples/src/utils/drag-drop/drag-drop.md
projects/novo-examples/src/utils/drag-drop/drag-drop/drag-drop-example.css
projects/novo-examples/src/utils/drag-drop/drag-drop/drag-drop-example.html
projects/novo-examples/src/utils/drag-drop/drag-drop/drag-drop-example.ts

Updates to the drag drop example to make it more presentable.

docs(DragDrop): Updated drag-drop example

---

projects/novo-elements/src/services/date-format/DateFormat.spec.ts

Fixes a number of unit tests regarding date verification, and adds new ones, for DateFormat.ts.
Improves coverage

test(DatePicker): Correct verification of DateFormat methods

---

projects/novo-elements/src/elements/chips/Chips.ts
projects/novo-examples/src/form-controls/chips/hide-chips/hide-chips-example.ts

- fixed edge-case (not found in examples) where model data is passed in to Chips.ts and hiddenChipsLimit is enabled/used.

fix(Chips): hidden-chips, existing model data

---

projects/novo-elements/src/elements/data-table/interfaces.ts

Reverts bullhorn/novo-elements#1545

fix(): Revert "fix(Criteria Types): Adding missing operator types"

---

projects/novo-elements/src/elements/button/styles/button-dialogue.scss
projects/novo-elements/src/elements/chips/Chips.ts

feat(Chips): allow novo-chip size input via novo-chips

---

projects/novo-elements/src/elements/data-table/interfaces.ts

feat(Data Table): Allow for saving of keywords in data table preferences

---

projects/novo-elements/src/elements/query-builder/condition-builder/condition-builder.component.html
projects/novo-elements/src/elements/query-builder/condition-builder/condition-builder.component.ts
projects/novo-elements/src/elements/query-builder/query-builder.types.ts
projects/novo-elements/src/elements/select/Select.module.ts
projects/novo-elements/src/elements/select/Select.ts
projects/novo-examples/src/form-controls/select/basic-select-with-search/basic-select-with-search-example.html

Add optional icon to select component and use it in the condition builder component

feat(Select): add icon option to select

---

projects/novo-elements/src/elements/data-table/interfaces.ts
projects/novo-elements/src/elements/places/places.component.ts
projects/novo-elements/src/elements/query-builder/condition-builder/condition-builder.component.html
projects/novo-elements/src/elements/query-builder/condition-builder/condition-builder.component.scss
projects/novo-elements/src/elements/query-builder/condition-builder/condition-builder.component.ts
projects/novo-elements/src/elements/query-builder/condition-definitions/address-condition.definition.ts
projects/novo-elements/src/elements/query-builder/condition-templates/condition-templates.component.html
projects/novo-elements/src/elements/query-builder/condition-templates/condition-templates.component.ts
projects/novo-elements/src/elements/query-builder/criteria-builder/criteria-builder.component.html
projects/novo-elements/src/elements/query-builder/criteria-builder/criteria-builder.component.spec.ts
projects/novo-elements/src/elements/query-builder/criteria-builder/criteria-builder.component.ts
projects/novo-elements/src/elements/query-builder/query-builder.types.ts
projects/novo-elements/src/services/novo-label-service.ts
projects/novo-examples/src/components/query-builder/just-criteria/just-criteria-example.html
projects/novo-examples/src/components/query-builder/just-criteria/just-criteria-example.ts

Added Radius Option to the Criteria Condition Builder

feat(Criteria Builder): Add location radius option to the criteria condition builder

---

projects/novo-elements/src/elements/form/ControlTemplates.ts
projects/novo-elements/src/elements/form/controls/BaseControl.ts

feat(SwitchControl): add change propogation to Switch Control Template

---

projects/novo-elements/src/elements/date-picker/DatePicker.scss
projects/novo-elements/src/elements/date-picker/DatePicker.ts
projects/novo-elements/src/elements/date-picker/DatePickerInput.scss
projects/novo-elements/src/elements/date-picker/DatePickerInput.spec.ts
projects/novo-elements/src/elements/date-picker/DatePickerInput.ts
projects/novo-elements/src/elements/date-time-picker/DateTimePicker.ts
projects/novo-elements/src/elements/field/formats/date-format.ts
projects/novo-elements/src/elements/field/formats/date-range-format.ts
projects/novo-elements/src/elements/field/formats/date-time-format.ts
projects/novo-elements/src/elements/field/formats/time-format.ts
projects/novo-elements/src/elements/field/picker.directive.ts
projects/novo-examples/src/components/field/field-usage/field-usage-example.html
projects/novo-examples/src/components/field/field-usage/field-usage-example.ts

fix(DatePicker): Fixed some behaviors of Date Picker to respect Clear button behavior, output events
Updated Date Picker Input component to add a "hasButtons" boolean input, and some new output events for better integration

feat(DatePicker): Add optional Cancel/Save buttons to Date Picker

---

projects/novo-elements/src/elements/places/places.component.ts
projects/novo-elements/src/elements/places/places.service.ts
projects/novo-elements/src/elements/query-builder/condition-definitions/address-condition.definition.ts
projects/novo-elements/src/elements/query-builder/query-builder.types.ts

feat(GooglePlacesService): add postal_codes to AddressData for better locality support
