demo/pages/select/SelectDemo.js
demo/pages/select/templates/BasicSelectDemo.html
src/elements/form/extras/form-input/FormInput.js
src/elements/form/extras/select-input/SelectInput.js
src/elements/select/Select.js
src/elements/select/_Select.scss

This branch adds an optional footer to the novo-select element that adds a new item to the list. The footer will be displayed if a footerConfig object is passed in; that footerConfig should contain the label for the footer (the default display), the placeholder for the input (displayed when footer is open), and the onSave function. 
Primarily the Select element. Passed the footerConfig down through the FormInput --> SelectInput. Updated the SelectDemo to show an example.
* @jgodi

feat(select) implement optional select footer component

---

src/elements/form/_Form.scss
src/elements/form/extras/check-box/CheckBox.js
src/elements/form/extras/form-input/FormInput.js

* Added a disabled property to form-input
* Added a disabled property to checkboxes to disable it
* new property to form-input & checkbox
*  styles for the new disabled class on checkbox
* @user
* [] Changes are limited to a single goal (no scope creep)

Added a disabled property to form-input to disable checkboxes

---

demo/pages/form/FormDemo.js
src/elements/form/_Form.scss
src/elements/form/extras/FormExtras.js
src/elements/form/extras/form-input/FormInput.js
src/elements/form/extras/tiles-input/TilesInput.js
src/elements/form/extras/tiles-input/TilesInput.spec.js
src/elements/tiles/_Tiles.scss

Updated the Styling for tiles so it is more flexible to various content, removed any absolute labels.
Added tiles to the form component
form component
tiles component
* @bvkimball @jgodi @krsween 
Changes to styling for Tiles component and adding form support for it

BH-38530 Novo: Incorporate Schedule Next Action within Notes

---

src/assets/styles/global/_functions.scss
src/elements/loading/Loading.js
src/elements/loading/_Loading.scss
src/elements/loading/_NovoSpinner.scss

Cross-browser fixes for loading animations: chrome, firefox, safari, iOS
* Adds animation path to spinner animation for firefox
* Removes filter effect on Safari / iOS Safari (Safari bug)
* @jgodi

fix(loading): Cross browser fixes for Loading element animations

---

src/elements/picker/_Picker.scss

Extra padding was added to the top of picker results
Removed padding-top
* @jgodi @bvkimball @krsween

fix(chips): change extra margin/padding on bottom

---

src/elements/form/Form.js

All users of form can subscribe to its changes via the changed output
- new form output changed emits event when form is updated
* @user @krsween @bvkimball

feat(form): form output to subscribe to changes

---

src/assets/styles/global/_variables.scss

adding Notes entity color to _variables.scss
`+$note: #778899;
+note: $note`

feat(entitycolor): adding notes entity color

---

src/elements/form/Form.js
src/elements/form/Form.spec.js
src/elements/toast/_Toast.scss

- style(toast): updates to toast styles
- fix(form): fixes hiding of boolean required fields
- Form: checks explicitly for null & undefined to account for boolean fields
- Form: removed unused import
- Toast: message only version font-size
- Toast: more padding-left
* @krsween @bvkimball

Updates for required fields & toast

---

src/elements/table/Table.js
src/elements/table/Table.spec.js

Changed table filtering from on-init to on-filter
Changed table filtering from on-init to on-filter
* @bvkimball

refactor(Table): refactored table filtering to be on-filter not on-init

---

demo/pages/table/TableDemo.js
demo/pages/table/templates/TableDemo.html
src/elements/table/extras/pagination/Pagination.js

Changed property names to be more intuitive.
`tableOptions` is now `rowOptions`
* @bvkimball

refactor(Pagination): changed property names to be more intuitive

---

src/elements/tiles/Tiles.js

fix for bug when element span.active-indicator did not exist (when there was no default value)
ngIf -> hidden
* @bvkimball 
- switched ngIf to hidden so that element always exists

fix(tiles): fix for no defaults

---

demo/pages/app/App.js
demo/pages/tip-well/TipWellDemo.js
demo/pages/tip-well/templates/TipWellDemo.html
src/elements/tip-well.js
src/elements/tip-well/README.md
src/elements/tip-well/TipWell.js
src/elements/tip-well/TipWell.spec.js
src/elements/tip-well/_TipWell.scss
src/novo-elements.js
src/novo-elements.scss

A TipWell can be used to display an in-line contextual help window for features that may confuse average users.
Added a new component, it's demo, and associated readme to novo-elements
* @jgodi

feat(TipWell): adding new TipWell feature

---

src/elements/form/extras/picker-input/PickerInput.js

In forms with the picker, if you press CMD+A or CTRL+A it registers in the DOM as a `select` event and passes that as a value into the picker, which throws off validation.
This checks if the value being passed in is an event and if it is an event it sets the value of picker to null.
* @jgodi

refactor(Picker): Added the ability to filter out events

---

src/elements/form/extras/date-input/DateInput.js

DateInput sets the input to ngModel.value but does not pass it to the date picker component
DateInput.js

bug(Form): DateInput value does not bind to ngModel

---

demo/pages/tip-well/TipWellDemo.js
demo/pages/tip-well/templates/TipWellDemo.html
demo/pages/tip-well/templates/TipWellIconDemo.html
demo/pages/tip-well/templates/TipWellNoButtonDemo.html
src/elements/tip-well/README.md
src/elements/tip-well/TipWell.js
src/elements/tip-well/TipWell.spec.js
src/elements/tip-well/_TipWell.scss

Add icon to tipwell and make button optional
I added two variables icon and hasButton. Icon is used to display an icon at the front of the tipwell. Icon defaults to not showing. hasButton decides whether or not the button will be shown. It defaults to true. 
* @user

feat(tipwell): Add icon and optional button

---

src/elements/table/Table.js

Date filters are objects in the new date-filter drop-down, but the data automation IDs still treat them as though they're strings.
Date-filter automation IDs now pass a date object's `label` property or the date object itself.
* @jgodi

chore(Table): Refactored automation IDs

---

src/assets/styles/content/_typography.scss

`<p>` tags are used for block paragraph text and should have a max-width. (See [typography](http://bullhorn.github.io/novo-elements/#/typography) section of style guide)
* Adds `max-width: 33em;` to `p` tags in global typographic styles.
* @jgodi

Adds max-width to paragraph tags

---

demo/novo-elements-demo.module.js
demo/pages/elements/form/FormDemo.js
demo/pages/elements/form/templates/TextBasedControls.html
demo/pages/elements/quick-note/QuickNoteDemo.js
src/elements/form/Control.html
src/elements/form/Control.js
src/elements/quick-note/QuickNote.js

Need to listen to changes on model passed into QuickNote CMP
Added eventEmitter that broadcasts changes on the QuickNote CMP and the form Control that injects it.
* @jgodi

refactor(QuickNote): Added emitter for model changes on QuickNote

---

src/elements/picker/Picker.js

Picker for backspacing, deletes the value but keeps the term
* picker
* @krsween

fix(picker): Fixing backspacing on picker

---

demo/pages/elements/button/ButtonDemo.js
demo/pages/elements/button/templates/DynamicButtonDemo.html
demo/pages/elements/list/ListDemo.js
demo/pages/elements/list/templates/ThemedListDemo.html
src/elements/button/Button.js
src/elements/button/Button.spec.js
src/elements/list/List.js
src/elements/list/README.md
src/elements/list/_List.scss

Novo Lists not can be themed with the [theme] attribute
```
<novo-list theme="navigation"></novo-list>
```
demo included!
What did you change?
Lists
also had a bug fix for button to update when Inputs changed
Reviewers: @jgodi

feat(list): Added themes support to Novo List

---

src/elements/chips/Chips.js

Fixed a bug on chips that allowed events to be passed in as values.
I added a condition to check if the data being passed in was an event.
Resolves #165 
* @jgodi

fix(Chips): Preventing null values from being passed on double-click

---

src/elements/form/Control.html
src/elements/form/Control.js

Fixes vertical layout forms with placeholders... 
* checks `control.placeholder`
* fixes active field label alignment
* @jgodi

fix(forms): Adds support for placeholders in vertical layout

---

src/elements/form/Control.html
src/elements/form/Control.js
src/elements/form/README.md
src/elements/form/controls/BaseControl.js
src/elements/form/controls/BaseControl.spec.js

allowing setting of maxlength
- setting maxlength on the control will set it on the input & textarea
* @jgodi

feat(form): allowing setting of maxlength on input

---

src/elements/form/_Form.scss

_Remove min-height from novo-control_
I removed the `min-height` property from `novo-control`
* @jgodi 
The min-height is causing a ton of white space to happen when the
control is hidden

fix: remove min-height from novo-control

---

src/elements/table/Table.js

This PR adds an additional input to the novo-table element. When skipSortAndFilterClear is true, the sorts and filters will persist after resetting the table rows. This will allow outside handling of async dataloading with persistent filters (needed for canvas-ui), until that's handled inside novo-table.
-Added a boolean input (skipSortAndFilterClear) to novo-table that defaults to false.
-Wrapped the clearSortFilters function in an if statement
* @jgodi

feat(table): make clearing filtering/sorting optional when setting rows

---

src/elements/form/FormUtils.js
src/elements/form/FormUtils.spec.js

Placements don't get the entity pickers.
Added Placements to the TO_ONE and TO_MANY types that get pickers and chips.
* @jgodi

refactor(forms): change FormUtils to include Placement

---

src/elements/picker/extras/entity-picker-results/EntityPickerResults.js

Display Client contact instead of Corporation twice for Placement
* @user

Display Client contact instead of Corporation twice for Placement

---

demo/pages/elements/toast/ToastDemo.js
demo/pages/elements/toast/templates/ToastDemo.html
src/elements/toast/Toast.js

Toast: Theme and Icon are now bound properly and will update when you are using a static toast component.
added `ngOnChanges`
* @jgodi

fix(Toast): Theme and Icon are now bound properly

---

src/elements/table/_Table.scss

On tables with checkboxes in the leftmost column, clicking the checkbox would make the rows' background color flash.
* Adds fixes for chrome rendering bugs: `transform-style: preserve-3d;`
* @jgodi

fix(table): Updated table row styles, removes flashing bg

---

src/elements/multi-picker/MultiPicker.js
src/elements/multi-picker/Multipicker.spec.js
src/elements/picker/extras/checklist-picker-results/ChecklistPickerResults.js

This PR makes the indeterminate state of 'All [type]' function the same as the 'All Selected' checkbox in Table. That is - when any item of a type is checked, the state of 'All [type]' should be indeterminate. This PR also makes it so when all items of a type are selected individually/manually, 'ALL [type]' will become checked and 'ALL [type]' will be displayed as a chip (instead of all individual items). Also includes some clean up and additional specs.
- Improvements to Multipicker to make it behave like Table
* @jgodi 
…e table

feat(multipicker): Make 'All [type]' indeterminate state function like Table

---

src/elements/multi-picker/MultiPicker.js
src/elements/multi-picker/Multipicker.spec.js

This PR fixes a bug where clearAll failed to reset indeterminate checkboxes.
- clearAll now sets indeterminate to false
- added to spec
* @jgodi

bug(multipicker): fix for clearAll

---

src/elements/form/Control.html
src/elements/form/FormUtils.js
src/elements/form/extras/address/Address.js
src/utils/countries/Countries.js
src/utils/countries/Countries.spec.js

Show and populate address fields
I changed the Address `writeValue` function to actually populate the address field, and changed formUtils to show the address field
* @jgodi 
* @bvkimball

fix:(address fields): Show and populate address fields

---

src/elements/table/Table.js
src/elements/table/_Table.scss
src/elements/table/extras/th-sortable/ThSortable.js

Fix table and sorting logic so that columns marked sorting: false do not display sorting features.
Table.js
_Table.scss
ThSortable.js
* @user

Fix logic to respect when column sorting is false

---

src/elements/table/_Table.scss

Show background correctly for select all results
Update the zibra table to not display for the selection line
* @user

BH-45115 - Show Select All text correctly

---

src/elements/form/extras/address/Address.js

Some state data is stored as `Ca.`, so we need to replace all odd characters and toUpperCase the state code. Also, fixed country name matching.
I added a `.replace` to remove odd characters when matching state codes, and added `.trim` for the countryName to ensure matching is correct.
* @jgodi

fix(address field): state matching and country name matching

---

src/elements/form/Form.scss

Added styling to change gray bottom border to display red when Note is saved and required field is not populated.
* @user

Styling for Underline Required Note fields

---

demo/pages/elements/multi-picker/MultiPickerDemo.ts
src/elements/multi-picker/MultiPicker.ts

Fix bugs to handle parents who don't have children. Added an example to demo. Make sure to reset display items when unselecting all of a type.
Multipicker
* @jgodi

bug(multipicker): Fix bugs surrounding  parents without children

---

src/elements/multi-picker/MultiPicker.ts

Fix two small bugs that occur when clearing via chip.
Multipicker.tx
* @jgodi

bug(multipicker): fix bug with chip removal

---

.gitignore
demo/pages/elements/form/FormDemo.ts
demo/pages/elements/form/MockMeta.ts
demo/pages/elements/form/templates/DynamicForm.html
demo/pages/elements/form/templates/DynamicFormFieldSets.html
src/elements/form/DynamicForm.ts
src/elements/form/Form.module.ts
src/elements/form/Form.scss
src/elements/form/FormUtils.ts

form fieldsets aka sections
- a fieldset is a group of form controls
- if novo-dynamic-form has a fieldsets input, it will ignore controls input
- fieldsets can have headers
- fieldset structure is defined by the NovoFieldset Interface
* @jgodi @bvkimball @asibilia 
- form controls can be grouped as fieldsets
- form will either use controls or use fieldsets as input

feat(form) added fieldsets with headers

---

src/elements/table/Table.ts

Canvas-UI uses a custom sorting/filtering function to load sorted/filtered reports. This PR adds back in that functionality.
Table.ts
* @jgodi

fix(table): add back in custom sorting/filtering functions

---

src/elements/table/Table.ts
src/elements/table/extras/pagination/Pagination.ts

Pagination now uses two-way from the DataProvider page and pagesize.
* @jgodi

fix(Table): Binding Pagination to dataProvider

---

src/elements/form/FormUtils.ts

Added a default sort order if no property on field
* @bvkimball @jgodi @krsween @amrutha-rajiv

bug(form-utils): Fieldmaps with no sort order are never added to the controls

---

src/elements/table/Table.ts

SelectAll functionality was broken when we added the PagedArrayCollection.  It was only using the pagedData, now this has been fixed to use the the Collections filteredData.
* @jgodi

fix(Table): SelectAll functionality has been fixed

---

src/elements/picker/Picker.ts

Clearing the picker onActiveChange cleared single value pickers.
Removed clearing altogether since data isn't set until the picker's dropdown's select event is fired.
* @jgodi

refactor(Picker): Remove term clearing from picker onActiveChange

---

src/elements/chips/Chips.scss
src/elements/chips/Chips.ts
src/utils/Helpers.ts

Added interpolation validator to Helpers and used it in Chips to prevent uninterpolated format params from being passed into chip labels. Also added a chip style fix for entity chip icons.
* @user

fix(Chips): Validate properties before interpolating a label string

---

src/elements/form/FormUtils.ts

fix for removing empty objects so they do not populate as [object Object] in multi select pickers
FormUtils.ts

fix(pickers): fix for removing empty objects so they do not populate as [object Object] in multi select pickers

---

src/elements/table/Table.ts

Column filtering with options should not have text input if values are not strings
Table.ts
* @bvkimball @jgodi

fix(Table): column filtering with options should not have text input if values are not strings

---

src/elements/table/Table.ts

Improvement over previous implementation which failed if the user search for a string which was not an option.
TableUtils.ts
* @bvkimball @jgodi

fix(Table): column filtering by options should not have text input if values are not string

---

src/elements/table/Table.ts

In the Table component, the existing class setter for column headers didn't do anything. Also, it would be helpful to use that class to discern what type of column header is being used.
Added dynamic classes for each of the main column types.
* @jgodi

feature(Table): added classes for main types of column headers

---

src/elements/table/Table.ts

Some tables have drop-downs for actions and not just a checkbox.
Added a class for actions that's separate from the checkbox.
* @jgodi

feat(Table): Adding actions column header type

---

src/elements/form/FormUtils.ts

FormUtils: Correctly Sort if no sortOrder was provided
sortOrder is now populated to be the default max value before the fields are sorted
* @user

FormUtils: Correctly Sort if no sortOrder was provided

---

demo/pages/elements/table/TableDemo.ts
demo/pages/elements/table/templates/TableDemo.html
src/elements/table/README.md
src/elements/table/Table.scss
src/elements/table/Table.ts
src/services/data-provider/ArrayCollection.ts
src/services/data-provider/Collection.ts
src/services/novo-label-service.ts

When Empty State was added to Tables, it was not considered that a filtered table with no records should show a different states. 
Table Empty State
Table No Matching Records State
* @jgodi

feat(Table): Split Empty and NoMatchingRecords States for Tables

---

src/elements/chips/Chips.ts

Currently if you pass in an array of string values to the Chip Picker who's options contain an array of objects (value and label) the value is displayed in the picker, not the label.
example:
set Picker value to [ 'AL'];
picker options:
[{value:'AL', label:'Alabama'}, {value:'MA', label:'Massachusetts'}]
before, would display - 'AL' in Chip
after, now displays - 'Alabama' in Chip
Picker.ts

feat(Chips): Adding support for Chips labels to be displayed correctly when only value passed in

---

src/elements/date-picker/DatePicker.ts

DatePicker.ts
* @bvkimball  @jgodi @krsween

fix(DatePicker): Selecting either month or year in Date Picker resets other value to default

---

src/elements/table/Table.ts

**WARNING**: This is a breaking change to how dates are returned in the filter.
fix(Table): Tables won't convert Dates into timestamps
Custom filter functions can now differentiate between Numbers vs a Dates

fix(Table): Tables won't convert Dates into timestamps

---

src/elements/form/FormUtils.ts
src/utils/Helpers.ts

Fall back to sorting by name if sortOrder is equal
Helpers.sortByField can now take in an array of fields to sort by
* @user

Fall back to sorting by name if sortOrder is equal

---

src/elements/select/Select.ts

added a typeahead for country dropdowns
* @user

feat(dropdown): adding typeahead for dropdowns

---

src/elements/date-time-picker/DateTimePicker.ts
src/elements/date-time-picker/_DateTimePicker.scss

updated .indicator class of DateTimePicker to be unique
.indicator class on DateTimePicker was interfering with .indicator class of novo-modal, so DateTimePicker was using both when styling the picker when loading it in a modal, causing it to look funky.
* @user

BH-46763 fix for DateTimePicker style when displayed in modal

---

src/elements/form/FormUtils.ts

Proprietary types of form elements were being evaluated by FormUtils.
Removed proprietary type-checking from FormUtils.
* @bvkimball @jgodi

refactor(FormUtils): removed proprietary type-checking from FormUtils

---

demo/pages/elements/table/MovieDataProvider.ts
src/elements/table/Table.ts
src/utils/Helpers.ts

fix(Table): Date Filtering and Options filtering is more stable.
Warning: Filters are no longer Arrays unless column is set to multiple. which is seemingly deprecated, need to evaluate continued support

fix(Table): Date Filtering and Options filtering is more stable.

---

src/elements/table/Table.ts

This is a hacky fix for the time being. It will be fixed as part of next sprint when Canvas code gets refactored to use new code in novo-table. 
Added boolean to ngIf of novo-table header. This will allow the header to get displayed in Canvas when there is an empty state while filtering. This boolean will get removed as part of BH-47169 during the next sprint. We would like to add this hack fix in the meantime so our popover code can be used and released in 2017.2. 
* @bvkimball 
* [x ] Changes are limited to a single goal (no scope creep)
* [x ] Code can be automatically merged (no conflicts)
* [x ] Code follows the standards laid out in the [contributing guide](https://github.com/bullhorn/novo-elements/blob/master/CONTRIBUTING.md)
* [x ] Passes all existing automated tests
* [x ] …

BH-44785:fix for table empty state for Canvas

---

src/elements/form/FormUtils.ts

When removing setRequired(true) on a control the required validator is not removed from the control
FormUtils.ts

bug(Form): When removing setRequired(true) to a control the required validator is not removed from the control

---

src/elements/form/Control.ts

Field Interactions cause CKEditor to crash browser by calling change events continuously
Control.ts

bug(Form): Field Interactions cause CKEditor to crash browser

---

src/elements/form/FormUtils.ts

form interactions removes required after every change, should only be on required state change
FormUtils.ts
* @bvkimball @jgodi

bug(Form): form interactions removes required after every change, should only be on required state change

---

src/elements/form/FormUtils.ts

Adding setTimeout to the setValue for field interactions too prevent expression changed errors

bug(Form): Adding setTimeout to the setValue for field interactions too prevent expression changed errors

---

src/elements/table/Table.ts

Issue occurring in Canvas where clicking filter and/or sorts really fast would cause the state of the table to be bad. Multiple columns would be registered as sorted.
Now onSortChange will remove the sort from every other column except for the column that is currently getting sorted.
* @user
* [x ] Changes are limited to a single goal (no scope creep)
* [x ] Code can be automatically merged (no conflicts)
* [x ] Code follows the standards laid out in the [contributing guide](https://github.com/bullhorn/novo-elements/blob/master/CONTRIBUTING.md)
* [x ] Passes all existing automated tests
* [x ] New functions are documented (with a description, list of inputs, and expected output)
* [x ] Visually tested in supported browsers and devices

fix(table) fix issue with multiple columns having sort enabled

---

src/elements/select/Select.scss

Increased the max height of the select containers so that the show half of the next element.
I am sorry about the new max-height, I feel dirty using 219px but its what looks best. (UX agrees)
select.scss
* @jgodi
* @more

feat(Select): Increase Form Dropdown Height by 2.5 Items #313

---

src/elements/table/Table.ts

this is a fix for if config = { paging: false } which we want because we don't want to show pagination control on tables that can only contain 5 records
* @jgodi
* @more

feat(Table): When paging is false the start and count values are not set on the dataprovider

---

src/elements/form/Control.ts

Stopped label from overriding entered text in picker control
Added _enteredText private variable, and check it when determining if the label is active for picker controls.
*Issue:*
*Fix:*
* @jgodi
* @more

BH-48213 - Stopped label from overriding entered text in picker control

---

src/elements/quick-note/QuickNote.ts

The formatted note object is only created on initial value set. When the value is set dynamically more than once (injected templates for example) the note object is not formatted and appended correctly.
* @jgodi
* @more

bug(QuickNote): Quick Note does not create the formatted object on writeValue.

---

src/elements/table/Table.ts

· Fixed issue where you could not add a new row if the table was empty
· Adding new row carried over values from previous row
· added now property on columns `hiddenOnEdit` which will hide the cells content when in edit mode
Table.ts
* @jgodi
* @more

feat(Edit Table): Edit table improvements and fixes

---

src/elements/date-time-picker/DateTimePicker.ts
src/elements/form/Control.ts
src/elements/select/Select.ts

onSelect events need to be fired after the onModelChange call because onSelect will be expecting the new values to be present in this.model
moved onSelect calls to be above onModelChange for date-time pickers.
added modelChange events to date, date-time, and time pickers when clearing the picker in a control.
* @jgodi
* @more

fix(control): Moving onSelect events after onModelChange call

---

src/elements/modal/Modal.scss
src/elements/modal/Modal.ts

This allows for users of the Notification Modal to be alerted when the 'X' is used to close the modal.
Also, the max width of the Notification Modal was changed to 600px.
* @jgodi
* @more

feat(modal): Added cancel event to the Notification Model

---

src/elements/table/Table.ts

cannot read properties of undefined pointing to the table _editing array
` t=!this.parentView.context.$implicit._editing[this.context.$implicit.name];`
added defensive code to make sure `_editing` exists on row
* @jgodi
* @more

bug(Table): fix for property of undefined on _editing

---

src/elements/table/Table.ts

Attempting to filter the Novo table on a String with an apostrophe in it, such as "User's Test Report", would cause an error.
Added a function to escape apostrophes when pre-filtering the String
* @jgodi
* @more

fix(Table): Escape apostrophes in onFilterChange

---

src/elements/multi-picker/MultiPicker.ts
src/elements/multi-picker/Multipicker.spec.ts
src/elements/picker/extras/checklist-picker-results/ChecklistPickerResults.ts

Labels for the sections in the picker dropdown need to be localized. 
This allows you to define the label of the types as well as allowing localized values (with spaces and special charactes) in the source.options array. Code is backwards compatible with previous way of defining the labels
* @jgodi
* @krsween 
* @more

fix(multipicker): Values in multipicker can now be localized

---

src/elements/form/extras/file/FileInput.scss
src/elements/form/extras/file/FileInput.ts

Fix alignment of text and icon - text now aligned with dot in dropzone icon, see below
* @jgodi
* @more

fix(fileInput): Fix alignment of file input dropzone icon

---

src/elements/form/Form.scss

Form Labels now wrap when text is to long.
word-break: word-break;
overflow-wrap: break-word;
* @jgodi
* @more

style(Form): Form Labels now wrap when text is to long.

---

src/elements/table/Table.ts

Use data provider total instead of length so the selectAll shows up even if only the first page is loaded
* @jgodi
* @more

selectAll not always showing

---

src/elements/ckeditor/CKEditor.spec.ts
src/elements/ckeditor/CKEditor.ts
src/elements/quick-note/QuickNote.ts

Putting an end to this:
And removed this:
Stopped using the built-in spell checker in CKEditor, which is a paid product, and switched to browser built-in spell checker instead.
* @jgodi
* @more

BH-51801 - Switched from third party spell checker to browser built-in

---

demo/pages/elements/editor/templates/BasicEditorDemo.html
src/elements/ckeditor/CKEditor.spec.ts
src/elements/ckeditor/CKEditor.ts
src/elements/quick-note/QuickNote.ts

The HTML that comes from the CKEditor config surrounds all line breaks with `<p>` tags, which formats with lots of whitespace when that text is sent in an email. 
Using `<br>` tag option for regular enter key presses, and `<p>` tags only for shift + enter.
* @jgodi
* @more

BH-52302 - Fixed formatting in CKEditor to look better in emails

---

demo/assets/styles/main.scss
demo/pages/elements/editor/EditorDemo.ts
demo/pages/elements/form/FormDemo.ts
src/elements/button/Button.scss
src/elements/calendar/month/CalendarMonthView.scss
src/elements/drawer/Drawer.ts
src/elements/dropdown/Dropdown.scss
src/elements/tabs/Tabs.scss

Fixing styling issues where Safari renders elements poorly. Testing against Chrome and Firefox to ensure that changes do not break any existing look and feel.
Fixed issue with `novo-dropdown` displaying at a bad location for Safari only. Fixed in a way that is supported by Safari, Chrome, and Firefox.
Fixed issue where images in the demo were monster sized:
Tamed the mega spinner:
Fixed calendar event rendering in Big Calendar for Safari:
* @jgodi
* @monroepe Fi

Safari Browser Fixes

---

src/elements/quick-note/QuickNote.spec.ts
src/elements/quick-note/QuickNote.ts

Fixed the location of the quick note results dropdown - a previous commit started always positioning it at the top of the editor.

Fixing the quick note results dropdown positioning to be at the cursor

---

src/elements/select/Select.spec.ts
src/elements/select/Select.ts

Searching for values in select drop downs is currently broken and this pull request fixes the issue. Basically if you open a select element (where the options are just strings as seen in the demo) and start typing you are unable to select any of the values. The fix is that we check if the options are not objects and use the formattedOptions instead.

fix(select): Fixing select searching and selecting

---

demo/pages/elements/form/MockMeta.ts
src/elements/form/DynamicForm.ts
src/elements/form/FormInterfaces.ts
src/utils/form-utils/FormUtils.spec.ts
src/utils/form-utils/FormUtils.ts

Included an icon input for DynamicForms that allows sectionHeaders to pass a custom icon in 
- [X ] Any related demos where added and `npm start` still works
- [ X] New demos work in `Safari`, `Chrome` and `Firefox`
- [ X] `npm run lint` passes
- [ X] `npm test` passes and code coverage is increased
- [ X] `npm run compile` still works

feat(forms) Custom section header icons for dynamic forms

---

src/utils/Helpers.spec.ts
src/utils/Helpers.ts

At times, Edge does not fill out the nextElementSibling. This method ensures that if it's missing, it gets calculated.

Added nextElementSibling helper method for Edge browser support

---

src/elements/form/extras/address/Address.scss

Added min-width to address control inputs to make flex behave in Firefox

Added min-width to address control to make flex behave in Firefox

---

src/elements/picker/extras/base-picker-results/BasePickerResults.spec.ts
src/elements/picker/extras/base-picker-results/BasePickerResults.ts
src/elements/picker/extras/entity-picker-results/EntityPickerResults.ts

Make picker defaultOptions handle promises, as well as functions and arrays.

Feat (picker)/ make defaultOptions handle promise

---

src/elements/form/Form.scss

Removed unneeded flex-basis on description text for dynamic forms - renders improperly in Safari only when there is a long description text.

BH-52999 - Removed unneeded flex-basis - renders improperly in Safari

---

demo/pages/elements/field-interactions/FieldInteractionsDemo.ts
demo/pages/elements/field-interactions/MockMeta.ts
src/elements/form/Control.ts
src/elements/form/FieldInteractionApi.ts
src/elements/form/Form.module.ts
src/elements/form/Form.scss
src/utils/app-bridge/AppBridge.ts

Work on FieldInteractionApi and AppBridge
- Changed AppBridge to create method for opening lists
- Changed FieldInteractionAPI to allow adding/removing fields on events other than onInit
- Added loading animation for async field interactions in Control.ts
- Styling changes to Form to allow for loading animation
- [ X ] Any related demos where added and `npm start` still works
- [ X ] New demos work in `Safari`, `Chrome` and `Firefox`
- [ X ] `npm run lint` passes
- [ X ] `npm run compile` still works

(feat) Field Interaction async loading animations, add/remove fields and open lists

---

demo/pages/elements/select/SelectDemo.ts
demo/pages/elements/select/templates/LongSelectDemo.html
src/elements/overlay/Overlay.ts
src/elements/select/Select.scss
src/elements/select/Select.ts

Styles and timings messed with Append to body
Selects pop-ups will now position appropriately when at top or bottom of the screen

fix(Select): Styles and timings messed with Append to body

---

CHANGELOG.md
demo/pages/design/typography/Typography.html
demo/pages/design/typography/Typography.scss
package.json
src/elements/chips/Chips.spec.ts
src/elements/multi-picker/Multipicker.spec.ts
src/styles/content/typography.scss

Add a new style to Typography that enabled section headers to be add outside of forms.

style(section header): Add a new form-independent section header style

---

src/elements/overlay/Overlay.ts

event was left behind and some browser thought it was window.event so it worked fine.

fix: event was no longer used but still lingered

---

src/elements/form/Control.ts
src/elements/form/Form.scss
src/elements/form/NovoFormControl.ts
src/elements/form/controls/BaseControl.spec.ts
src/elements/form/controls/BaseControl.ts
src/utils/form-utils/FormUtils.ts

added the encrypted icon to the control form when the field is a customEncrypted field

added the encrypted icon to the control form when the field is a customEncrypted field

---

novo-elements.scss

The capitalization was wrong for value causing build failures for projects that use novo-elements
- [ x ] Any related demos where added and `npm start` still works
- [ x ] New demos work in `Safari`, `Chrome` and `Firefox`
- [ x ] `npm run lint` passes
- [ x ] `npm test` passes and code coverage is increased
- [ x ] `npm run compile` still works

fix capitalization to prevent unix environment build fails

---

src/elements/form/ControlGroup.ts

Was getting build errors in Novo due to the duplicate key in an object literal declaration. This is just to remove the duplicate.

removed extra key in object literal declaration

---

src/elements/form/ControlGroup.ts

Added an event emitter for adding a new row to the control group class

BBO-2152 - (fix) added onAdd to Control Groups

---

src/elements/form/ControlGroup.scss

added css to handle the first button in a control group row. putting it here because it seems like the most useful place to have it since it's not BBO-specific.

BBO-2152 - Create css for first button in control row in control group

---

demo/pages/elements/editor/EditorDemo.ts
demo/pages/elements/editor/templates/BasicEditorDemo.html
demo/pages/elements/editor/templates/MinimalEditorDemo.html
demo/pages/elements/form/MockMeta.ts
src/elements/ckeditor/CKEditor.spec.ts
src/elements/ckeditor/CKEditor.ts
src/elements/form/Control.ts
src/elements/form/controls/editor/EditorControl.ts
src/utils/form-utils/FormUtils.spec.ts
src/utils/form-utils/FormUtils.ts

Added an additional parameter to CK editor to allow for a minimal look and feel, similar to quick note without references.

Change to allow CKEditor to have a minimal configuration

---

src/platform/novo-elements.module.ts

feat(module): adding DateFormatService to novo-elements module providers

---

src/platform/utils/form-utils/FormUtils.ts

Made a small change to prevent controls from being tossed out if ranges and fieldsets were never populated.

Override not always being respected for entityPicker

---

src/platform/elements/chips/Chips.ts
src/platform/elements/picker/Picker.spec.ts
src/platform/elements/picker/Picker.ts
src/platform/utils/form-utils/FormUtils.ts

For pickers, if `getLabels` is present, use the method to display the name instead of ID

Added support for array in getLabels for Picker Element, unit tests and code cleanup

---

src/app/pages/elements/quick-note/QuickNoteDemo.scss
src/platform/elements/quick-note/QuickNote.spec.ts
src/platform/elements/quick-note/QuickNote.ts

Added resize bar to the bottom of the QuickNote Element, to make it work like the Editor element.

Added expander to QuickNote to allow for resizing of the content area

---

src/app/pages/design/iconography/Iconography.html

fix(wrong link): Fix the link to Bullhorn-Glyphicons

---

src/platform/elements/table/Table.scss

The condition occurs on some laptop screens when full-screening in
Chome on Windows 10.

Removed double scroll bar from table container in rare condition

---

src/platform/utils/app-bridge/AppBridge.ts

Appbridge register needs to let user-define windowName so that if the endpoint redirects it can still send AppBridge calls.

fix(AppBridge): Handling of WindowName was erroneous in register events

---

src/platform/elements/picker/extras/entity-picker-results/EntityPickerResults.ts

Use owner name in EntityPickerResults

Use owner name in EntityPickerResults

---

package.json
src/app/pages/elements/value/ValueDemo.ts
src/app/pages/elements/value/templates/EntityListDemo.html
src/platform/elements/value/EntityList.ts
src/platform/elements/value/Value.module.ts
src/platform/elements/value/Value.ts
src/platform/elements/value/Values.scss

* BH-54679 porting over EntityList
* BH-54679 missing imports and exports
* BH-54679 adding entity list module
* BH-54679 moving element into value directory
* BH-54679 adding entityList.ts file
* BH-54679 reverting cli version back and adding entity lists to value demo
* BH-54679 hard-coding cli version
* BH-54679 adding entity colored dot to entity list in value
* BH-54679 only make linkable if openLink method exists, and taking out novo business logic
* BH-54679 returning isLinkable for entityList if openLink function exists

BH-54679 Adding entity list to value renderer (#660)

---

src/platform/elements/value/Render.ts
src/platform/elements/value/Value.spec.ts
src/platform/elements/value/Value.ts

Added a case for html/text area fields display. The css class is used in mobile to add custom styles
Also added a flag to strip out the html
Novo will not be affected and is being tested

feat(value) displaying html fields for mobile

---

src/app/pages/elements/form/FormDemo.ts
src/app/pages/elements/form/templates/FileInputControls.html
src/platform/elements/form/Control.ts
src/platform/elements/form/Form.scss
src/platform/elements/form/controls/BaseControl.ts
src/platform/elements/form/extras/file/FileInput.scss
src/platform/elements/form/extras/file/FileInput.spec.ts
src/platform/elements/form/extras/file/FileInput.ts

- To support BBO NOVO attachments workflow.
- Add edit button as an option for multipleFileControl.
- Support custom defined actions for edit, save, delete buttons. 
- Add support for file link & description

f/multiFileControl - add edit btn

---

src/platform/elements/table/Table.ts

Fixes a bug where detail row is short by a cell because the checkbox column is not being accounted for in determining the row's column span. No new demos were added.

NovoTable - Allowing for an extra colspan in row detail if checkboxes are a visible column

---

src/platform/elements/form/extras/address/Address.ts

Add the ability to populate an address that does not have a country.

fix(addresss): Allow address to be populated without a country supplied

---

src/app/pages/elements/form/FormDemo.ts
src/app/pages/elements/form/templates/AddressControl.html
src/platform/elements/form/Control.ts
src/platform/elements/form/extras/address/Address.spec.ts
src/platform/elements/form/extras/address/Address.ts
src/platform/index.ts
src/platform/services/novo-label-service.ts
src/platform/utils/form-utils/FormUtils.ts

- address subfield labels will b e configurable by providing address a `config` input
- config will be of the following format - 
```
config  = {
address1: {
label: 'Address'
},
address2: {
label: 'Address line 2'
},
country:{
label: 'Country'
},
zip: {
label: 'Zip Code'
},
state: {
label: 'State'
},
}
```
- All keys are optional, defaults are retrieved from the labels service
- Config for each subfield will be enhanced in the future to allow properties like "required" or "hidden" for the ability to require or hide sub-fields.

feat(address) - address subfield labels are configurable

---

src/app/pages/elements/form/FormDemo.ts
src/app/pages/elements/form/MockMeta.ts
src/platform/elements/form/Control.ts
src/platform/elements/form/DynamicForm.ts
src/platform/elements/form/Form.scss
src/platform/elements/form/FormValidators.spec.ts
src/platform/elements/form/FormValidators.ts
src/platform/elements/form/controls/BaseControl.ts
src/platform/elements/form/extras/address/Address.scss
src/platform/elements/form/extras/address/Address.spec.ts
src/platform/elements/form/extras/address/Address.ts
src/platform/elements/form/extras/checkbox/Checkbox.ts
src/platform/utils/form-utils/FormUtils.ts

-  Users can configure address subfields to be required  
- novo-address as a control can no longer be "required" if novo-address control is required, that will translate to all of the subfields being required
Example configuration - 
```
config =  {
address1: {
label: 'Address Line 1',
required: true
},
address2: {
label: 'Address Line 2',
required: true
},
state: {
label: 'State',
required: true
},
country: {
label: 'Country',
required: true
},
city: {
label: 'City',
required: true
},
zip: {
label: 'Zipcode',
required: true
}
}
```
Alternatively, a required flag will imply that all subfields are required - 
```
config = {
required: true
}
```
`config` is a configurable property of `novo-address`
* Vertical Form
* Horizontal Form with some subfields checked
* Horizontal Form with only 1 …

feat(address) - allow address subfields to be required via configuration

---

src/platform/elements/simple-table/cell-header.ts

Added the changes that were made to the datatable filterData method in order to fix the custom date range filter on the simple table

fix(simple-table): fixing the custom date range filter

---

src/platform/elements/simple-table/cell-header.ts

… filter
When updating the simple table for the custom date range I missed the logic that keeps the menu from disappearing when switching to/from the calendar picker

fix(simple-table): fixing custom range toggling

---

src/platform/elements/date-picker/DatePickerInput.ts

If allow invalid date was on without changing the date format the full date string is displayed
n/a

fix allowInvalidDate with standard date formats

---

src/platform/elements/form/Control.ts

This fixes a bug where the count shows for all textbox fields (including number fields)

fix(form-control) maxlength won't show for all fields in focus

---

src/platform/elements/value/Value.spec.ts
src/platform/elements/value/Value.ts

Opportunity entities will now render as internal links, like Candidate, Contact, etc.

Added Opportunity to the list of entities rendered as internal links

---

src/app/pages/elements/field-interactions/FieldInteractionsDemo.ts
src/app/pages/elements/field-interactions/templates/Tooltip.html
src/platform/elements/form/FieldInteractionApi.ts

Added setTooltip method to be compatible with BBO Field Interactions.

add set tooltip method to field interactions

---

src/platform/elements/form/FieldInteractionApi.ts
src/platform/elements/form/FormInterfaces.ts
src/platform/elements/form/NovoFormControl.ts

Emit if there are changes to the NovoFormControl via Field Interactions

Add Emitter for NovoFormControl Changes

---

src/platform/elements/dropdown/Dropdown.ts
src/platform/elements/tiles/Tiles.ts

Changed slide from swallowing every event to only the ones that we care about and allowed radios to default to a unique name if one isn't given.

fix(dropdownAndTile): Changes to improve accessibility

---

src/platform/elements/form/FieldInteractionApi.ts

Fixes minor issue to new functionality introduced in [PR 719](https://github.com/bullhorn/novo-elements/pull/719). `readOnly` should be `true` when a control is disabled and `false` when a control is enabled.

fix(FieldInteractionAPI): Fix faulty logic for enable/disable events

---

src/platform/elements/tiles/Tiles.scss

Added white background so that the tiles will always have a white background on non-white pages.

style(tiles): Added white background to tiles

---

src/platform/elements/value/EntityList.ts

Meta type was being overwritten unnecessarily when displaying the entity list, which was causing the type to be misidentified when reloading the list after changes.

fix(EntityList): prevent meta type from being overwritten

---

src/platform/elements/value/EntityList.ts

Use local variable for meta so that meta.type can be edited without changing the underlying object.

fix(EntityList): prevent meta type from being overwritten - fix

---

src/platform/elements/button/Button.scss

Tweaking button styling to center text/icon inside of button

---

src/platform/elements/form/Control.spec.ts
src/platform/elements/form/Control.ts
src/platform/elements/form/Form.scss

The autosizing textarea was shrinking by one pixel on every input event, depending on content/initial height of the textarea. The method of resizing is now `resize to smallest valid input height to calculate the appropriate scrollHeight`. The heights previously set in the directive have also been moved to min/max heights in CSS. Also removed some padding to better replicate the look of a one line text input.
The `compile` script does not seem to exist
Old behavior:
New behavior:

fix(NovoAutoSize): Fix shrinking behavior of autosizing textareas

---

src/platform/elements/button/Button.scss

This reverts commit dec11f47cc0adf80eb6641d36f2dc248938f1524.
Reverting recent changes around button icon text centering as it caused issues in Novo

Revert "style(button): Fix button centering"

---

src/app/pages/elements/field-interactions/FieldInteractionsDemo.ts
src/platform/elements/form/FieldInteractionApi.ts

Add duplicate check to FieldInteractions addStaticOption method

fix(FieldInteractionAPI): Add duplicate check to addStaticOption method

---

src/platform/elements/select/Select.module.ts
src/platform/elements/select/Select.spec.ts
src/platform/elements/select/Select.ts

Made various updates to the accessibility of the select component. See video posted below for an demo of how accessibility now is for the select component.

(select): Updates to select accessibility

---

src/platform/elements/radio/Radio.scss

In a novo-dynamic-form the 0 opacity input inside of novo-radio components had a width that was 100% of the width of the novo-control-input-container. Change styling on novo-radio to be position relative so that the input inside has the correct width from the novo-radio component.
There is not `compile` script.

fix(NovoRadio): change novo-radio style so that hidden input has correct width

---

src/platform/elements/picker/Picker.ts

Make clicking on a picker result behave the same as pressing enter on a result (don't re-open the entire list of results when something is selected)

Novo picker changes to click behavior

---

src/app/pages/elements/form/FormDemo.ts
src/platform/elements/form/Control.ts

Added tooltip capability to textarea (previously not supported in just hint.css, needed wrapper)

Add tooltip capability to textarea and update demo

---

src/platform/elements/date-picker/DatePickerInput.ts

blur event bug: when month is selected in a date-picker, picker focuses out of the picker.

fix: date-picker-month-select

---

src/platform/elements/form/Control.ts

grouped control didn't updates after templates were instantiated because of the ChangeDection onPush strategy. Explicitly pushing changes so that it does update.

fix(form-control-group) - change detection to fix control group display

---

src/platform/elements/data-table/data-table.component.scss

custom range datepicker width is not responsive on the data-table

fix-data-table-dropdown-styling

---

src/platform/elements/form/Control.ts

Marking change for check instead of detecting changes

fix(form-control) better change detection

---

src/platform/elements/data-table/cell-headers/data-table-header-cell.component.ts
src/platform/elements/data-table/data-table.component.scss
src/platform/elements/simple-table/cell-header.ts
src/platform/elements/table/Table.scss
src/platform/elements/table/Table.ts

update calendar class so that its spelled correctly

fix(Table): spelling fix - calender should be calendar

---

src/platform/elements/form/Control.ts

Using condensed form controls (for example, the novo-control-group component), the space allocated for the required check/cross is removed when the control is set as readonly.  When toggling a required control's readonly state, the left hand side of the control will jump as it adds the required icon.
This brings the original behavior back to the control that was removed in in #696. I spoke with @amrutha-rajiv, and this change doesn't seem negatively affect the changes from #696.
Before:
After:

fix(novo-control) leave padding for required icon in condensed controls

---

src/platform/elements/date-picker/DatePickerInput.spec.ts
src/platform/elements/date-picker/DatePickerInput.ts

Allows users to type dates in the dd/mm/yyyy format

format date to proper locale when manually entering date

---

package.json
src/app/pages/elements/tiles/TilesDemo.ts
src/app/pages/elements/tiles/templates/TilesDemo.html
src/platform/elements/tiles/Tiles.spec.ts
src/platform/elements/tiles/Tiles.ts

Allowing for event emitters when selected tiles are clicked. This enables consumers of Novo Elements to key off of any clicks that happen in the tiles element.

feat(tiles): Added event emitter for when selected tiles are clicked

---

src/platform/elements/picker/extras/entity-picker-results/EntityPickerResults.ts

Added two missing fields (occupation and primary department) to the internal picker dropdown results.

Change to add dept and title fields to the internal picker

---

src/app/pages/elements/form/FormDemo.ts
src/platform/elements/form/NovoFormControl.ts
src/platform/utils/form-utils/FormUtils.ts

The checkboxLabel property on checkboxes seemed to have been removed.   This is adding it back

add back in the checkboxLabel property to control config

---

src/platform/elements/form/FieldInteractionApi.ts

fix(FieldInteractionAPI) - only copying over the resultsTemplate from existing config

---

src/platform/elements/value/Value.ts

Changed regex in Value for html fields that strip html to ignore the style tags.

fix(value): Changed html field displays to not strip style tags

---

src/app/pages/elements/data-table/DataTableDemo.ts
src/app/pages/elements/data-table/templates/basic-remote.html
src/platform/elements/data-table/data-table.component.scss
src/platform/elements/data-table/interfaces.ts
src/platform/elements/data-table/pagination/data-table-pagination.component.ts
src/platform/elements/header/Header.scss

Handle overflow of header title and allow for spacing with the data-table pagination
Data table prev/next can now show up on the right side of the table if you want (they have their own theme)
If a header title overflows, then correctly hide it

Handle overflow of header title and allow for spacing with the data-table pagination

---

src/platform/elements/ckeditor/CKEditor.spec.ts
src/platform/elements/ckeditor/CKEditor.ts

Allowing for more styles than just the default to be used when pasting html content into CKEditor. Whether user copy/paste or programmatic setting of the html content, this allows for less stripping of styles by CKEditor. Broken up into 2 commits - the first is the prettier automatic formatting of the file. The second commit is the 1 line change.

feat(editor): Allow pasting of html content with styles into the editor

---

src/platform/elements/chips/Chips.scss
src/platform/elements/picker/Picker.scss

Height of picker results is slightly less than half of the screen
height so that they will always be able to be positioned above/below
and still fit on screen. The static height of 450px was sometimes too
tall for the window height.

fix(Picker): Make picker results dynamic height so they fit on screen

---

src/platform/elements/chips/RowChips.ts

Override default closeOnSelect to true in row-chips component.
Set the closeOnSelect to true as default for the NovoRowChipsElement.

fix(NovoRowChipsElement) set picker input closeOnSelect default to true

---

src/platform/elements/ckeditor/CKEditor.spec.ts
src/platform/elements/ckeditor/CKEditor.ts

add calibri as a font to ckeditor

add calibri font to ckeditor

---

src/app/pages/elements/chips/ChipsDemo.ts
src/platform/elements/chips/Chips.scss
src/platform/elements/chips/Chips.ts
src/platform/utils/form-utils/FormUtils.ts

Adjust NovoRowChipsElement styling to be more consistent with other novo-elements disabled fields. Fix typo on Chips demo page.
Update Chips styling so that selectors `chip`, `novo-chip`, `chips` and `novo-chips` have the same styling applied.
Update Chips template to use `novo-chip` tag rather than `chip` tag

fix(NovoRowChipsElement) adjust NovoRowChipsElement styling for consistency

---

src/platform/elements/chips/Chips.ts

change the mouseover event to select on `mouseenter` and deselect on `mouseleave` events so that the chip outline and preview will hide on `mouseleave`.

fix(NovoChipsElement) change chip hover functionality to deselect on mouseleave event

---

src/app/pages/elements/tip-well/TipWellDemo.ts
src/app/pages/elements/tip-well/templates/TipWellHtmlDemo.html
src/platform/elements/tip-well/TipWell.ts

I added the ability to use HTML in a tipwell for more structured information.

add ability to put HTML in a tipwell

---

src/platform/elements/form/NovoFormControl.ts

add back in removed masked options accidentally removed in #810

---

src/platform/elements/chips/Chips.scss

Remove bottom border on picker inside of chips element and add a bottom border to entire chips element.

fix(Chips): Chips disabled state styling fix

---

src/platform/elements/card/Card.spec.ts
src/platform/elements/form/ControlTemplates.ts
src/platform/elements/form/NovoFormControl.ts
src/platform/elements/form/controls/BaseControl.ts
src/platform/elements/table/Table.spec.ts
src/platform/elements/tooltip/Tooltip.directive.ts
src/platform/elements/tooltip/Tooltip.spec.ts

Interim change to restore full default functionality of tooltips until more research can be done in auto-positioning tooltips in novo.

add default option for static tooltips

---

src/platform/elements/form/controls/BaseControl.spec.ts
src/platform/elements/form/controls/BaseControl.ts
src/platform/elements/form/extras/file/FileInput.spec.ts
src/platform/elements/form/extras/file/FileInput.ts

Add a flag in FileInput to hide the "remove" button.
Default the flag to true to maintain current default behavior.
Add the flag property to all relevant classes and interfaces.

WIP: feat(FileInput,BaseControl): Add flag to hide remove button

---

projects/novo-elements/src/elements/data-table/data-table.component.ts

This fixes the demo for data-tables

stop execution if there are not any re-sizable columns

---

projects/novo-elements/src/elements/data-table/data-table.component.ts

Update data table code based on feedback and add a prettier ignore comment so prettier stops attempting to refactor against the linter

chore(data-table): refactor only execute code if there are any resizable columns

---

.gitignore
package-lock.json
projects/novo-elements/src/elements/form/Control.spec.ts
projects/novo-elements/src/elements/form/Control.ts

Added support for non-english locales to use commas and/or periods when entering a decimal separator character. This is required because some locales, like `fr_CA` (French Canadian) may need to switch between comma and period by switching between a French and English browser locale.

feat(Currency): Allow Comma or Period as decimal for non-English users

---

projects/novo-elements/src/elements/picker/Picker.spec.ts
projects/novo-elements/src/elements/picker/Picker.ts

Add support for a picker to display the title property of an object if it is present.

Feat(Picker): Allow Picker to display title property as label.

---

projects/novo-elements/src/elements/chips/Chips.scss
projects/novo-elements/src/elements/chips/Chips.spec.ts
projects/novo-elements/src/elements/chips/Chips.ts
projects/novo-elements/src/elements/chips/RowChips.ts

Added param for user to specify an empty message for when no selections have been made and the input is disabled (the select input will be shown when enabled).
Also added value formatter support for deleting a row chip. Missed from [#845](https://github.com/bullhorn/novo-elements/pull/845)

feat(RowChips): Add empty state message for disabled RowChips and RowChip delete functionality

---

projects/novo-elements/src/elements/form/ControlTemplates.ts
projects/novo-elements/src/elements/form/FieldInteractionApi.ts
projects/novo-elements/src/elements/form/extras/address/Address.spec.ts
projects/novo-elements/src/elements/form/extras/address/Address.ts

Fix address disabled state and promptUser data-automation-id
Fix State picker disabled state when readOnly changes
Update to control for disabled state on Address component via country selection and readOnly binding

fix(address): update address disabled state

---

package.json

Fix an Angular compiler error with Typescript > 3.2.0

fix(package.json): Lock Typescript dependency to < 3.2.0 due to angular compiler issue

---

projects/novo-elements/src/elements/form/FormInterfaces.ts
projects/novo-elements/src/elements/form/controls/BaseControl.ts
projects/novo-elements/src/utils/form-utils/FormUtils.spec.ts
projects/novo-elements/src/utils/form-utils/FormUtils.ts

Update FormUtils to respect the "Allow Multiple" flag when it's configured to false for fields with to-many associations (by selecting type "picker"/"entitypicker" instead of "chips"/"entitychips").

fix(FormUtils): Respect Allow Multiple false for to-many association fields

---

src/platform/elements/form/FormInterfaces.ts
src/platform/elements/form/controls/BaseControl.ts
src/platform/utils/form-utils/FormUtils.spec.ts
src/platform/utils/form-utils/FormUtils.ts

Porting changes from #874 into 2.x.x support branch

Port changes for preventing multiple on TO_MANY fields to support branch

---

tools/examples-routes.ts

fixes #865
On Windows, the build doesn't generate routes correctly.  This small change is to help generate them as expected.

chore(build): split path by forwardslashes instead of backslashes when generating routes

---

projects/novo-elements/src/elements/chips/Chips.ts

Adding a div to wrap the novo chips on multi-pickers for the purpose of limiting the maximum height in Novo.
No style changes in this branch.

feat(picker): Added maximum height to picker chips form control

---

projects/novo-elements/src/elements/button/Button.ts

Fixed issue where we were setting an empty icon (bhi-undefined) on button causing it to look bad.

fix(button): Only set icon on button if exists

---

projects/novo-elements/src/elements/picker/extras/entity-picker-results/EntityPickerResults.spec.ts
projects/novo-elements/src/elements/picker/extras/entity-picker-results/EntityPickerResults.ts

Add ID for Job, Opportunity, and Placement picker results

feat(EntityPickerResults): Update Job, Placement, and Opportunity results to include ID

---

projects/novo-elements/src/elements/chips/Chips.ts

Added back a container Div that was removed by a later commit

feat(picker): Added container div to picker chips form control

---

projects/novo-elements/src/utils/form-utils/FormUtils.ts

Previously, entity pickers by ID did not return full entity picker results but entity pickers using text did. UX wanted both to show the entity results instead of the simple one line of text only results. Old behavior is on the left, new behavior is on the right.

feat(Picker): Changing all entity id pickers to use full entity results

---

projects/novo-elements/src/utils/form-utils/FormUtils.spec.ts
projects/novo-elements/src/utils/form-utils/FormUtils.ts

Add function to remove controls from form group.

feat(formUtils): add remove controls function to form utils

---

src/app/pages/elements/value/ValueDemo.ts
src/app/pages/elements/value/templates/MultiOptionDemo.html
src/platform/elements/value/Render.spec.ts
src/platform/elements/value/Render.ts
src/platform/elements/value/SimpleValueDemo.html

Fix(RenderPipe) - allow options() to handle multiple values passed in an array

---

projects/novo-elements/src/utils/Helpers.spec.ts
projects/novo-elements/src/utils/Helpers.ts

I just extended the logic of `isNumber` to allow for floats as well.

feat(helpers): Extended the logic of isNumber

---

src/platform/elements/value/Render.spec.ts
src/platform/elements/value/Render.ts

Added support for SecondaryAddress and Billing Address display for Vertical Layout

Fix(Render) - Address field Display for mobile

---

projects/novo-elements/src/elements/value/Render.spec.ts
projects/novo-elements/src/elements/value/Render.ts

Added support for SecondaryAddress and Billing Address display for Vertical Layout

Fix(Render) - SecondaryAddress and Billing Address render for verticl

---

demo/assets/stackblitz/index.html
demo/assets/stackblitz/main.ts
package-lock.json
projects/novo-examples/src/_shared/stackblitz/stackblitz-writer.ts

Fix the issues found with stackblitz file generation.
- N/A Run `Novo Automation`
- N/A Run `BBO Automation`

chore(demo) fix stackblitz file generation

---

demo/assets/stackblitz/.angular-cli.json
projects/novo-examples/src/_shared/stackblitz/stackblitz-writer.ts

Follow on from #928 
Github pages doesn't seem to agree with the .angular-cli.json file.  I removed dependency of the json file and added it via javascript. removes the requirement of server side requests

fix(demo): remove angular-cli json file and add it in typescript

---

projects/novo-elements/src/utils/app-bridge/AppBridge.ts

Fixing the AppBridge registration call to send back reject() when it fails, instead of the same response as when it succeeds. Also, adding type for preview slideout (Novo Only) and fixing the response of the DevAppBridge to not wrap the rest return in a second data object.

feat(AppBridge): App Bridge Fixes

---

projects/novo-elements/src/elements/select/Select.ts
projects/novo-elements/src/utils/form-utils/FormUtils.spec.ts
projects/novo-elements/src/utils/form-utils/FormUtils.ts

Updating FormUtils to allow support for workflow options.

feat(FormUtils): Add support for workflow options

---

projects/novo-elements/src/utils/form-utils/FormUtils.ts

Novo/Novo-elements needs to start honoring both systemRequired and *required *when handling required fields in forms.

BH-61013 Novo: Using systemRequired in meta

---

projects/novo-elements/src/elements/picker/Picker.ts
projects/novo-elements/src/elements/picker/extras/checklist-picker-results/ChecklistPickerResults.ts
projects/novo-elements/src/elements/picker/extras/entity-picker-results/EntityPickerResults.ts
projects/novo-elements/src/elements/picker/extras/picker-results/PickerResults.ts
projects/novo-elements/src/elements/picker/extras/skills-picker-results/SkillsSpecialtyPickerResults.ts
projects/novo-elements/src/services/novo-label-service.spec.ts
projects/novo-elements/src/services/novo-label-service.ts

I changed the default text on picker overlays so that users are not confused by the message, "No results to display..." as they focus on the field.

Update the default text on Picker field overlays

---

projects/novo-elements/src/elements/form/ControlGroup.html
projects/novo-elements/src/elements/form/ControlGroup.scss
projects/novo-elements/src/elements/form/ControlGroup.spec.ts
projects/novo-elements/src/elements/form/ControlGroup.ts
projects/novo-elements/src/elements/form/controls/BaseControl.ts
projects/novo-elements/src/utils/Helpers.spec.ts
projects/novo-elements/src/utils/Helpers.ts

- base-control: copying over subtype and type
- resetting edit/remove checks on every add and remove of controls
- fixed styles for required columns
- added the control key as a class to the label column

fix(control-group) style & input type fixes

---

projects/novo-elements/src/utils/form-utils/FormUtils.spec.ts
projects/novo-elements/src/utils/form-utils/FormUtils.ts

get the minimum start date of an effective date entity (EDE Locations, Billing Profiles or Invoice Terms) from data or meta.

Bh 61033 get start date from data or meta

---

projects/novo-elements/src/elements/chips/Chips.scss
projects/novo-elements/src/elements/popover/PopOver.scss
projects/novo-elements/src/elements/toast/Toast.scss

Changed `start` to `flex-start` in 3 places to resolve mixed support warnings in mobile builds.

fixing mixed support warning in mobile builds

---

projects/novo-elements/src/elements/form/DynamicForm.ts
projects/novo-elements/src/elements/form/FieldInteractionApi.ts
projects/novo-elements/src/elements/form/NovoFormControl.ts

Fields can be hidden in a form because an other fields. Those hidden fields should stay hidden if the user go back and forth in the error page.
- [*] Any related demos were added and `npm start` and `npm run build` still works
- [*] `npm run lint` passes
- [*] `npm test` passes and code coverage is increased
- [*] `npm run build` still works

BH-61236 field hidden when error message

---

projects/novo-elements/src/utils/form-utils/FormUtils.ts

fix(form-utils) passing through layoutOptions

---

projects/novo-elements/src/elements/data-table/data-table.component.scss

Fixing an issue from #947 where an outer element made empty state links unclickable.
Empty state on data-table should be clickable for elements such as buttons or links.

fix(data-table): novo-data-table empty state is unclickable

---

projects/novo-elements/src/utils/form-utils/FormUtils.ts

A string date is not at a local GMT zone so it can show a different date on a novo date picker.
For example '2019-06-24' will be seen as '2019-06-24' in GMT 0 so '2019-06-23' on the Est coast.

date local format

---

projects/novo-elements/src/utils/form-utils/FormUtils.ts

Fields can be marked as hidden in meta but system required fields should show regardless of this. This change allows for system required fields to show regardless of the hidden flag.

feat(field-control): system required fields should show

---

projects/novo-elements/src/index.ts

instead of this in Novo
`import { NovoDynamicFormElement } from 'novo-elements/elements/form/DynamicForm';
`
we will be able to do
`import { NovoDynamicFormElement } from 'novo-elements';
`

cleaner import in novo

---

projects/chomsky/src/utils/chomsky.ts
projects/chomsky/src/utils/formats.spec.ts
projects/chomsky/src/utils/formats.ts
projects/novo-elements/src/elements/time-picker/TimePickerInput.ts
projects/novo-elements/src/services/novo-label-service.ts

The change I make are returning formatted time results in parts for consistency between locale formats

return time in parts for assembly

---

projects/novo-elements/src/elements/form/ControlGroup.html
projects/novo-elements/src/elements/form/ControlGroup.ts

Propagate the onChange() of a novo-control to the novo-control-group

onChange for ControlGroup

---

projects/novo-elements/src/elements/form/FieldInteractionApi.ts
projects/novo-elements/src/elements/form/FieldInteractionApiTypes.ts

feat(picker): preserve empty results message on config for pickers

---

projects/novo-elements/src/elements/data-table/data-table.source.ts

The data-table has a `total` property which was always set as the count of rows the first time data is returned for the table. This is not a safe assumption since because of things like sticky filters, the first time data is returned for a list may not be all of the data. In the case that the first time table data was returned was "0", data-tables were assuming there were no records.
If data-table gets more records than the `total` property is set to, the `total` property should be updated to the number of records received. This MR is also refactoring how and when the total and the `loading` property is being set, in order to avoid the `totallyEmpty` state pages from appearing during loading.
Old behavior:
New behavior:

Fix issue where novo data tables weren't showing results if they start filtered

---

projects/novo-elements/src/elements/form/Control.spec.ts
projects/novo-elements/src/elements/form/Control.ts

Character counts for fields that use them should only ever display if the field is focused.
This small change in logic ensures that the focus state is checked before anything else.

BH-61571: Hide char count for field if not focused

---

package-lock.json
projects/novo-elements/src/elements/data-table/cell-headers/data-table-header-cell.component.ts

We shouldn't ever listen to global keydown events as processing those events are extremely slow.

fix(data-table): Reduce scope of capturing keydown events

---

projects/novo-elements/src/elements/form/Control.spec.ts
projects/novo-elements/src/elements/form/Control.ts
projects/novo-elements/src/elements/picker/extras/base-picker-results/BasePickerResults.spec.ts
projects/novo-elements/src/elements/picker/extras/base-picker-results/BasePickerResults.ts

Allow Picker results to accept a custom preselected function for determining whether a result has already been selected.

Accept Custom Preselected Config

---

projects/novo-elements/src/elements/form/controls/BaseControl.spec.ts
projects/novo-elements/src/elements/form/controls/BaseControl.ts

Fixed bug where some fields don't calculate dirty flag properly, specifically booleans set to false, and integers set to 0

Change how dirty flag is being calculated

---

projects/novo-elements/src/elements/data-table/data-table.component.scss
projects/novo-elements/src/elements/data-table/data-table.component.ts
projects/novo-elements/src/elements/data-table/rows/data-table-header-row.component.ts

The column headers bounce when there are a large number of records within the data set (items per page = 500) that is being scrolled. The problem is related to it being triggered from the scroll bar scroll event. This changeset changes the approach to CSS instead of the listener.

feat(data-table): modified how fixed header is applied to column headers

---

projects/novo-elements/src/elements/table/extras/date-cell/DateCell.ts

Dates throughout the rest of the app use NovoLabelService to format dates. If an app is extending NovoLabelService to change how dates are displayed, it currently doesn't affect date cells in tables.

Use novo label service instead of built in angular date pipe

---

projects/novo-elements/src/elements/form/extras/address/Address.spec.ts
projects/novo-elements/src/elements/form/extras/address/Address.ts
projects/novo-examples/src/form-controls/form/address-control/address-control-example.ts

Fixed the countryID to not be set to the countryName in default config
Fixes issue: #988
Duplicate of https://github.com/bullhorn/novo-elements/pull/1010. Rebase caused a lot of false file changes, so cherry-picked changes over on to new feature branch.

country name fix

---

projects/novo-elements/src/elements/form/FieldInteractionApi.spec.ts
projects/novo-elements/src/elements/form/FieldInteractionApi.ts
projects/novo-elements/src/elements/form/FieldInteractionApiTypes.ts

Adding a page parameter to the existing optionsPromise field interaction for custom picker options in order to enable optionsPromise to implement paging when constructing a third party service for options generation.

feat(Picker): Enabling custom optionsPromise to use infinite scroll

---

projects/novo-elements/src/elements/data-table/data-table.pipes.spec.ts
projects/novo-elements/src/elements/data-table/data-table.pipes.ts

This will make sure the hotfix applied in 3.16.1 will also publish to the new version of novo in the 3.17.0 release.

BH-64754: Add for new novo version

---

projects/novo-examples/src/components/tabbed-group-picker/tabbed-group-picker-basic/tabbed-group-picker-basic-example.ts
projects/novo-examples/src/components/tabbed-group-picker/tabbed-group-picker-big-groups-example/tabbed-group-picker-big-groups-example.ts
projects/novo-examples/src/components/tabbed-group-picker/tabbed-group-picker-groups-example/tabbed-group-picker-groups-example.ts
projects/novo-examples/src/components/tabbed-group-picker/tabbed-group-picker-quick-select-example/tabbed-group-picker-quick-select-example.ts

novo-examples should refer to novo-elements using tsconfig>paths and not using 'dist/novo-elements' directly.

fix examples import

---

projects/novo-elements/src/elements/data-table/data-table.source.ts

Given that a user 1) filters a novo-data-table that has sticky filters so that there are no results, 2) navigates away, and 3) returns (so that the filter with empty results is applied on load)
When the user clears the filter so that non-empty data is returned
Then the table reloads with the expected results.
Previous undesired behavior: the table loads with an empty state message.

Fix data table sticky filter empty state bug

---

projects/novo-elements/src/elements/ckeditor/CKEditor.spec.ts
projects/novo-elements/src/elements/ckeditor/CKEditor.ts
projects/novo-elements/src/elements/form/NovoFormControl.ts
projects/novo-elements/src/elements/form/controls/BaseControl.ts

There is an existing bug with the CKEditor initialization within dynamic forms where the creation logic does not properly instantiate the editor component. 
CURRENT DYNAMIC FORM DEMO (Broken)
DYNAMIC FORM DEMO AFTER (Fixed)

fix(Editor): Fix the creation logic of CKEditor element within dynamic forms

---

projects/novo-elements/src/utils/form-utils/FormUtils.ts

This reverts https://github.com/bullhorn/novo-elements/commit/f350cd3ebc7beae455b5ba36f3e96c3e70ab5161 .

fix(FormUtils): Don't allow distributionLists field to have controls

---

projects/novo-elements/src/elements/form/DynamicForm.ts
projects/novo-elements/src/elements/form/FieldInteractionApi.spec.ts
projects/novo-elements/src/elements/form/FieldInteractionApi.ts
projects/novo-elements/src/elements/form/Form.scss
projects/novo-elements/src/elements/form/FormInterfaces.ts
projects/novo-elements/src/utils/form-utils/FormUtils.ts

Making fieldsets hidable through field interactions

feat(fieldset): added key property to fieldset and added FI for fieldset header

---

projects/novo-elements/src/elements/date-time-picker/DateTimePickerInput.ts

This allows datetime pickers to have their values persisted when only the date portion of the field has been filled out. The time part will default to 12pm whenever a date is selected and the time is null.

Half null date time

---

projects/novo-elements/src/utils/form-utils/FormUtils.ts

This PR consists of a few small changes for making embedded custom objects work. These are specifically concerning section headers. With things as they were initially, section headers were rendering as editable text fields and with a generic label rather than the label they actually have configured. This corrects these problems coming through from the meta for embedded custom objects

Epic embedded co

---

projects/novo-elements/src/elements/date-picker/DatePickerInput.ts
projects/novo-elements/src/elements/date-time-picker/DateTimePicker.ts
projects/novo-elements/src/elements/date-time-picker/DateTimePickerInput.ts
projects/novo-elements/src/elements/form/ControlTemplates.ts
projects/novo-elements/src/elements/form/NovoFormControl.ts
projects/novo-elements/src/elements/form/controls/BaseControl.ts
projects/novo-elements/src/utils/form-utils/FormUtils.ts

We are updating the Date and DateTime controls to allow a custom week start day to be specified via a setting

Date Control Week Start Day

---

projects/novo-elements/src/elements/form/extras/file/extras/file/File.spec.ts
projects/novo-elements/src/elements/form/extras/file/extras/file/File.ts

feat(novo-file): Do not resolve promise for read until read is finished

---

projects/novo-elements/src/elements/form/ControlGroup.ts

markForCheck on resetAddRemove

fix(angular) markForCheck on resetAddRemove

---

projects/novo-elements/src/elements/tiles/Tiles.scss

Updating css on tiles to fix height and font weight
- [ n/a] Run `Novo Automation`
- [ n/a] Run `BBO Automation`

updating tile css again

---

projects/novo-elements/src/elements/dropdown/Dropdown.ts

subscribing to changes on QueryList so that we can reset/reload the `items` property dynamically, since we now have a component that can actively filter dropdown results.
also resetting `activeIndex` when we do this, since we use that to access `items` array elements and will throw errors if we get out of range with shorter, filtered items lists.
QueryList also unsubscribes itself on destroy:
https://github.com/angular/angular/blob/7d137d7f8872a6fba72668e32f9baf2c5dcfc48b/packages/core/src/linker/query_list.ts#L115

BH-66970 refresh dropdown list array when it changes

---

projects/novo-elements/src/elements/form/ControlGroup.html
projects/novo-elements/src/elements/form/ControlGroup.ts

Added ability to have a custom column header template for horizontal control groups.

feat(controGroup): added custom column header template

---

projects/novo-elements/src/elements/chips/Chips.spec.ts
projects/novo-elements/src/elements/chips/Chips.ts

Modified value to return just the id when object is passed

feat(chips): modified value to return just the id when object is passed

---

projects/novo-elements/src/elements/chips/Chips.scss

Fix for #1121 
Added styles to `.novo-chip-container` that flexes the chip components, allowing them to fall horizontally instead of stacking vertically
* There are failures, but these are inherited from failures in `master`. This is a simple style update.

Fix for #1121 - flex the chips horizontally

---

projects/novo-elements/src/elements/data-table/data-table-clear-button.component.ts

Prevents this bad pop-up behavior from happening in situations where the Clear Button is at the far right, and the browser window is full screen.

fix(Clear Button): Prevent data table clear dropdown from popping up instead of down

---

.travis.yml
projects/novo-elements/src/elements/form/Control.spec.ts

use node 14 instead of node 10
https://nodejs.org/en/about/releases/

chore(build): use node 14 instead of node 10

---

projects/novo-elements/src/elements/date-picker/DatePickerInput.ts

Manual entry was including the current time in the datepicker causing issues for locations operating in multiple timezones. Stripping time from the datepicker to match the behavior when selecting from the calendar,

Date picker fix

---

projects/novo-elements/src/elements/picker/extras/base-picker-results/BasePickerResults.ts

Adding ability to pass in "selected" items to BasePickerResults to disable the option in pickers without them appearing selected in the form

WIP: BH-68520 passing config.selected to BasePickerResults preselected function

---

projects/novo-elements/src/elements/data-table/ListInteractionTypes.ts
projects/novo-elements/src/elements/data-table/cell-headers/data-table-header-cell.component.ts
projects/novo-elements/src/elements/data-table/data-table.component.ts

Adds methods that enable novo data tables list interactions.

Changes for list interactions to be enabled

---

projects/novo-elements/src/index.ts
projects/novo-elements/src/services/novo-label-service.spec.ts
projects/novo-elements/src/services/novo-label-service.ts

feat(NovoLabelService): Add options to formatBigDecimal() to allow overrides without changing existing behavior

---

projects/novo-elements/src/elements/dropdown/Dropdown.ts
projects/novo-elements/src/elements/select/Select.ts
projects/novo-elements/tsconfig.lib.json

Added support for non-English keyboards for typeahead on dropdowns. Uses `event.key` instead of the deprecated `event.keyCode`.
Auto-scrolling to an entry with non-english characters:

BH-68882 Non-English support for dropdown searching

---

projects/novo-elements/src/elements/select/Select.ts

Normalizes `select` search strings consistently so you can search without capslock.

BH-70094 Fixed incorrect case-sensitivity in dropdown searching

---

projects/novo-elements/src/elements/date-picker/DatePickerInput.ts

Moved the change emit into an existing function already getting called on all changes, instead of calling it on blur which didn't account for all change scenarios.

feat(DatePickerInput): moving change event emit from handleBlur to dispatchOnChange

---

.github/workflows/main.yml

The snapshot is not updated when there are PRs merged to master.  Update the action to run on [PR events](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request) and [push events](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#push)

ci(actions): change events that the action is triggered off of

---

projects/novo-elements/src/elements/form/Control.ts
projects/novo-elements/src/elements/form/FieldInteractionApi.ts
projects/novo-examples/src/utils/field-interactions/fi-validation/fi-validation-example.html
projects/novo-examples/src/utils/field-interactions/fi-validation/fi-validation-example.ts
projects/novo-examples/src/utils/field-interactions/field-interactions.md

Useful to scripts when using invokeOnInit combined with change, blur, or focus.

feat(Field Interactions): Adding isInvokedOnInit to identify to field interactions whether the operation is happening on init or not

---

projects/novo-elements/src/elements/form/FieldInteractionApi.ts

Allow interactions to be passed with the meta for FieldInteractionAPI's addControl.

chore(typescript): Add interactions to FieldInteractionAPI's addControl metaForNewField properties

---

.github/workflows/releaseNovoElements.yml

Create an action that publishes Novo elements to NPM automatically.  This is run manually from the actions tab.

chore(actions): create manual action to publish novo elements 

---

projects/novo-elements/src/elements/form/Control.ts

Set percentValue to undefined rather than null

fix: bug with dot and minus symbols on percentage fields

---

projects/novo-elements/src/services/novo-label-service.ts

It says to select a category from the right to get started even though the categories are on the left.

fix(GroupedMultiPicker): correct typo in groupedMultiPicker empty state

---

projects/novo-elements/src/utils/Helpers.ts

angular 10 upgrade PR introduced a bug where we are now attempting to deep clone classes using logic that exists to deep clone functions, resulting in an exception being thrown when trying to iterate through it and copy it.

fix(Helpers): excluding classes from function deep cloning logic

---

projects/novo-elements/src/elements/data-table/data-table.component.ts
projects/novo-elements/src/elements/tooltip/Tooltip.component.ts

- Added tool tip to novo datatable cell renderers
- Made tooltip support HTML content 
- ✔️  Any related demos were added and `npm start` and `npm run build` still works
- ✔️  New demos work in `Safari`, `Chrome` and `Firefox`
- ✔️ `npm run lint` passes
- ❌   `npm test` passes : one unrelated unit test was failing, assuming it's an existing issue, will discuss with team
- ✔️  `npm run build` still works

feat(NovoTable): Adding tool tip on default cell renderers + experimental support for HTML tooltips

---

.github/workflows/main.yml
package.json
snapshot-publish

fixes #1202
This changes the snapshot build to use production configuration

chore(actions): change build process to build production

---

.github/workflows/main.yml
projects/novo-elements/src/elements/form/Control.spec.ts
projects/novo-elements/src/elements/tooltip/Tooltip.component.ts
projects/novo-elements/src/elements/tooltip/Tooltip.directive.ts
projects/novo-examples/src/utils/tooltip/tooltip-align/tooltip-align-example.css
projects/novo-examples/src/utils/tooltip/tooltip-options/tooltip-options-example.css
projects/novo-examples/src/utils/tooltip/tooltip-options/tooltip-options-example.html
projects/novo-examples/src/utils/tooltip/tooltip-placement/tooltip-placement-example.css
projects/novo-examples/src/utils/tooltip/tooltip-sizes/tooltip-sizes-example.css
projects/novo-examples/src/utils/tooltip/tooltip-toggle/tooltip-toggle-example.css
projects/novo-examples/src/utils/tooltip/tooltip-types/tooltip-types-example.css

Other minor updates:
- Fixed a broken unit test
- Cleaned up the tool tip examples as the tooltip parents were squashed together
Adding an option to allow HTML tooltips

feat(tooltip): Adding HTML support for tooltips

---

projects/novo-examples/src/_shared/stackblitz/stackblitz-writer.ts

docs(demo/stackblitz): set correct versions for stackblitz demos

---

projects/novo-elements/src/elements/button/Button.scss
projects/novo-elements/src/elements/form/ControlGroup.spec.ts
projects/novo-elements/src/elements/form/ControlGroup.ts

Added optional method for a delete button confirmation for form control groups.

feat(ControlGroup): Add optional delete button confirmation

---

projects/novo-elements/src/elements/select/Select.module.ts
projects/novo-elements/src/elements/select/Select.scss
projects/novo-elements/src/elements/select/Select.spec.ts
projects/novo-elements/src/elements/select/Select.ts
projects/novo-examples/src/form-controls/select/basic-select/basic-select-example.css
projects/novo-examples/src/form-controls/select/basic-select/basic-select-example.html
projects/novo-examples/src/form-controls/select/basic-select/basic-select-example.ts

Added an optional disabled state and tooltip for items in the select dropdown.
https://user-images.githubusercontent.com/3843503/131854242-d0556cd3-34b4-4a03-9dae-e46f732c42d4.mov

feat(Select): Add optional disabled state and tooltip

---

projects/novo-elements/src/utils/form-utils/FormUtils.spec.ts
projects/novo-elements/src/utils/form-utils/FormUtils.ts

Fix bug where only label/value were being used for current workflow options. This change retains the original properties alongside the new ones using the spread operator assignment.

fix(WorkflowOptions): Allow additional data in workflow option

---

projects/novo-elements/src/elements/chips/Chips.scss
projects/novo-elements/src/elements/picker/extras/entity-picker-results/EntityPickerResults.ts
projects/novo-elements/src/styles/global/variables.scss
projects/novo-elements/src/utils/app-bridge/AppBridge.ts

feat(AppBridge): add 'slide-out-add' to NovoApps type.
This will allow scheduler app to add a note to a JobShift via the AddNote slideout in novo

feat(AppBridge): add 'slide-out-add' to NovoApps type

---

projects/novo-elements/src/elements/form/FormInterfaces.ts
projects/novo-elements/src/utils/form-utils/FormUtils.ts

Map the parent entity of a field to the parentEntity property on a form field. This is useful to use in determining advanced filtering conditions in pickers that may be specific to what entity form the picker is located on.
The specific problem this will solve is allowing us to restrict certain location data from showing in pickers based on the entity the location is on. Example, BillingProfiles should only show BillTo locations.

feat(Form): Add parentEntity to formFields

---

projects/novo-elements/src/elements/form/extras/address/Address.ts

…to read only
Disable Address Field when set to read only to prevent tabbing into the field.

feat(addressField): Disable Address Field to prevent tabbing when set to read only

---

projects/novo-elements/src/elements/data-table/data-table.component.scss

This fix allows data table headers to word wrap. Previously, the column titles were truncated if they were longer than the column width.

feat(data table): Enable data table headers to word wrap

---

projects/novo-elements/src/elements/date-picker/DatePicker.scss
projects/novo-elements/src/elements/date-picker/DatePickerInput.ts
projects/novo-elements/src/services/date-format/DateFormat.ts

When user tabs or clicks away from the date field the field will remove the invalid value and be null
A warning will display that the field was not entered correct

feat(datePickerInput): Clear invalid date field when tabbing out

---

projects/novo-elements/src/elements/date-picker/DatePickerInput.ts
projects/novo-elements/src/services/novo-label-service.spec.ts
projects/novo-elements/src/services/novo-label-service.ts

Format and translate the placeholder within the date picker input based on user's locale and setting preferences

fix(datePickerInput): use translated and local format as date placeholder

---

projects/novo-elements/src/elements/form/ControlGroup.html
projects/novo-elements/src/elements/form/ControlGroup.ts

Small change to allow for the icons in the control group to be defaulted to the current ones but customized as an input.

feat(Control Group): Allow customizing of icons

---

package-lock.json
package.json
projects/novo-elements/src/elements/form/ControlGroup.ts
projects/novo-elements/src/elements/form/DynamicForm.ts
projects/novo-elements/src/elements/form/Form.ts
projects/novo-elements/src/elements/form/NovoFormGroup.ts
projects/novo-elements/src/elements/picker/extras/base-picker-results/BasePickerResults.ts
projects/novo-elements/src/elements/stepper/stepper.component.ts
projects/novo-elements/src/elements/table/extras/base-renderer/BaseRenderer.ts
projects/novo-elements/src/elements/table/extras/date-cell/DateCell.ts
projects/novo-elements/src/elements/table/extras/dropdown-cell/DropdownCell.ts
projects/novo-elements/src/utils/form-utils/FormUtils.ts
projects/novo-examples/src/examples.routes.ts

getting ready to update typescript from 3.9 to 4.0 in anticipation of angular 11 upgrade.
had to update a few components to use properties instead of getters/setters, and vice versa, due to breaking change in typescript 4.0.
- [/] Any related demos were added and `npm start` and `npm run build` still works
- [/] New demos work in `Safari`, `Chrome` and `Firefox`
- [/] `npm run lint` passes
- [/] `npm test` passes and code coverage is increased
- [/] `npm run build` still works

refactor(): some refactor work in preparation for typescript 4.0.8 upgrade

---

projects/novo-elements/src/elements/form/Control.ts
projects/novo-elements/src/elements/form/ControlTemplates.ts
projects/novo-elements/src/elements/table/Table.ts
projects/novo-elements/src/elements/table/extras/date-cell/DateCell.ts
projects/novo-elements/src/elements/table/extras/dropdown-cell/DropdownCell.ts
projects/novo-elements/src/elements/table/extras/table-cell/TableCell.ts

…grade
Missed a few spots in [!1266.](https://github.com/bullhorn/novo-elements/pull/1266)
Updating a few more .value calls to .getRawValue() on NovoFormGroup objects, and adding some missing getters.
- [/] Any related demos were added and `npm start` and `npm run build` still works
- [/] New demos work in `Safari`, `Chrome` and `Firefox`
- [/] `npm run lint` passes
- [/] `npm test` passes and code coverage is increased
- [/] `npm run build` still works

refactor(): some remaining prep work for the upcoming typescript 4 upgrade

---

projects/novo-elements/src/elements/select/Select.ts

Change default position to above-below to prevent dropdown from going below page. Dropdown will now appear above if there is not enough space below.

fix(select): change select default position to above-below

---

projects/novo-elements/src/elements/chips/Chip.ts
projects/novo-elements/src/elements/chips/Chips.ts
projects/novo-elements/src/elements/form/extras/file/FileInput.ts
projects/novo-examples/src/examples.routes.ts

BUG FIX 
Chips Preview Template never initiating onClick.  Added toggle to the clickHandler.  The eventual idea is for this to be managed by the "ChipList" component because it should handle key and focus events for accessibility, but that work should be done on the next branch.

fix(Chips): Chips preview wasn't dispatch because select event was busted

---

projects/novo-elements/src/elements/date-picker/DatePickerInput.ts

I modified the _setCalendarValue method in NovoDatePickerInputElement class. The date picker input did not respect the date that was in the input field unless the enter key was pressed and then the calendar ui would highlight the date in the input field. The reason this was happening was that this code value = new Date(value).setHours(0, 0, 0, 0); was returning a date as a timestamp instead of a date object.

fix(datepickerInput): fix calendar UI not respecting valid date in input field

---

projects/novo-elements/src/novo-elements.providers.ts
projects/novo-elements/src/services/security/Security.ts
projects/novo-examples/src/examples.routes.ts

The Security service is being instantiated more times than we need it to be, so by providing it in root and removing it from the providers export and all but the main Novo module we are able to cut down the number of instances to one per iframe (plus the one in the mainframe).

fix(Security): providing security service in root to avoid running unnecessary instances

---

projects/novo-elements/src/elements/data-table/data-table.component.scss

This resolves issue https://github.com/bullhorn/novo-elements/issues/1267 by making the background of the data table pagination marker dynamic. instead of a hardcoded color, it's now simply black with an opacity of 10%, so it will render as whatever color the header is, just slightly darker.

fix(NovoDataTable): making pagination marker background color dynamic

---

projects/novo-elements/src/elements/aside/aside-ref.ts
projects/novo-elements/src/elements/aside/aside.service.ts
projects/novo-elements/src/elements/modal/modal-ref.ts
projects/novo-examples/src/components/aside/aside-examples.md
projects/novo-examples/src/components/aside/aside-usage/aside-usage-example.ts
projects/novo-examples/src/components/modal/modal-examples.md
projects/novo-examples/src/examples.routes.ts

This will close #1276 
Added `onClosed` promise to `NovoAsideRef` to conform to `NovoModalRef`
Added better typing support to both `NovoAsideRef` and `NovoModalRef` to support return type. With T being the type for the Params passed to the **Modal**/**Aside** and R being the returned result. You only need to set R value when calling `asideService.open<string>(...)` the type is optional and will default to any.
```ts
class NovoAsideRef<T = any, R = any> 
class NovoModalRef<T = any, R = any> 
// AsideService
open<R = any>( ... ) // where R is the return value. 
```
```ts 
const ref = this.aside.open<string>(AsideCustomDemo, { id: 100, name: 'Ferdinand del Toro' });
ref.onClosed.then((result) => {
console.log('Aside has been closed, with result:', result);
});
```

fix(Aside): Aside ref was missing returning optional result and didn't conform to same api as ModalRef

---

.gitignore
package-lock.json
projects/novo-elements/src/elements/button/styles/button-other.scss
projects/novo-elements/src/elements/calendar/calendar.component.scss
projects/novo-elements/src/elements/calendar/month-view/month-view.component.scss
projects/novo-elements/src/elements/common/option/option.component.scss
projects/novo-elements/src/elements/common/typography/text.mixins.scss
projects/novo-elements/src/elements/form/ControlGroup.scss
projects/novo-elements/src/elements/tabbed-group-picker/TabbedGroupPicker.scss
projects/novo-elements/src/novo-elements.scss
projects/novo-elements/src/styles/themes/dark.scss
projects/novo-elements/src/styles/themes/light.scss
projects/novo-elements/src/styles/typography.scss

Updated css variable for light theme.
```css
/* Changed main text color to charcoal  */
--text-main: var(--color-charcoal);
/* Changed muted text color to neutral, used for secondary text like labels and captions  */
--text-muted: var(--color-neutral);
/* Added for disabled and placeholder text*/
--text-disabled: var(--color-slate);
```

fix(Theme): text colors are now darker

---

package-lock.json
projects/novo-elements/src/elements/dropdown/Dropdown.ts
projects/novo-elements/src/elements/select/Select.ts

when using type-ahead in dropdown and select components, debounce time was very low (100ms) so the user would have to type extremely fast to avoid each keystroke being registered as a separate search, each one overriding the last.
This is being done to address issue https://github.com/bullhorn/novo-elements/issues/1291

fix(Dropdown): increasing debounce time for type-ahead

---

projects/novo-elements/src/elements/chips/RowChips.ts

Adjusting the row chips picker to stay visible on the screen when adding many items to the list. For very long lists of row chip pickers in Novo, the row chip picker overlay needs to be allowed to pop up over the existing rows.

feat(picker): Adjusting how picker overlay appears for row chips.

---

projects/novo-elements/src/elements/chips/Chips.scss

Removing the novo-picker style when nested within novo-row-chips. We want the picker to expand to 100% of the size of the container, which is how it behaves in other areas. After these changes the picker will expand to be the standard width of our form fields.
BEFORE CHANGES:
AFTER CHANGES:

style(Chips): remove max-width from novo-picker if a row chips picker

---

package-lock.json
package.json
projects/novo-elements/package.json
projects/novo-elements/src/elements/form/extras/file/FileInput.scss
projects/novo-elements/src/elements/form/extras/file/FileInput.spec.ts
projects/novo-elements/src/elements/form/extras/file/FileInput.ts
projects/novo-examples/src/form-controls/form/file-input-controls/file-input-controls-example.html
projects/novo-examples/src/form-controls/form/file-input-controls/file-input-controls-example.ts

Small fixes for NovoFileInputElement:
- FileInput now allows for removing file and re-selecting same file. 
- FileInput now clears file list when undefined is passed through form.patchValue(). (E.g. fileForm.patchValue({file:  #undefined});
Fixes Issues:  #1183 and #1182

fix(NovoFileInputElement): Allow for same file delete/upload, allow file list clear from patchValue().

---

projects/novo-elements/src/elements/field/autocomplete/autocomplete.component.ts
projects/novo-elements/src/elements/form/ControlTemplates.ts
projects/novo-elements/src/elements/layout/sidenav/sidenav.component.ts
projects/novo-elements/src/elements/table/extras/table-filter/TableFilter.ts

Fixing some import statements so that novo-elements can be run with the novo app locally

fix(imports): fix utils imports

---

projects/novo-elements/src/elements/time-picker/TimePickerInput.ts

Fixed date comparisons to avoid incorrectly emitting change events

fix: use correct comparison for dates in time picker input

---

package-lock.json
projects/novo-elements/src/elements/common/option/optgroup.component.ts
projects/novo-elements/src/elements/common/option/option.component.html
projects/novo-elements/src/elements/common/option/option.component.ts
projects/novo-elements/src/elements/data-table/cell-headers/data-table-header-cell.component.ts
projects/novo-elements/src/elements/data-table/data-table.component.scss
projects/novo-elements/src/elements/dropdown/Dropdown.scss
projects/novo-elements/src/elements/icon/Icon.scss
projects/novo-elements/src/elements/tabbed-group-picker/TabbedGroupPicker.html
projects/novo-elements/src/elements/table/Table.ts
projects/novo-examples/src/examples.routes.ts

a chrome v102 update to the inert attribute broke a bunch of our data table filters, since they were using that attribute. this update basically disabled them completely, so we renamed our attribute we were keying off of to 'novoInert' and are also updating how we're handling the keep-open state of the filter dropdowns.
https://chromestatus.com/feature/5703266176335872

fix: fix for chrome update breaking inert elements

---

projects/novo-elements/src/elements/picker/extras/grouped-multi-picker-results/GroupedMultiPickerResults.scss

Set flex on the list-item class to prevent the horizontal scrollbar from showing.

fix(GroupedMultiPickerResults): Remove horizontal scrollbar

---

projects/novo-elements/src/elements/picker/extras/picker-results/PickerResults.ts

Added data-automation-id to picker result list items so picker element location is consistent in the automation

style(picker): Add data-automation-id to picker

---

projects/novo-elements/src/elements/ckeditor/CKEditor.spec.ts
projects/novo-elements/src/elements/ckeditor/CKEditor.ts

Change CKEditor config to no longer encode special and accented characters by default.
Example: `À Á Â` will now save as `À Á Â` instead of `&Agrave; &Aacute; &Acirc;`
https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html

refactor(CKEditor): Do not encode special characters by default

---

projects/novo-elements/src/elements/data-table/data-table.component.scss
projects/novo-elements/src/elements/data-table/data-table.component.ts
projects/novo-elements/src/services/novo-label-service.ts

This handles the case where a user is enabled permissions for infinite paging on a data-table and no records are returned on the current page being viewed. (ie. the user has paged beyond the end of available records)

feat(data-table): Add no-more-results container

---

projects/novo-elements/src/elements/chips/ChipInput.ts
projects/novo-elements/src/elements/chips/ChipList.ts
projects/novo-elements/src/elements/chips/ChipTextControl.ts
projects/novo-elements/src/elements/common/option/option.component.ts
projects/novo-elements/src/elements/field/autocomplete/autocomplete.component.ts
projects/novo-elements/src/elements/field/field.ts
projects/novo-examples/src/components/autocomplete/autocomplete-stacked-chips/autocomplete-stacked-chips-example.html
projects/novo-examples/src/components/autocomplete/autocomplete-stacked-chips/autocomplete-stacked-chips-example.ts
projects/novo-examples/src/components/autocomplete/autocomplete-textarea/autocomplete-textarea-example.html
projects/novo-examples/src/components/autocomplete/autocomplete-with-chips/autocomplete-with-chips-example.html
projects/novo-examples/src/components/autocomplete/autocomplete-with-chips/autocomplete-with-chips-example.ts

Autocomplete now works with the NovoChipList when used in a NovoFormField.  The manual events are no longer necessary to utilize the autocomplete functionality.  Now basic functionality can be supported with a limited specification.
```html
<novo-field>
<novo-label>Favorite Fruits</novo-label>
<novo-chip-list #chipList [formControl]="fieldCtrl">
<novo-chip *ngFor="let fruit of chipList.value" [value]="fruit">
<novo-text>{{fruit}}</novo-text>
<novo-icon novoChipRemove>close</novo-icon>
</novo-chip>
<input #chipInput novoChipInput placeholder="New fruit..." autocomplete="off" [formControl]="searchCtrl" />
</novo-chip-list>
<novo-autocomplete (optionSelected)="selected($event)" multiple>
<novo-option *ngFor="let fruit of filteredFruits | async" [value]="fruit">
{{fruit}}
</novo-option> …
```

feat(Autocomplete): Autocomplete now works with ChipList

---

projects/novo-elements/src/elements/non-ideal-state/NonIdealState.ts
projects/novo-examples/src/components/non-ideal-state/non-ideal-state-examples.md
projects/novo-examples/src/components/non-ideal-state/non-ideal-state-loading-usage/index.ts
projects/novo-examples/src/components/non-ideal-state/non-ideal-state-loading-usage/non-ideal-state-loading-usage-example.css
projects/novo-examples/src/components/non-ideal-state/non-ideal-state-loading-usage/non-ideal-state-loading-usage-example.html
projects/novo-examples/src/components/non-ideal-state/non-ideal-state-loading-usage/non-ideal-state-loading-usage-example.ts
projects/novo-examples/src/examples.routes.ts

Adding a message next to the novo-loading component is not a known pattern. This could be used to display a message while loading with the flag controlled at implementation. This can be used for a loading message displaying all the time for a loading screen, or having a timer flipping the flag to show a message during a long long loading screen.

feat(NonIdealState): Non Ideal Loading

---

projects/novo-elements/src/elements/chips/ChipInput.ts
projects/novo-elements/src/elements/query-builder/condition-definitions/string-condition.definition.ts
projects/novo-elements/src/elements/query-builder/condition-group/condition-group.component.ts
projects/novo-elements/src/elements/query-builder/criteria-builder/criteria-builder.component.ts

I added an ngModel to the input on the query builder's string definition to fix some errors being thrown about needing a provider for NgControl, but this created an issue where the model was effectively being shared between multiple string defs if they were loaded onto the form together. To fix this (and the original issue as well) I refactored the novo-field and chip-list on the string def to use a formGroup and ngControlName instead of ngModel.
Also making the value not required since it doesn't need to be.

fix(NovoDefaultStringConditionDef): fixing bug with the model when loading multiple string defs

---

package.json
projects/novo-elements/src/elements/data-table/data-table.component.ts
projects/novo-elements/src/elements/data-table/interfaces.ts
projects/novo-elements/src/elements/data-table/state/data-table-state.service.spec.ts
projects/novo-elements/src/elements/data-table/state/data-table-state.service.ts
projects/novo-examples/src/examples.routes.ts

..and reset saved search name
most of the data-table state fns are additive, allowing the consumer to change, set, reset one property without affecting the others. the exception to this is the reset() fn, which sets everything to undefined and then fires an update event. we needed a fn that functions like this, but sets everything to a provided value whether it's defined or not so we can explicitly set the state of the data-table.
we also needed a way to store and reset the name of the currently applied saved search to avoid having to manage this state separately in lower level services.

feat(DataTable): adding ability to explicitly set data-table state

---

projects/novo-elements/src/elements/picker/Picker.spec.ts
projects/novo-elements/src/elements/picker/Picker.ts

Updating picker to only trigger events and field interactions when backspacing on picker values. Field interactions no longer trigger when backspacing on empty picker input, or non-select/non-chip input value.

fix(picker): fixed field interaction issue on picker

---

projects/novo-elements/src/elements/data-table/data-table.component.ts
projects/novo-elements/src/elements/data-table/interfaces.ts
projects/novo-elements/src/elements/data-table/pagination/data-table-pagination.component.ts
projects/novo-elements/src/services/novo-label-service.ts

NovoDataTablePagination: update with a loading state (loading dots) and an error state (with button that can be wired up to handle refreshing data)
NovoDataTable: update with pass throughs for the new pagination loading state and refresh button, and add overrideTotal input to enable manually setting pagination length

feat(NovoDataTable): Update pagination with loading state, refresh button, and ability to override total

---

projects/novo-elements/src/elements/common/overlay/Overlay.ts

Adding a safety check to the elementIsInNestedOverlay. On the off chance that el.id is something other than a string, this will ensure we don't try to execute the el.id?.includes() which breaks in this situation.

fix(Overlay): add safety check to nested overlay check method

---

projects/novo-elements/src/elements/field/field-control.ts
projects/novo-elements/src/elements/field/field.ts
projects/novo-elements/src/elements/query-builder/condition-definitions/picker-condition.definition.ts

if a field has an ngControl, it looks like we can pull the name of the control to use as the data-automation-id.

feat(Field): adding data-auto-ids to the new novo-field elements

---

package-lock.json
package.json

Removed unused @xmldom dependency due to critical security flaw:
https://github.com/bullhorn/novo-elements/security/dependabot/60

fix(xmldom): removed unused xmldom dependency due to security concern

---

projects/demo/index.html

Using a new cdn for ckeditor to not impose on new license terms.

chore(demo): use different cdn for ckeditor

---

projects/elements/addons/dragula/dragula-service.ts
projects/elements/addons/dragula/dragula.module.ts
projects/elements/addons/dragula/dragula.ts

deprecating novo-elements dragula implementation in anticipation of deleting it in a future release.

refactor(dragula): deprecating dragula directive and service

---

projects/novo-elements/src/elements/data-table/sort-filter/sort-button.animations.ts
projects/novo-elements/src/elements/data-table/sort-filter/sort-button.component.html
projects/novo-elements/src/elements/data-table/sort-filter/sort-button.component.scss

ng14 is now throwing console warnings when you try to animate non-animatable properties. ie:
```
browser.mjs:2541 Warning: The animation trigger "sortNone" is attempting to animate the following not animatable properties: pointerEvents
(to check the list of all animatable properties visit https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_animated_properties)
```
this is a fix for this behavior.

fix(NovoDataTableSortButton): fixing ng14 warning caused by animating pointer-events

---

projects/novo-elements/src/elements/date-time-picker/DateTimePicker.ts
projects/novo-elements/src/elements/field/formats/date-time-format.ts
projects/novo-elements/src/elements/field/toggle/picker-toggle.component.html
projects/novo-elements/src/elements/field/toggle/picker-toggle.component.ts
projects/novo-elements/src/elements/query-builder/condition-definitions/date-time-condition.definition.ts
projects/novo-elements/src/elements/query-builder/criteria-builder/criteria-builder.component.html
projects/novo-elements/src/elements/query-builder/index.ts
projects/novo-elements/src/elements/query-builder/query-builder.module.ts
projects/novo-examples/src/components/field/form-usage/form-usage-example.html

feat(date-time-condition): Added default date-time condition definition

---

package-lock.json
package.json
projects/novo-elements/src/elements/data-table/sort-filter/sort-button.animations.ts
projects/novo-elements/src/elements/data-table/sort-filter/sort-button.component.html
projects/novo-elements/src/elements/data-table/sort-filter/sort-button.component.scss
projects/novo-elements/src/elements/date-time-picker/DateTimePicker.ts
projects/novo-elements/src/elements/field/field-control.ts
projects/novo-elements/src/elements/field/field.module.ts
projects/novo-elements/src/elements/field/field.ts
projects/novo-elements/src/elements/field/formats/date-time-format.ts
projects/novo-elements/src/elements/field/index.ts
projects/novo-elements/src/elements/field/toggle/picker-toggle.component.html
projects/novo-elements/src/elements/field/toggle/picker-toggle.component.ts
projects/novo-elements/src/elements/form/Form.module.ts
projects/novo-elements/src/elements/query-builder/condition-builder/condition-builder.component.scss
projects/novo-elements/src/elements/query-builder/condition-definitions/abstract-condition.definition.ts
projects/novo-elements/src/elements/query-builder/condition-definitions/address-condition.definition.ts
projects/novo-elements/src/elements/query-builder/condition-definitions/boolean-condition.definition.ts
projects/novo-elements/src/elements/query-builder/condition-definitions/date-condition.definition.ts
projects/novo-elements/src/elements/query-builder/condition-definitions/date-time-condition.definition.ts
projects/novo-elements/src/elements/query-builder/condition-definitions/number-condition.definition.ts
projects/novo-elements/src/elements/query-builder/condition-definitions/picker-condition.definition.ts
projects/novo-elements/src/elements/query-builder/condition-definitions/string-condition.definition.ts
projects/novo-elements/src/elements/query-builder/criteria-builder/criteria-builder.component.html
projects/novo-elements/src/elements/query-builder/index.ts
projects/novo-elements/src/elements/query-builder/query-builder.module.ts
projects/novo-elements/src/services/novo-label-service.ts
projects/novo-examples/src/components/field/form-usage/form-usage-example.html
projects/novo-examples/src/components/field/form-usage/form-usage-example.ts

feat(Field): adding data-auto-ids to the new novo-field elements #1349
feat(QueryBuilder): adding isNull/isEmpty operators to query builder field definitions #1358
feat(dateTimePicker): Added formatter for dateTimePicker #1361
fix(xmldom): removed unused xmldom dependency due to security concern #1357
chore(deps): bump loader-utils from 1.4.0 to 1.4.1 #1362
chore(deps): bump loader-utils from 1.4.1 to 1.4.2 #1366
fix(NovoDataTableSortButton): fixing ng14 warning caused by animating pointer-events #1368
feat(date-time-condition): Added default date-time condition definition #1364

feat(): next

---

projects/novo-elements/src/elements/button/Button.ts
projects/novo-examples/src/components/buttons/button-dynamic/button-dynamic-example.ts
projects/novo-examples/src/components/buttons/button-loading/button-loading-example.ts

Disabled buttons and buttons in a 'loading' state were correctly swallowing click events, but they were not swallowing keyboard events which would call functions attached to them. This was resulting in a user being able to make multiple identical api requests when (for example) submitting a form by hitting enter/space multiple times or by holding either of those keys down.

fix(NovoButton): disabling enter/space keypresses on disabled/loading buttons

---

projects/novo-elements/src/elements/quick-note/QuickNote.ts

Currently when you click on the placeholder/help text in a Notes Textbox you are unable to enter a comment/note. You have to click outside of the placeholder to be able to write a comment/note. I am adding `pointer-events: none` to the quickNote placeholder to prevent the placeholder from being the target of click events.

fix(quickNote): Allow placeholder to hide when clicking in text field to write a note

---

projects/novo-elements/src/elements/popover/PopOver.ts

fix error when popover htmlcontent is empty

feat(popOver): fix popover error with empty content

---

projects/novo-elements/src/elements/data-table/data-table.component.scss
projects/novo-examples/src/components/data-table/data-table-rows/data-table-rows-example.ts

Making resizable column more obvious by adding a vertical divider on the right, and adding a light gray background on hover. Also adding a few resizable columns to the DataTable demo to test them out.

fix(DataTable): restyling resizable column headers to make them more obvious

---

package-lock.json

pulled out the changes from the automated PRs pointed to master into this one PR pointing to next.
https://github.com/bullhorn/novo-elements/pull/1393
https://github.com/bullhorn/novo-elements/pull/1387
https://github.com/bullhorn/novo-elements/pull/1383
https://github.com/bullhorn/novo-elements/pull/1380

chore(deps): dependabot security updates from the last few months

---

projects/novo-elements/src/elements/data-table/cell-headers/data-table-header-cell.component.ts
projects/novo-elements/src/elements/data-table/interfaces.ts
projects/novo-examples/src/components/data-table/data-table-rows/data-table-rows-example.ts

In an effort to make dynamic column width settings able to be saved, persistent, and ultimately managed by the consumer of the data-table, I am pulling some logic out of the main resizing function to be able to be called independently. There is a width property on IDataTableColumn which can be used, but in order to use this we would need to know the width of the column before initializing the data table, and with the asynchronous way we handle loading data tables and their Preferences that may not always be the case.

feat(DataTable): pulling out column width setting logic to public function

---

projects/novo-elements/src/elements/picker/Picker.scss
projects/novo-elements/src/elements/picker/Picker.ts

We have a few different picker results templates which can still display text when their width is pretty small, but the `novo-entity-picker-results` template specifically displays lots of sub data points for each result which requires some space to be able to display properly. We're implementing some of these pickers in a place where the initial field width is pretty narrow, but has room around it for the picker to expand over, so we want to set a min-width here to give it room to display properly.
We're also making the `input` ViewChild property on the NovoPickerElement public so that we can call `focus` on it from a consuming component, since we want to load the pickers conditionally after the template has already been initialized.

fix(Picker): setting min-width on novo entity picker results

---

package-lock.json
package.json

Bumping icons version to pull in some recently added icons

chore(icons): Bump icons version

---

projects/novo-elements/src/elements/picker/Picker.ts

Add maxlength parameter for novo-picker

feat(picker): add maxlength parameter for characters on input

---

.github/workflows/firebase-hosting-pull-request.yml
.github/workflows/main.yml
.github/workflows/publish-docs.yml
.github/workflows/release.yml

our builds started failing with the error
`Firebase CLI v12.0.0 is incompatible with Node.js v14.19.1 Please upgrade Node.js to version >=16.13.0 || >=18.0.0`
during the deploy preview stage so i upped the node version in all of our workflow scripts.

build(): fixing the firebase preview script by upping node version

---

projects/novo-elements/src/elements/list/list-item-content.scss
projects/novo-elements/src/elements/list/list-item-header-avatar.scss
projects/novo-elements/src/elements/list/list-item-header-title.scss

- list `item-title`s appeared fine but had no actual size in the DOM so had broken some test automation
- avatar icons weren't applying their themed colors correctly
- a couple list `item-content` properties were getting overridden due to losing a bit of specificity so i had to add some back

fix(css): fixing some issues found with round 1 of the style encapsulation work

---

projects/novo-elements/src/elements/tabs/Tabs.ts
projects/novo-elements/src/elements/tabs/tab-content.scss
projects/novo-elements/src/elements/tabs/tab-outlet.scss

encapsulating the styles for the tabs' outlet and content components caused the specificity on their styles to increase which overwrote some styles that novo needed to display the nested tab components properly. it would be preferable to encapsulate these styles, but in the interest of backwards compatibility we're going to not encapsulate them for now. we're still building them with their respective components with the styleUrls property so that's still a big step up from importing them into the root novo-elements stylesheet which is what we were doing before.

fix(css): another minor fix to a style encapsulation issue on the tabs component

---

projects/novo-elements/src/elements/picker/extras/base-picker-results/BasePickerResults.ts

when the results component is set to not close on select (like in the case of a Chips multiselect picker), `selectingMatches` was never getting set back to false. this was preventing `activeMatch` from getting reset to the first match when a new search was carried out due to this if check in the `processSearch()` function:
```
if (this.matches.length > 0 && this.autoSelectFirstOption && !this.selectingMatches) {
this.nextActiveMatch();
}
```

fix(Picker): fixing bug preventing active match from resetting when results don't close

---

projects/novo-elements/src/elements/dropdown/Dropdown.scss

certain DataTable cell dropdowns were relying on styles located in a stylesheet for the Table component, so after we went through and encapsulated styles properly they were no longer getting applied. The Table component is deprecated so the best fix for this was just to copy these styles from that component stylesheet and put them in the appropriate Dropdown component stylesheet.

fix(Dropdown): fixing a styling bug with data table dropdown cell lists

---

.gitignore
jest.config.js
package.json
sonar-project.properties

Added SonarQube configuration and exclusions to generate code coverage reports

feat(test): Configure SonarQube to inspect code coverage from jest

---

projects/novo-elements/src/elements/dropdown/Dropdown.scss

the style encapsulation changes made with the v8 release prevented this styling block from getting applied, which resulted in dropdown trigger icons not displaying the pointer cursor.

fix(dropdown): fixing a styling bug around dropdown icon cursors introduced in v8

---

projects/novo-elements/src/elements/drag-drop/drag-drop-box.spec.ts
projects/novo-elements/src/elements/drag-drop/drag-drop-box.ts

Fixes to drag-drop module when regions are contained within each other (as in BhMenu in Novo)

fix(DragDrop): Address dragdrop parenting issues

---

projects/novo-elements/src/elements/form/extras/FormExtras.module.ts
projects/novo-elements/src/elements/form/extras/file/FileInput.html
projects/novo-elements/src/elements/form/extras/file/FileInput.scss
projects/novo-elements/src/elements/form/extras/file/FileInput.spec.ts
projects/novo-elements/src/elements/form/extras/file/FileInput.ts
projects/novo-elements/src/services/global/global.service.ts

Removes use of Dragula from FileInput in favor of Angular CDK drag-drop module (progressing towards removal of the Dragula module)

refactor(FileInput): Removed Dragula from FileInput.ts

---

projects/novo-elements/src/elements/drag-drop/drag-drop-box.spec.ts
projects/novo-elements/src/elements/drag-drop/drag-drop-box.ts
projects/novo-examples/src/utils/drag-drop/drag-drop/drag-drop-example.ts

Exchanged mousemove/drag events for dragover events, to have Firefox better handle drag-outside situations.

fix(DragDrop): Fix Firefox's use of drag events

---

projects/novo-examples/src/components/field/field-design.md
projects/novo-examples/src/components/query-builder/query-builder-design.md
projects/novo-examples/src/examples.routes.ts
projects/novo-examples/src/layouts/sidenav/sidenav.md
projects/novo-examples/src/updates/v9.md
projects/novo-examples/src/utils/ace-editor/ace-editor.md

Adds a screen that details the new changes in v9.

docs(v9): Add v9 documentation page

---

.github/workflows/firebase-hosting-pull-request.yml
projects/novo-elements/src/elements/field/formats/date-format.ts
projects/novo-elements/src/elements/field/formats/date-time-format.ts
projects/novo-elements/src/elements/field/formats/time-format.ts
projects/novo-elements/src/services/date-format/DateFormat.ts

we need to allow dates to be set beyond 2030 so we're upping the default date/time masks to support dates up to 2100.
also setting the firebase tools version manually for the firebase build action due to this bug:
https://github.com/FirebaseExtended/action-hosting-deploy/issues/326

fix(imask): upping the max date on all date/time masks from 2030 to 2100

---

projects/novo-elements/src/services/data-provider/ArrayCollection.ts
projects/novo-elements/src/services/data-provider/Collection.ts

just a quick typing update to correctly pass the generic type `T` into the getItemIndex function in the Collection service. this brings it in line with other functions and the types of existing functions that call it.
the purpose for this update is to fix a typescript compilation error when an app is importing novo-elements as a dependency and that app's tsconfig has the `strict = true` compiler option enabled.

fix(Collection): fixing a strict=true TS compilation error

---

projects/novo-elements/src/elements/expansion/expansion-panel-header.ts

since these properties are used in an animation, they need to have a value as of angular 15. this fixes a compilation error and should not change any existing behavior.

fix(ExpansionPanelHeader): adding default heights to expansion-panel-header input properties

---

projects/novo-elements/src/utils/app-bridge/AppBridge.spec.ts
projects/novo-elements/src/utils/app-bridge/AppBridge.ts
projects/novo-elements/src/utils/app-bridge/index.ts
projects/novo-elements/src/utils/app-bridge/interfaces.ts

This change takes the raw "origin" value from postrobot event handlers and appends it to the message data, making it easier for the host frame to record information on different senders. This comes in natively as part of the iframe message event, so the child instance of AppBridge doesn't need to implement it.
This also changes the types around MessageTypes so that they are definitively typed towards each string, rather than all being of type "string". Thus, a coder providing a value that doesn't match the options will get a compilation error.

feat(AppBridge): When handling AppBridge events, pass origin to handler

---

projects/novo-elements/src/elements/picker/extras/picker-results/PickerResults.scss

Making a small change for entity-picker background to fix transparency issues in firefox and safari. Entity-picker inside PickerResults should remain non-transparent in firefox and safari as it does in chrome.

fix(PickerResults): Fixing picker background in firefox/safari

---

projects/novo-elements/src/elements/form/DynamicForm.ts
projects/novo-elements/src/elements/stepper/stepper.component.ts
projects/novo-examples/src/form-controls/dynamic-form/dynamic-form-field-sets/dynamic-form-field-sets-example.ts
projects/novo-examples/src/form-controls/dynamic-form/dynamic-form/dynamic-form-example.ts
projects/novo-examples/src/layouts/sidenav/basic-sidenav/basic-sidenav-example.html

There were a few issues with the examples called out by some issues:
- #1482
- DynamicForm - this was actually an issue in the component itself. added an undefined check on a property reference.
- #1198
- DynamicForm - we were not referencing the form objects properly in the clear functions implemented in the demos.
- #1440 
- SideNav - the outlet on the novo-nav in the example template needed to be bracketed to properly pass it in.
- #1440 
- Stepper - we were subscribing to a state change until 'this._destroyed' without using the OnDestroy lifecycle hook. implemented OnDestroy.

fix(Demo): fixing a few issues with the examples and their components

---

projects/novo-elements/src/elements/chips/RowChips.scss
projects/novo-elements/src/elements/chips/RowChips.ts

Adds a flag that can be passed into the control config/overrides to allow row chips to be shown at full height (instead of always having overflow hidden and height set at 2em).

feat(RowChips): Add flag to show chips at full height

---

projects/novo-elements/src/elements/chips/Chip.spec.ts
projects/novo-elements/src/elements/chips/Chips.module.ts
projects/novo-elements/src/elements/chips/Chips.scss
projects/novo-elements/src/elements/chips/Chips.spec.ts
projects/novo-elements/src/elements/chips/Chips.ts
projects/novo-elements/src/elements/chips/index.ts
projects/novo-elements/src/elements/chips/pipe/AvatarType.pipe.ts
projects/novo-elements/src/elements/chips/pipe/index.ts
projects/novo-elements/src/services/novo-label-service.ts
projects/novo-examples/src/examples.routes.ts
projects/novo-examples/src/form-controls/chips/chips-examples.md
projects/novo-examples/src/form-controls/chips/hide-chips/hide-chips-example.css
projects/novo-examples/src/form-controls/chips/hide-chips/hide-chips-example.html
projects/novo-examples/src/form-controls/chips/hide-chips/hide-chips-example.ts
projects/novo-examples/src/form-controls/chips/hide-chips/index.ts

- Added optional `maxChipsShown` prop to the @Input `source` object. This will limit the number of chips shown in the picker input element. 
- A clickable suffix label was also added, to toggle the visibility of the hidden chips.

feat(Chips): added new hidden chips feature to Chips picker

---

projects/demo/app/app.component.ts
projects/novo-examples/src/examples.routes.ts
projects/novo-examples/src/updates/v10.md
projects/novo-examples/src/updates/v6.md
projects/novo-examples/src/updates/v7.md
projects/novo-examples/src/updates/v9.md
projects/novo-examples/src/utils/ace-editor/ace-editor.md
tools/examples-routes.ts

- adding release notes for v10 release
- fixing ordering for 'Updates' section to respect the order property instead of sorting alphabetically
- adding additional deprecation notice to ace editor documentation

chore(): adding release notes for v10 release

---

projects/novo-elements/src/elements/data-table/data-table.component.ts
projects/novo-elements/src/elements/data-table/interfaces.ts
projects/novo-elements/src/elements/data-table/state/data-table-state.service.spec.ts
projects/novo-elements/src/elements/data-table/state/data-table-state.service.ts

Adds appliedSearchType allowing searches to be sorted by type

feat(Data Tables): Add applied search type

---

projects/novo-elements/src/elements/data-table/interfaces.ts
projects/novo-elements/src/elements/data-table/state/data-table-state.service.spec.ts
projects/novo-elements/src/elements/data-table/state/data-table-state.service.ts
projects/novo-elements/src/elements/query-builder/condition-group/condition-group.component.html
projects/novo-elements/src/elements/query-builder/condition-group/condition-group.component.ts
projects/novo-elements/src/elements/query-builder/criteria-builder/criteria-builder.component.spec.ts
projects/novo-elements/src/elements/query-builder/criteria-builder/criteria-builder.component.ts
projects/novo-elements/src/elements/query-builder/query-builder.service.ts
projects/novo-elements/src/elements/query-builder/query-builder.types.ts
projects/novo-examples/src/components/query-builder/just-criteria/just-criteria-example.ts

Cleaning up the types and tests for the criteria builder - non-functional changes

feat(Criteria Builder): Add criteria builder types and tests

---

projects/novo-elements/src/elements/form/Control.spec.ts

Added unit test coverage for Control.ts to bring the code coverage to 80%

test(Control): increase code coverage for Control

---

projects/novo-elements/src/utils/app-bridge/AppBridge.spec.ts
projects/novo-elements/src/utils/app-bridge/AppBridge.ts
projects/novo-elements/src/utils/app-bridge/index.ts
projects/novo-elements/src/utils/app-bridge/interfaces.ts

Third attempt at reintroducing sender tracking on AppBridge calls

feat(AppBridge): Log origin information during method calls

---

projects/novo-elements/src/elements/data-table/interfaces.ts
projects/novo-elements/src/elements/query-builder/condition-definitions/abstract-condition.definition.ts
projects/novo-elements/src/elements/query-builder/condition-definitions/address-condition.definition.ts
projects/novo-elements/src/elements/query-builder/condition-definitions/boolean-condition.definition.ts
projects/novo-elements/src/elements/query-builder/condition-definitions/date-condition.definition.ts
projects/novo-elements/src/elements/query-builder/condition-definitions/date-time-condition.definition.ts
projects/novo-elements/src/elements/query-builder/condition-definitions/id-condition.definition.ts
projects/novo-elements/src/elements/query-builder/condition-definitions/number-condition.definition.ts
projects/novo-elements/src/elements/query-builder/condition-definitions/picker-condition.definition.ts
projects/novo-elements/src/elements/query-builder/condition-definitions/string-condition.definition.ts
projects/novo-elements/src/elements/query-builder/criteria-builder/criteria-builder.component.spec.ts
projects/novo-elements/src/elements/query-builder/query-builder.types.ts
projects/novo-examples/src/components/query-builder/just-criteria/just-criteria-example.ts

Our typescript types could be stricter, since we have a limited number of operations.

fix(Criteria): Added criteria operator types

---

projects/novo-elements/src/elements/data-table/interfaces.ts

fix(Criteria Types): Adding missing operator types

---

projects/novo-elements/src/elements/data-table/interfaces.ts

fix(CriteriaTypes): Adding missing operator types

---

projects/novo-elements/src/elements/common/option/option.component.ts
projects/novo-elements/src/elements/query-builder/condition-builder/condition-builder.component.ts
projects/novo-elements/src/elements/tabbed-group-picker/TabbedGroupPicker.html
projects/novo-elements/src/elements/tabbed-group-picker/TabbedGroupPicker.scss
projects/novo-elements/src/elements/tabbed-group-picker/TabbedGroupPicker.spec.ts
projects/novo-elements/src/elements/tabbed-group-picker/TabbedGroupPicker.ts
projects/novo-elements/src/services/novo-label-service.ts
projects/novo-examples/src/components/tabbed-group-picker/index.ts
projects/novo-examples/src/components/tabbed-group-picker/tabbed-group-picker-no-selection-example/index.ts
projects/novo-examples/src/components/tabbed-group-picker/tabbed-group-picker-no-selection-example/tabbed-group-picker-no-selection-example.html
projects/novo-examples/src/components/tabbed-group-picker/tabbed-group-picker-no-selection-example/tabbed-group-picker-no-selection-example.ts
projects/novo-examples/src/components/tabbed-group-picker/tabbed-group-picker.md
projects/novo-examples/src/examples.routes.ts

Added option to disable item selection/checkboxes.

feat(TabbedGroupPicker): Added option to disable item selection/checkboxes

---

projects/novo-elements/src/elements/common/overlay/Overlay.ts
projects/novo-elements/src/elements/common/typography/base/base-text.component.ts
projects/novo-elements/src/elements/header/Header.ts
projects/novo-elements/src/elements/search/SearchBox.ts

this way we can attach the overlay to any element we want.

feat(Search): adding ability to override parent element for custom overlay positioning

---

projects/novo-elements/src/elements/query-builder/condition-definitions/picker-condition.definition.ts
projects/novo-elements/src/elements/select/Select.extupdatefix.directive.spec.ts
projects/novo-elements/src/elements/select/Select.extupdatefix.directive.ts
projects/novo-elements/src/elements/select/Select.module.ts
projects/novo-elements/src/elements/select/index.ts
projects/novo-elements/src/services/novo-label-service.ts
projects/novo-examples/src/components/query-builder/just-criteria/MockMeta.ts

Adjusts checkboxes inside of the <novo-select> overlay when its value was updated via some external process.
Since this change may be high-impact across all <novo-select> instances, the fix is created as a directive, and should only be applied when the problem has some impact.

fix(Select): Provide an optional fix directive for <novo-select> elements

---

projects/novo-elements/src/elements/tabbed-group-picker/TabbedGroupPicker.html
projects/novo-elements/src/elements/tabbed-group-picker/TabbedGroupPicker.spec.ts
projects/novo-elements/src/elements/tabbed-group-picker/TabbedGroupPicker.ts

New automation-value attribute is based on the tab's valueField / name.

test(TabbedGroupPicker): Add data-automation-value attribute

---

projects/novo-elements/src/elements/query-builder/criteria-builder/criteria-builder.component.ts
projects/novo-elements/src/elements/query-builder/query-builder.types.ts

Enabling search criteria to be nested. This is a small novo elements change with bigger Novo ramifications for handling nested searches.

feat(QueryBuilder): Enabling nested search criteria via new types

---

projects/novo-elements/src/elements/common/overlay/Overlay.ts
projects/novo-elements/src/elements/data-table/data-table-clear-button.component.ts
projects/novo-elements/src/elements/data-table/interfaces.ts
projects/novo-elements/src/elements/modal/modal.component.ts
projects/novo-elements/src/elements/query-builder/condition-definitions/string-condition.definition.ts
projects/novo-elements/src/elements/select/Select.ts

- added `novo-dropdown` to novo-notifcation's allowable ng-content
- added `emitOnly` optional input in data-table-clear-button, preventing state-modifying method calls, only emitting a button event.
- added `backDropClicked` eventEmitter to the novo Overlay component
- fixed `string-condition.definition` -- manually setting form to dirty when value is programmatically changed

feat(Novo Notification): added novo-dropdown to ng-content

---

projects/novo-elements/src/elements/date-picker/DatePickerInput.ts

Added hideFooter input to flow down to the DatePicker.

fix(DatePickerInput): Add hideFooter input to pass to DatePicker

---

projects/novo-elements/src/elements/tabbed-group-picker/TabbedGroupPicker.ts

Ensure that when the TabbedGroupPicker opens, its virtual scrolling updates to show the first elements in the list

fix(TabbedGroupPicker): Fix scroll behavior, add to examples

---

projects/novo-elements/src/elements/autocomplete/autocomplete.component.spec.ts
projects/novo-elements/src/elements/autocomplete/autocomplete.component.ts
projects/novo-elements/src/elements/chips/ChipInput.ts
projects/novo-examples/src/components/autocomplete/autocomplete-with-chips/autocomplete-with-chips-example.html

Add an attribute option to immediately activate the first result for autocomplete (rather than waiting for first down key)

feat(Autocomplete): Introduce makeFirstItemActive option

---

projects/novo-elements/src/elements/chips/ChipList.ts

The click / change event now does not change the chipList's value - when set to undefined it was clearing the chiplist.

fix(ChipList): Fixed a bug clearing ChipLists when clicked

---

projects/novo-elements/src/elements/common/overlay/Overlay.ts

When the overlay received a mouse event from a drag that had just completed, it pointed to the ghost version of the element that existed for the drag, and was just removed. All the elements we inspect for being "outside the overlay" should be in the DOM, so this adds that check.

fix(Overlay): Drag events close overlays

---

projects/novo-elements/src/elements/data-table/interfaces.ts

Updating the types to include the new optional "uniqueName" and making the exclude optional, which is backwards compatible and safe because testing exclude using a falsy check will work for "false" or "undefined" or "null". The exclude is not guaranteed to be there if the data is coming in from an outside call. Likewise, uniqueName is not guaranteed from the outside call yet, but should be there going forward, so optional for now.

fix(types): Update keyword types

---

projects/novo-elements/src/elements/query-builder/condition-definitions/address-condition.definition.ts
projects/novo-elements/src/elements/query-builder/query-builder.types.ts

we needed a couple of additional properties (name, types) from the google places API response in our implementation of the query builder, so i added them here and made them optional to retain backwards compatibility.

feat(AddressDef): adding some additional properties to the address obj we set in the query builder

---

projects/novo-elements/src/elements/tooltip/Tooltip.directive.ts
projects/novo-elements/src/elements/tooltip/Tooltip.spec.ts

added a new input closeOnClick and a close event which is executed if closeOnClick is true

fix(Tooltip): Add closeOnClick input to pass to Tooltip

---

projects/novo-elements/src/elements/data-table/interfaces.ts

Clean up and simplify the types that were added for autobuild saved searches, before we release the feature to production.

fix(types): Update autobuild types

---

projects/novo-elements/src/elements/data-table/interfaces.ts

Add an optional type to allow for passing the scoreByEntityId through the where object, which is used for Vector Based Search.

fix(Types): Add scoreByEntityId to the DataTableWhere type

---

projects/novo-elements/src/elements/tabbed-group-picker/TabbedGroupPicker.scss

the groups in the Tabbed Group Picker were indented farther than the nested items they contained, so the hierarchy looked a bit off. this PR gives the groups less indentation.

fix(TabbedGroupPicker): adjusting indentation on groups

---

projects/novo-elements/src/elements/data-table/pagination/data-table-pagination.component.spec.ts
projects/novo-elements/src/elements/data-table/pagination/data-table-pagination.component.ts

when setting the page, we could be setting a page that is not in the currently displayed list of pages. ie when we apply a sort, we will set the page to the first page, but we may have done this while on the 10th page, making the displayed pages [8, 9, 10, 11, 12] which was causing an inconsistency with the 'displayed pages' and the currently displayed page. calling `updateDisplayedPageSizeOptions()` any time we set a page should solve this issue.
fixes #1297

fix(NovoDataTablePagination): updating displayed pages when setting page

---

projects/novo-elements/src/elements/picker/Picker.ts

Added logic for tab output for the Picker component, it will be used for keyboard navigation in adjustments, it is turned off by default.

feat(Picker): Add Optional Keyboard Nav Logic

---

projects/novo-elements/src/elements/tabbed-group-picker/TabbedGroupPicker.spec.ts
projects/novo-elements/src/elements/tabbed-group-picker/TabbedGroupPicker.ts
projects/novo-examples/src/components/tabbed-group-picker/index.ts
projects/novo-examples/src/components/tabbed-group-picker/tabbed-group-picker-footer-example/index.ts
projects/novo-examples/src/components/tabbed-group-picker/tabbed-group-picker-footer-example/tabbed-group-picker-footer-example.html
projects/novo-examples/src/components/tabbed-group-picker/tabbed-group-picker-footer-example/tabbed-group-picker-footer-example.ts
projects/novo-examples/src/components/tabbed-group-picker/tabbed-group-picker.md
projects/novo-examples/src/examples.routes.ts

- Updated Tabbed Group Picker to emit the current tabs (which are reverted to previously applied state already) when cancel is clicked.
- Added a demo for Tabbed Group Picker with a footer that takes advantage of the emitted value on cancel.

fix(TabbedGroupPicker): Emit selected values on cancel

---

package-lock.json
projects/novo-examples/src/examples.routes.ts

just regenerating the package-lock file to pull in some minor/patch version updates of our dependencies. going to start doing this more regularly in the future, and probably look into automating it.

chore(deps): regenerating package-lock

---

projects/novo-elements/src/elements/button/Button.spec.ts
projects/novo-elements/src/elements/button/Button.ts

… events
When we set up a <button> element as a Button.ts component, we want to ensure the native disabled attribute is still set - as this is the best way of blocking keyboard tabbing access to the button.

fix(Button): Set the native disabled attribute

---

projects/novo-elements/src/elements/field/formats/date-range-format.ts
projects/novo-elements/src/elements/field/formats/date-time-format.spec.ts
projects/novo-elements/src/elements/field/formats/date-time-format.ts

This format code is called when clearing values from inputs, which leads to an error when formatting "" that prevents some other logic.
Unit tests pending...

fix(QueryBuilder): Prevent a logic error normalizing dates

---

jest.setup.ts
projects/novo-elements/src/elements/tooltip/Tooltip.directive.ts
projects/novo-examples/src/components/tooltip/tooltip-examples.md
projects/novo-examples/src/components/tooltip/tooltip-overflow/index.ts
projects/novo-examples/src/components/tooltip/tooltip-overflow/tooltip-overflow-example.css
projects/novo-examples/src/components/tooltip/tooltip-overflow/tooltip-overflow-example.html
projects/novo-examples/src/components/tooltip/tooltip-overflow/tooltip-overflow-example.ts
projects/novo-examples/src/examples.routes.ts

Implemented properly reactive tooltip enablement upon width overflow

feat(Tooltip): tooltipOnOverflow, proper reactive resizing enablement

---

projects/novo-elements/src/elements/chips/Chips.module.ts
projects/novo-elements/src/elements/chips/Chips.ts
projects/novo-elements/src/elements/chips/RowChips.ts
projects/novo-elements/src/elements/field/input.ts
projects/novo-examples/src/examples.routes.ts
projects/novo-examples/src/form-controls/chips/row-chips/row-chips-example.ts

just quickly testing out adding checkbox support for row chips

feat(RowChips): testing out supporting checkboxes in row chips

---

projects/novo-elements/src/elements/chips/Chip.scss
projects/novo-elements/src/elements/chips/ChipList.scss
projects/novo-elements/src/elements/query-builder/condition-builder/condition-builder.component.scss
projects/novo-elements/src/elements/query-builder/condition-definitions/address-condition.definition.ts
projects/novo-elements/src/elements/query-builder/condition-definitions/string-condition.definition.ts
projects/novo-elements/src/elements/query-builder/query-builder.module.ts
projects/novo-examples/src/examples.routes.ts

Adds a number of styling changes to the Chip List. This makes use of the new tooltipOnOverflow option so that chips collapse correctly with ellipses (using the new attribute) and do not push their "X" button past the edge of the content.
This MR is based on f/tooltip-on-overflow and will be retargeted once that's merged.

style(Chips/QueryBuilder): Fixes to chip-list width max/ellipsis appearance

---

RELEASE_PROCESS.md

Two-pronged MR. Adds a note to help people avoid the mistake of a missing release, and triggers a release for styling fixes.

fix(Release): added a note to the release process readme

---

projects/novo-elements/src/elements/chips/ChipList.scss

Targeted fix to prevent chip-list being longer than necessary in some cases.

fix(ChipList): Prevent Chips from stretching

---

projects/novo-elements/src/elements/chips/ChipList.scss
projects/novo-examples/src/examples.routes.ts

Changed a negative margin hack into `gap` to prevent bugs where the edge was cut off.

fix(ChipList): Minor styling appearance fix

---

projects/novo-elements/src/elements/date-picker/DatePicker.ts
projects/novo-elements/src/elements/date-picker/DatePickerInput.ts

Added an optional input for DatePickerInput flowing to DatePicker called `dateForInitialView ` to make sure a certain month shows initially in the date picker when opened that is not the current month/date.

feat(DatePicker): Add optional dateForInitialView input

---

projects/novo-elements/src/elements/query-builder/condition-builder/condition-builder.component.ts

I added a reset method that takes a values object where key is the key of the form control and value is the value that should be set for the form control.

feat(Condition Builder): Add reset method to condition builder

---

projects/novo-elements/src/elements/picker/Picker.spec.ts
projects/novo-elements/src/elements/picker/Picker.ts

Added a safety check when clearing the customTextValue on popup instance, which doesn't get created until Picker results are shown. This was causing console logs when a user would try clear a picker on a form before ever expanding the results.

fix(Picker): Add null check when clearing custom text value

---

projects/novo-elements/src/elements/data-table/interfaces.ts

The type has been incorrect for a while now, so fixing the filter value so that it matches up with the current code - the filter value can be any object, string, number, etc.

feat(Types): Fixing data table filter value type

---

projects/novo-elements/src/elements/field/field-fill.scss
projects/novo-elements/src/elements/field/field-standard.scss
projects/novo-elements/src/elements/select/Select.scss

added disabled state styling to novo-field underlined appearance

feat(novo-field): added disabled state styling to novo-field 

---

projects/novo-elements/src/elements/button/Button.ts
projects/novo-examples/src/components/buttons/button-examples.md
projects/novo-examples/src/components/buttons/button-two-icon/button-two-icon-example.css
projects/novo-examples/src/components/buttons/button-two-icon/button-two-icon-example.html
projects/novo-examples/src/components/buttons/button-two-icon/button-two-icon-example.ts
projects/novo-examples/src/components/buttons/button-two-icon/index.ts
projects/novo-examples/src/components/buttons/index.ts

feat(Button): Add support for two icon buttons

---

projects/novo-elements/src/elements/data-table/interfaces.ts

updating some types to support top level ORs and nested ANDs in our keyword search objects.

feat(DataTable): updating some data table types

---

projects/novo-elements/src/elements/picker/extras/grouped-multi-picker-results/GroupedMultiPickerResults.scss

The background visibility of the Grouped Multi Picker Results was not extending the entire length if the Grouped Multi Picker was inside of a modal. This change is to ensure the background fits the length of the results.

fix(GroupedMultiPickerResults): Ensure Background Visibility

---

projects/novo-elements/src/elements/common/overlay/Overlay.ts
projects/novo-elements/src/elements/data-table/cell-headers/data-table-header-cell.component.ts
projects/novo-elements/src/elements/modal/modal.service.ts

- adding accessible overlay ref on modal service
- adding support for contextual custom overlay containers to allow for multiple overlay contexts
- updating the side of the filter icon the data table filter overlay attaches to, to avoid the overlays popping up under left-side menus and bowling alleys

feat(NovoOverlay): contextual custom overlay containers

---

projects/novo-elements/src/elements/field/input.ts
projects/novo-elements/src/elements/query-builder/condition-definitions/abstract-condition.definition.ts
projects/novo-elements/src/elements/query-builder/condition-definitions/address-condition.definition.spec.ts
projects/novo-elements/src/elements/query-builder/condition-definitions/address-condition.definition.ts
projects/novo-elements/src/elements/query-builder/condition-group/condition-group.component.ts
projects/novo-elements/src/elements/query-builder/criteria-builder/criteria-builder.component.ts
projects/novo-elements/src/elements/query-builder/query-builder.types.ts
projects/novo-elements/src/services/novo-label-service.ts
projects/novo-examples/src/components/query-builder/just-criteria/just-criteria-example.ts

For address field in the Query Builder, replaced Radius with Inside Radius and added new Outside Radius operator. Also changed the value field from a dropdown to an integer field.

feat(Query Builder): Replace Radius with Inside Radius and add new Outside Radius operator for address field

---

projects/novo-elements/src/elements/common/typography/label/label.component.ts
projects/novo-elements/src/elements/select/Select.scss
projects/novo-elements/src/elements/select/Select.ts

Sample changes to provide better screenreader accessibility on the <novo-select> component.

fix(Select): Changes to better support screen readers in <novo-select>

---

projects/novo-elements/src/elements/query-builder/condition-definitions/number-condition.definition.ts

…tions
There shouldn't usually be a situation where numerical values can be "null", so this option has not traditionally made sense.

feat(QueryBuilder): Remove Is Empty option from numerical conditions

---

projects/novo-elements/src/elements/common/option/option.component.ts
projects/novo-elements/src/elements/select/Select.ts

- moved `_initLegacyOptions()` call in `ngOnInit` to the more relevent location: 
- after **options** are set -- now via an **@Input** setter, which always beats `ngOnInit` in a race.

fix(Select): novo-select, call _initLegacyOptions sooner to address race condition

---

projects/novo-elements/src/elements/common/directives/accent.directive.ts

This directive had an onDestroy method that was not correctly configured via interface implementation

fix(Accent): Resolve a memory leak

---

projects/novo-elements/src/elements/data-table/interfaces.ts

Making the keywords array no longer required, since the autobuild endpoint doesn't always contain it.

feat(Types): Keywords are no longer required in the autobuild response

---

package-lock.json
package.json
projects/novo-elements/src/elements/select-search/select-search.component.ts
projects/novo-elements/src/elements/select/Select.spec.ts
projects/novo-elements/src/elements/select/Select.ts
projects/novo-examples/src/examples.routes.ts
projects/novo-examples/src/form-controls/select/index.ts
projects/novo-examples/src/form-controls/select/legacy-select-option/index.ts
projects/novo-examples/src/form-controls/select/legacy-select-option/legacy-select-option-example.css
projects/novo-examples/src/form-controls/select/legacy-select-option/legacy-select-option-example.html
projects/novo-examples/src/form-controls/select/legacy-select-option/legacy-select-option-example.ts
projects/novo-examples/src/form-controls/select/select.md
tools/examples-module.ts

When we apply text filtration of <novo-select> options, it can cause the UI to mistakenly show the current value as a "legacy option" - a disabled entry that shows it can no longer be selected. Since these are less useful when the set of options is large, we can just hide it. We've better clarified the code that causes these to display, and provided an example for users. There's also an added option allowing legacy options to be hidden completely in any case.

fix(Select): Hide legacy options select if text-filtered

---

projects/novo-elements/src/elements/select/Select.ts

Reverting the initLegacyOptions call removal from within ngOnInit, for the cases where options are not passed in via @Input (e.g., options via ng-content)

fix(Select): restoring ngOnInit > initLegacyOptions

---

projects/novo-elements/src/elements/field/formats/base-format.ts
projects/novo-elements/src/elements/field/formats/date-format.spec.ts
projects/novo-elements/src/elements/field/formats/date-format.ts
projects/novo-elements/src/elements/query-builder/condition-definitions/date-condition.definition.ts
projects/novo-examples/src/components/query-builder/just-criteria/just-criteria-example.ts

Updated just-criteria-example to better cover display of both Date and Datetime fields
- This adds an "Equals" operator option for the date comparator (not date-time).
- Also adds a new date format for Date Conditions to create a string date (YYYY-MM-DD) without any timezone conversion.

feat(ConditionBuilder): Add an "Equals" operator for Date field

---

projects/novo-elements/src/elements/query-builder/condition-builder/condition-builder.component.scss
projects/novo-elements/src/elements/query-builder/condition-group/condition-group.component.html
projects/novo-elements/src/elements/query-builder/condition-group/condition-group.component.scss

Moved address pin / delete icon to stay at the bottom of the entry region
Moved the Chips search magnifier down to align with other icons

style(ConditionBuilder): Move the icon for address to row bottom

---

projects/novo-elements/src/elements/data-table/cell-headers/data-table-header-cell.component.ts
projects/novo-elements/src/elements/data-table/data-table.component.ts
projects/novo-examples/src/components/data-table/data-table-rows/data-table-rows-example.html
projects/novo-examples/src/components/data-table/data-table-rows/data-table-rows-example.ts
projects/novo-examples/src/components/data-table/extras/mock-data.ts

Enabling alternate behavior for setting up column filters on a table: If their configuration does not include a template for the input popup, then it will output an event with the column name for an outside component to handle.

feat(DataTable): When column filter is type: 'custom' but has no template, emit an event to handle externally

---

projects/novo-elements/src/elements/query-builder/condition-definitions/string-condition.definition.ts

fix(CriteriaBuilder): Rollback fix for criteria builder string condition chiplist bug 

---

projects/novo-elements/src/elements/form/extras/address/Address.ts

Check for validity changes with the Address configuration since field interactions can alter this after initialization

fix(addressComponent): Update valid and invalid arrays when the config required property updates externally
